-- Seed: annexe A recipes (30 originals + linked Protein demo versions).
-- Generated by scripts/seed-recipes.py — idempotent on slug.

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Couscous au poisson', 'couscous-au-poisson', 'Le grand classique tunisien du vendredi : semoule, légumes et poisson en sauce rouge.', 'tunisie', 'plat', 'moyen', 30, 60,
     6, 'parve', true, 1.0, array['chabbat'], 'community', 'boutargue',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '9683'), 900, 'g', 900, 'graine de couscous cuite'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '26023'), 800, 'g', 800, 'mérou ou cabillaud'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20497'), 800, 'g', 800, 'légumes pour couscous'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '20068'), 70, 'g', 70, 'concentré de tomate'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 60, 'ml', 55, 'huile d''olive'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '11112'), 30, 'g', 30, 'harissa'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '11000'), 15, 'g', 15, 'ail'),
    ((select id from r), 7, (select id from public.foods where source = 'ciqual' and external_id = '11042'), 5, 'g', 5, 'cumin')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Fais revenir l''ail, le concentré de tomate et la harissa dans l''huile d''olive.'),
  ((select id from r), 1, 'Ajoute les légumes, couvre d''eau et laisse mijoter 30 minutes.'),
  ((select id from r), 2, 'Pose le poisson sur les légumes et cuis 15 minutes de plus.'),
  ((select id from r), 3, 'Sers la semoule arrosée de bouillon, légumes et poisson par-dessus.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Couscous boulettes', 'couscous-boulettes', 'Couscous du chabbat aux boulettes de bœuf, sauce rouge généreuse.', 'tunisie', 'plat', 'moyen', 40, 75,
     6, 'bassari', false, 1.0, array['chabbat'], 'community', 'boutargue',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '9683'), 900, 'g', 900, 'graine de couscous cuite'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '6254'), 700, 'g', 700, 'bœuf haché 15%'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20497'), 700, 'g', 700, 'légumes pour couscous'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '20034'), 150, 'g', 150, 'oignon'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '20068'), 70, 'g', 70, 'concentré de tomate'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 50, 'ml', 46, 'huile d''olive'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '22000'), 1, 'pièce', 50, 'œuf'),
    ((select id from r), 7, (select id from public.foods where source = 'ciqual' and external_id = '11112'), 20, 'g', 20, 'harissa')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Mélange le bœuf haché avec l''oignon râpé, l''œuf et les épices, forme des boulettes.'),
  ((select id from r), 1, 'Fais-les dorer dans l''huile, réserve.'),
  ((select id from r), 2, 'Prépare la sauce tomate-harissa, ajoute les légumes et de l''eau, mijote 40 minutes.'),
  ((select id from r), 3, 'Remets les boulettes 20 minutes et sers sur la semoule.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Couscous boulettes — version Protéine', 'couscous-boulettes-proteine', 'La version allégée : boulettes de dinde, semoule complète mesurée, moitié moins d''huile.', 'tunisie', 'plat', 'moyen', 35, 60,
     6, 'bassari', false, 1.0, array['chabbat','meal-prep'], 'community', 'proteine',
     (select id from public.recipes where slug = 'couscous-boulettes'), 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '9683'), 720, 'g', 720, 'graine de couscous cuite'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '36306'), 700, 'g', 700, 'escalope de dinde hachée'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20497'), 900, 'g', 900, 'légumes pour couscous'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '20034'), 150, 'g', 150, 'oignon'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '20068'), 70, 'g', 70, 'concentré de tomate'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 25, 'ml', 23, 'huile d''olive'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '22000'), 1, 'pièce', 50, 'œuf'),
    ((select id from r), 7, (select id from public.foods where source = 'ciqual' and external_id = '11112'), 20, 'g', 20, 'harissa')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Forme des boulettes de dinde avec l''oignon, l''œuf et les épices.'),
  ((select id from r), 1, 'Cuis-les directement dans la sauce tomate (pas de friture).'),
  ((select id from r), 2, 'Ajoute beaucoup de légumes et mijote 40 minutes.'),
  ((select id from r), 3, 'Sers avec la semoule pesée : 120 g cuits par personne.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Brik à l''œuf', 'brik-a-l-oeuf', 'La brik croustillante à l''œuf coulant, thon et câpres.', 'tunisie', 'entree', 'facile', 15, 10,
     4, 'parve', true, 1.0, array['express'], 'community', 'boutargue',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '51550'), 4, 'pièce', 80, 'feuilles de brick'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '22000'), 4, 'pièce', 200, 'œufs'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '26039'), 120, 'g', 120, 'thon au naturel'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '11040'), 20, 'g', 20, 'câpres'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '11014'), 10, 'g', 10, 'persil'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '17440'), 40, 'ml', 37, 'huile de friture')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Dépose thon, câpres, persil et un œuf cru au centre de chaque feuille.'),
  ((select id from r), 1, 'Plie en triangle en soudant les bords.'),
  ((select id from r), 2, 'Fais frire 2 minutes par face jusqu''à dorure.'),
  ((select id from r), 3, 'Sers immédiatement avec un quartier de citron, l''œuf doit couler.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Brik à l''œuf — version Protéine', 'brik-a-l-oeuf-proteine', 'La brik au four : croustillante, deux fois moins grasse.', 'tunisie', 'entree', 'facile', 15, 12,
     4, 'parve', true, 1.0, array['express'], 'community', 'proteine',
     (select id from public.recipes where slug = 'brik-a-l-oeuf'), 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '51550'), 4, 'pièce', 80, 'feuilles de brick'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '22000'), 4, 'pièce', 200, 'œufs'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '26039'), 160, 'g', 160, 'thon au naturel'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '11040'), 20, 'g', 20, 'câpres'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '11014'), 10, 'g', 10, 'persil'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 10, 'ml', 9, 'huile d''olive')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Badigeonne légèrement les feuilles d''huile d''olive au pinceau.'),
  ((select id from r), 1, 'Garnis de thon, câpres, persil et d''un œuf, plie en triangle.'),
  ((select id from r), 2, 'Enfourne 10-12 minutes à 200 °C sur une plaque chaude.'),
  ((select id from r), 3, 'Sers dès la sortie du four.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Pkaila aux haricots', 'pkaila', 'Le plat mijoté tunisien aux épinards confits et haricots blancs.', 'tunisie', 'plat', 'difficile', 40, 180,
     8, 'bassari', false, 1.0, array['chabbat','meal-prep'], 'community', 'boutargue',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '20027'), 1500, 'g', 1500, 'épinards ou blettes'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '20511'), 500, 'g', 500, 'haricots blancs'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '6101'), 600, 'g', 600, 'bœuf à braiser'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 120, 'ml', 110, 'huile d''olive'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '20034'), 200, 'g', 200, 'oignon'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '11000'), 20, 'g', 20, 'ail'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '11027'), 5, 'g', 5, 'menthe séchée')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Fais réduire les épinards à sec puis confis-les longuement dans l''huile jusqu''à couleur très foncée.'),
  ((select id from r), 1, 'Ajoute oignon, ail, viande et fais revenir.'),
  ((select id from r), 2, 'Couvre d''eau, ajoute les haricots et mijote 2 h 30 à feu doux.'),
  ((select id from r), 3, 'Rectifie et sers avec du couscous ou du pain.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Loubia', 'loubia', 'Haricots blancs en sauce rouge, le réconfort du dimanche soir.', 'algerie', 'plat', 'facile', 15, 60,
     6, 'parve', false, 1.0, array['meal-prep'], 'community', 'boutargue',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '20511'), 750, 'g', 750, 'haricots blancs'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '20068'), 60, 'g', 60, 'concentré de tomate'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20034'), 150, 'g', 150, 'oignon'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '11000'), 15, 'g', 15, 'ail'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 50, 'ml', 46, 'huile d''olive'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '11042'), 8, 'g', 8, 'cumin'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '11112'), 15, 'g', 15, 'harissa')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Fais revenir l''oignon et l''ail dans l''huile.'),
  ((select id from r), 1, 'Ajoute concentré, cumin, harissa et un verre d''eau.'),
  ((select id from r), 2, 'Verse les haricots, couvre et mijote 45 minutes.'),
  ((select id from r), 3, 'Sers brûlant avec un filet d''huile d''olive.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Mloukhia', 'mloukhia', 'La sauce noire tunisienne à la corète, mijotée des heures avec la viande.', 'tunisie', 'plat', 'difficile', 20, 240,
     8, 'bassari', false, 1.0, array['fete','meal-prep'], 'community', 'boutargue',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, null, 250, 'g', 250, 'poudre de mloukhia (corète)'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '6101'), 800, 'g', 800, 'bœuf à braiser'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 200, 'ml', 184, 'huile d''olive'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '11000'), 30, 'g', 30, 'ail'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '20068'), 30, 'g', 30, 'concentré de tomate'),
    ((select id from r), 5, null, 2, 'pièce', 1, 'laurier')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Délaye la poudre de mloukhia dans l''huile à froid.'),
  ((select id from r), 1, 'Ajoute de l''eau progressivement en fouettant, puis l''ail et le laurier.'),
  ((select id from r), 2, 'Mijote 3 à 4 heures à feu très doux en remuant, la sauce doit devenir noire et nappante.'),
  ((select id from r), 3, 'Ajoute la viande à mi-cuisson et sers avec du pain.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Nikitouches', 'nikitouches', 'La soupe de petites pâtes au bouillon de poulet des grands-mères tunes.', 'tunisie', 'plat', 'facile', 15, 45,
     6, 'bassari', false, 1.0, array['chabbat'], 'community', 'boutargue',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '9822'), 300, 'g', 300, 'petites pâtes aux œufs'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '36016'), 600, 'g', 600, 'poulet'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20034'), 100, 'g', 100, 'oignon'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '20023'), 80, 'g', 80, 'céleri branche'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '20009'), 150, 'g', 150, 'carotte'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '11174'), 10, 'g', 10, 'bouillon de volaille')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Fais un bouillon avec le poulet, l''oignon, le céleri et la carotte, 40 minutes.'),
  ((select id from r), 1, 'Retire le poulet, effiloche-le.'),
  ((select id from r), 2, 'Cuis les nikitouches directement dans le bouillon.'),
  ((select id from r), 3, 'Remets le poulet effiloché et sers bien chaud.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Tfina / Dafina', 'tfina', 'Le plat chaud du chabbat : mijoté toute la nuit, pommes de terre confites, œufs bruns.', 'maroc', 'plat', 'moyen', 30, 720,
     8, 'bassari', false, 1.0, array['chabbat'], 'community', 'boutargue',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '6101'), 800, 'g', 800, 'bœuf à braiser'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '4026'), 1000, 'g', 1000, 'pommes de terre'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20532'), 400, 'g', 400, 'pois chiches'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '22010'), 8, 'pièce', 400, 'œufs entiers en coquille'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '9691'), 200, 'g', 200, 'riz ou blé'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '17440'), 40, 'ml', 37, 'huile'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '31008'), 20, 'g', 20, 'miel')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Dispose viande, pois chiches, pommes de terre, œufs en coquille et blé dans une grande marmite.'),
  ((select id from r), 1, 'Couvre d''eau, assaisonne, ajoute le miel.'),
  ((select id from r), 2, 'Enfourne à 100 °C avant chabbat et laisse toute la nuit.'),
  ((select id from r), 3, 'Sers samedi midi : tout doit être confit et caramel.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Tershi de potiron', 'tershi', 'La purée de courge relevée à l''harissa et au citron — kémia essentielle.', 'tunisie', 'kemia', 'facile', 10, 20,
     4, 'parve', false, 1.0, array['express','sans-gluten'], 'community', 'proteine',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '20096'), 800, 'g', 800, 'potiron'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '11000'), 10, 'g', 10, 'ail'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '11112'), 20, 'g', 20, 'harissa'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 30, 'ml', 28, 'huile d''olive'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '13009'), 40, 'g', 40, 'citron'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '11042'), 4, 'g', 4, 'carvi ou cumin')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Cuis le potiron à l''eau ou vapeur, égoutte bien.'),
  ((select id from r), 1, 'Écrase à la fourchette avec l''ail pilé, la harissa et le cumin.'),
  ((select id from r), 2, 'Monte avec l''huile d''olive et le jus de citron.'),
  ((select id from r), 3, 'Sers frais avec du pain ou en kémia.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Slata méchouia', 'slata-mechouia', 'Poivrons et tomates grillés, écrasés à l''huile d''olive — LA salade tunisienne.', 'tunisie', 'kemia', 'facile', 15, 25,
     4, 'parve', false, 1.0, array['sans-gluten'], 'community', 'proteine',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '20086'), 500, 'g', 500, 'poivrons'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '20047'), 400, 'g', 400, 'tomates'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '11000'), 10, 'g', 10, 'ail'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 40, 'ml', 37, 'huile d''olive'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '13009'), 30, 'g', 30, 'citron'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '13033'), 30, 'g', 30, 'olives et câpres')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Grille poivrons et tomates au four ou à la flamme jusqu''à peau noircie.'),
  ((select id from r), 1, 'Pèle, épépine et hache grossièrement au couteau.'),
  ((select id from r), 2, 'Assaisonne avec ail pilé, huile d''olive, citron, sel.'),
  ((select id from r), 3, 'Décore d''olives, de câpres et éventuellement de thon ou d''œuf dur.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Salade de carottes au cumin', 'salade-carottes-cumin', 'Carottes fondantes, ail, cumin, citron : la kémia la plus simple et la plus fraîche.', 'maroc', 'kemia', 'facile', 10, 15,
     4, 'parve', false, 1.0, array['express','sans-gluten'], 'community', 'proteine',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '20008'), 600, 'g', 600, 'carottes'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '11000'), 8, 'g', 8, 'ail'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '11042'), 6, 'g', 6, 'cumin'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 25, 'ml', 23, 'huile d''olive'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '13009'), 30, 'g', 30, 'citron'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '11112'), 10, 'g', 10, 'harissa (option)')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Cuis les carottes en rondelles à l''eau salée, al dente.'),
  ((select id from r), 1, 'Mélange ail pilé, cumin, harissa, huile et citron.'),
  ((select id from r), 2, 'Enrobe les carottes tièdes de cette sauce.'),
  ((select id from r), 3, 'Laisse mariner 1 heure au frais avant de servir.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Plateau de kémia', 'plateau-kemia', 'L''apéro tunisien complet : olives, tershi, méchouia, œufs, pickles.', 'tunisie', 'kemia', 'facile', 20, 0,
     6, 'parve', false, 1.0, array['chabbat','fete'], 'community', 'boutargue',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '13033'), 150, 'g', 150, 'olives assorties'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '22010'), 3, 'pièce', 150, 'œufs durs'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '26039'), 100, 'g', 100, 'thon au naturel'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '11112'), 30, 'g', 30, 'harissa'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '20210'), 100, 'g', 100, 'concombre en pickles'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '7001'), 150, 'g', 150, 'baguette'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 20, 'ml', 18, 'huile d''olive')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Dispose chaque préparation dans une petite coupelle.'),
  ((select id from r), 1, 'Coupe les œufs durs en quartiers, arrose d''huile d''olive.'),
  ((select id from r), 2, 'Sers avec le pain et les boissons fraîches.'),
  ((select id from r), 3, 'La règle : petit, généreux, convivial.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Boutargue tranchée', 'boutargue-tranchee', 'Fines tranches de boutargue, huile d''olive et citron. Le luxe simple.', 'tunisie', 'kemia', 'facile', 5, 0,
     4, 'parve', true, 1.0, array['fete','sans-gluten','express'], 'community', 'boutargue',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '26004'), 80, 'g', 80, 'boutargue (œufs de mulet séchés)'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 20, 'ml', 18, 'huile d''olive'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '13009'), 30, 'g', 30, 'citron')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Tranche la boutargue le plus finement possible.'),
  ((select id from r), 1, 'Arrose d''huile d''olive et de quelques gouttes de citron.'),
  ((select id from r), 2, 'Sers avec des piques, sans rien d''autre.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Chakchouka', 'chakchouka', 'Poivrons, tomates, œufs pochés dans la sauce — avec ou sans feta.', 'tunisie', 'plat', 'facile', 15, 25,
     4, 'halavi', false, 1.0, array['express'], 'community', 'proteine',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '20086'), 400, 'g', 400, 'poivrons'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '20047'), 500, 'g', 500, 'tomates'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20034'), 100, 'g', 100, 'oignon'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '22000'), 4, 'pièce', 200, 'œufs'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '12066'), 100, 'g', 100, 'feta'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 25, 'ml', 23, 'huile d''olive'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '11112'), 15, 'g', 15, 'harissa')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Fais compoter oignon et poivrons dans l''huile 10 minutes.'),
  ((select id from r), 1, 'Ajoute tomates et harissa, mijote 10 minutes.'),
  ((select id from r), 2, 'Casse les œufs dans la sauce, couvre 5 minutes.'),
  ((select id from r), 3, 'Émiette la feta, poivre et sers à la poêle.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Fricassé tunisien', 'fricasse', 'Le petit pain frit garni thon-harissa-olives-citron confit.', 'tunisie', 'entree', 'moyen', 45, 15,
     6, 'parve', true, 1.0, array['fete'], 'community', 'boutargue',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '9435'), 500, 'g', 500, 'farine'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '22000'), 1, 'pièce', 50, 'œuf'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '17440'), 100, 'ml', 92, 'huile de friture'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '26039'), 200, 'g', 200, 'thon au naturel'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '4026'), 200, 'g', 200, 'pommes de terre'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '13033'), 60, 'g', 60, 'olives'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '11112'), 30, 'g', 30, 'harissa'),
    ((select id from r), 7, (select id from public.foods where source = 'ciqual' and external_id = '11040'), 20, 'g', 20, 'câpres')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Prépare une pâte levée avec farine, œuf, levure et un peu d''eau ; laisse pousser 1 heure.'),
  ((select id from r), 1, 'Façonne des petits pains et fais-les frire.'),
  ((select id from r), 2, 'Fends-les et garnis : thon, pomme de terre, olives, harissa, câpres.'),
  ((select id from r), 3, 'Sers tiède, avec du citron.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Complet poisson', 'complet-poisson', 'L''assiette tunisienne complète : poisson grillé, riz ou frites, méchouia, œuf.', 'tunisie', 'plat', 'moyen', 25, 30,
     4, 'parve', true, 1.0, '{}', 'community', 'proteine',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '26109'), 700, 'g', 700, 'dorade ou loup'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '9104'), 500, 'g', 500, 'riz cuit'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20086'), 250, 'g', 250, 'poivrons grillés'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '20047'), 200, 'g', 200, 'tomates'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '22010'), 2, 'pièce', 100, 'œufs durs'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 30, 'ml', 28, 'huile d''olive'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '13009'), 40, 'g', 40, 'citron')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Grille le poisson entier au four avec citron et huile.'),
  ((select id from r), 1, 'Prépare une méchouia rapide avec poivrons et tomates grillés.'),
  ((select id from r), 2, 'Dresse l''assiette : poisson, riz, méchouia, demi-œuf dur.'),
  ((select id from r), 3, 'Arrose de citron et d''un filet d''huile.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Mekbouba', 'mekbouba', 'La compotée tomates-poivrons-piments confite à l''huile, servie tiède ou froide.', 'tunisie', 'kemia', 'facile', 15, 40,
     4, 'parve', false, 1.0, array['sans-gluten','meal-prep'], 'community', 'proteine',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '20086'), 500, 'g', 500, 'poivrons et piments doux'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '20047'), 600, 'g', 600, 'tomates'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '11000'), 15, 'g', 15, 'ail'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 40, 'ml', 37, 'huile d''olive')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Coupe poivrons et tomates en gros dés.'),
  ((select id from r), 1, 'Confis à feu doux dans l''huile avec l''ail 40 minutes.'),
  ((select id from r), 2, 'Écrase grossièrement en fin de cuisson.'),
  ((select id from r), 3, 'Sers tiède avec un œuf ou froid en kémia.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Marka hlou', 'marka-hlou', 'Le mijoté sucré-salé aux pruneaux et à la cannelle des fêtes.', 'tunisie', 'plat', 'moyen', 20, 90,
     6, 'bassari', false, 1.0, array['fete'], 'community', 'boutargue',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '21506'), 700, 'g', 700, 'bœuf ou agneau'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '13011'), 250, 'g', 250, 'pruneaux et fruits secs'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20034'), 150, 'g', 150, 'oignon'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '31008'), 40, 'g', 40, 'miel'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '17440'), 30, 'ml', 28, 'huile'),
    ((select id from r), 5, null, 5, 'g', 5, 'cannelle')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Fais dorer la viande avec l''oignon dans l''huile.'),
  ((select id from r), 1, 'Couvre d''eau, ajoute cannelle et mijote 1 heure.'),
  ((select id from r), 2, 'Ajoute fruits secs et miel, poursuis 30 minutes.'),
  ((select id from r), 3, 'La sauce doit être sirupeuse ; sers pour Roch Hachana.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Boulettes de poisson en sauce', 'boulettes-poisson', 'Boulettes de poisson blanc, sauce tomate safranée piquante.', 'tunisie', 'plat', 'moyen', 30, 40,
     4, 'parve', true, 1.0, '{}', 'community', 'proteine',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '26095'), 600, 'g', 600, 'merlan ou cabillaud haché'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '22000'), 1, 'pièce', 50, 'œuf'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '11094'), 20, 'g', 20, 'persil et coriandre'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '20068'), 50, 'g', 50, 'concentré de tomate'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '11000'), 15, 'g', 15, 'ail'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 30, 'ml', 28, 'huile d''olive'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '11112'), 15, 'g', 15, 'harissa')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Mixe le poisson avec l''œuf, les herbes, sel et poivre ; forme des boulettes.'),
  ((select id from r), 1, 'Prépare une sauce tomate ail-harissa.'),
  ((select id from r), 2, 'Poche les boulettes 20 minutes dans la sauce frémissante.'),
  ((select id from r), 3, 'Sers avec du riz ou du pain complet.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Poulet aux olives et citron confit', 'poulet-olives-citron', 'Tajine marocain fondant, olives vertes et citron confit.', 'maroc', 'plat', 'facile', 20, 60,
     4, 'bassari', false, 1.0, '{}', 'community', 'proteine',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '36033'), 900, 'g', 900, 'poulet rôti'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '13033'), 120, 'g', 120, 'olives vertes'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '13009'), 60, 'g', 60, 'citron confit'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '20034'), 200, 'g', 200, 'oignon'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '11000'), 15, 'g', 15, 'ail'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 30, 'ml', 28, 'huile d''olive'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '11094'), 15, 'g', 15, 'coriandre fraîche')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Fais revenir l''oignon, l''ail et les épices dans l''huile.'),
  ((select id from r), 1, 'Ajoute le poulet, dore sur toutes les faces.'),
  ((select id from r), 2, 'Mouille à hauteur, ajoute olives et citron confit, mijote 45 minutes.'),
  ((select id from r), 3, 'Parsème de coriandre et sers avec semoule ou pommes vapeur.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Tajine de kefta', 'tajine-kefta', 'Boulettes de bœuf épicées, sauce tomate, œufs pochés au centre.', 'maroc', 'plat', 'facile', 25, 35,
     4, 'bassari', false, 1.0, '{}', 'community', 'boutargue',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '6254'), 600, 'g', 600, 'bœuf haché'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '20047'), 600, 'g', 600, 'tomates'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20034'), 120, 'g', 120, 'oignon'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '22000'), 4, 'pièce', 200, 'œufs'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 30, 'ml', 28, 'huile d''olive'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '11042'), 10, 'g', 10, 'cumin et paprika'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '11094'), 15, 'g', 15, 'coriandre')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Assaisonne le haché avec oignon râpé, cumin, paprika ; roule des keftas.'),
  ((select id from r), 1, 'Fais réduire les tomates en sauce dans l''huile.'),
  ((select id from r), 2, 'Poche les keftas 15 minutes dans la sauce.'),
  ((select id from r), 3, 'Casse les œufs au centre, couvre 5 minutes et sers dans le plat.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Hraimi', 'hraimi', 'Poisson en sauce rouge pimentée, spécialité de Tripoli servie le vendredi soir.', 'tunisie', 'plat', 'moyen', 15, 35,
     4, 'parve', true, 1.0, array['chabbat'], 'community', 'proteine',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '26023'), 700, 'g', 700, 'cabillaud ou mérou en darnes'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '20068'), 70, 'g', 70, 'concentré de tomate'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '11000'), 20, 'g', 20, 'ail'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '11112'), 25, 'g', 25, 'harissa'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 40, 'ml', 37, 'huile d''olive'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '11042'), 8, 'g', 8, 'cumin et carvi'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '13009'), 30, 'g', 30, 'citron')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Fais revenir ail, concentré, harissa et épices dans l''huile.'),
  ((select id from r), 1, 'Ajoute un verre d''eau et laisse épaissir 10 minutes.'),
  ((select id from r), 2, 'Pose les darnes dans la sauce, couvre et cuis 20 minutes.'),
  ((select id from r), 3, 'Termine au citron ; sers tiède avec du pain.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Sabich', 'sabich', 'La pita israélienne : aubergine, œuf, tahin, crudités.', 'israel', 'plat', 'facile', 20, 20,
     4, 'parve', false, 1.0, array['express'], 'community', 'proteine',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '7180'), 4, 'pièce', 320, 'pains pita'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '20002'), 500, 'g', 500, 'aubergines'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '22010'), 4, 'pièce', 200, 'œufs durs'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '15203'), 60, 'g', 60, 'tahin'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '20210'), 150, 'g', 150, 'concombre'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '20047'), 200, 'g', 200, 'tomates'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 30, 'ml', 28, 'huile d''olive')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Rôtis les tranches d''aubergine badigeonnées d''huile au four.'),
  ((select id from r), 1, 'Prépare une salade concombre-tomate et une sauce tahin-citron.'),
  ((select id from r), 2, 'Garnis les pitas : aubergine, œuf dur en tranches, salade.'),
  ((select id from r), 3, 'Nappe de tahin, ajoute zhoug ou amba si tu aimes.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Bouillon de poulet & kneidlach', 'bouillon-kneidlach', 'Le bouillon doré ashkénaze et ses quenelles moelleuses.', 'ashkenaze', 'plat', 'moyen', 30, 90,
     6, 'bassari', false, 1.0, array['chabbat','fete'], 'community', 'boutargue',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '36016'), 800, 'g', 800, 'poulet'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '20009'), 200, 'g', 200, 'carottes'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20023'), 100, 'g', 100, 'céleri'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '20034'), 120, 'g', 120, 'oignon'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '9435'), 150, 'g', 150, 'farine de matza'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '22000'), 2, 'pièce', 100, 'œufs'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '17440'), 30, 'ml', 28, 'huile')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Fais frémir le poulet avec les légumes 1 heure, écume.'),
  ((select id from r), 1, 'Mélange farine de matza, œufs, huile et un peu de bouillon ; repos 30 minutes au frais.'),
  ((select id from r), 2, 'Forme des boules et poche-les 30 minutes dans le bouillon.'),
  ((select id from r), 3, 'Sers le bouillon filtré avec les kneidlach et des carottes.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Hallah tressée', 'hallah', 'Le pain brioché du chabbat, doré et moelleux.', 'ashkenaze', 'pain', 'moyen', 30, 35,
     8, 'parve', false, 1.0, array['chabbat'], 'community', 'boutargue',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '9435'), 500, 'g', 500, 'farine'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '22000'), 2, 'pièce', 100, 'œufs'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '31016'), 60, 'g', 60, 'sucre'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '17440'), 60, 'ml', 55, 'huile'),
    ((select id from r), 4, null, 10, 'g', 10, 'levure de boulanger'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '15203'), 10, 'g', 10, 'graines de sésame (option)')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Pétris farine, levure, sucre, œuf, huile et eau tiède ; laisse doubler 1 h 30.'),
  ((select id from r), 1, 'Dégaze, divise en trois boudins et tresse.'),
  ((select id from r), 2, 'Laisse pousser 45 minutes, dore à l''œuf, parsème de graines.'),
  ((select id from r), 3, 'Cuis 30-35 minutes à 180 °C.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Kugel de nouilles', 'kugel', 'Le gratin sucré-salé de nouilles ashkénaze, entre dessert et plat.', 'ashkenaze', 'plat', 'facile', 15, 45,
     8, 'halavi', false, 1.0, array['fete'], 'community', 'boutargue',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '9822'), 500, 'g', 500, 'nouilles aux œufs cuites'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '22000'), 3, 'pièce', 150, 'œufs'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '19410'), 150, 'g', 150, 'crème fraîche'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '16400'), 50, 'g', 50, 'beurre'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '31016'), 60, 'g', 60, 'sucre'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '13011'), 80, 'g', 80, 'raisins secs'),
    ((select id from r), 6, null, 4, 'g', 4, 'cannelle')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Mélange les nouilles cuites avec œufs battus, crème, sucre, cannelle et raisins.'),
  ((select id from r), 1, 'Verse dans un plat beurré.'),
  ((select id from r), 2, 'Cuis 45 minutes à 180 °C jusqu''à dorure.'),
  ((select id from r), 3, 'Sers tiède ou froid, en carrés.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Makrouds', 'makrouds', 'Losanges de semoule fourrés aux dattes, frits et trempés dans le miel.', 'tunisie', 'dessert', 'difficile', 60, 20,
     10, 'parve', false, 1.0, array['fete'], 'community', 'boutargue',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '9610'), 500, 'g', 500, 'semoule moyenne'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '13011'), 300, 'g', 300, 'pâte de dattes'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '17440'), 150, 'ml', 138, 'huile'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '31008'), 200, 'g', 200, 'miel'),
    ((select id from r), 4, null, 20, 'ml', 20, 'fleur d''oranger')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Sable la semoule avec l''huile, mouille à l''eau de fleur d''oranger, repos 30 minutes.'),
  ((select id from r), 1, 'Étale un boudin de pâte, insère la pâte de dattes au centre, referme.'),
  ((select id from r), 2, 'Coupe en losanges et fais frire jusqu''à dorure.'),
  ((select id from r), 3, 'Trempe immédiatement dans le miel chaud.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Yoyos', 'yoyos', 'Les beignets de Hanouka à l''orange, glacés au miel.', 'tunisie', 'dessert', 'moyen', 25, 20,
     8, 'parve', false, 1.0, array['hanouka','fete'], 'community', 'boutargue',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '9435'), 400, 'g', 400, 'farine'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '22000'), 2, 'pièce', 100, 'œufs'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '2070'), 100, 'ml', 100, 'jus d''orange'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '31016'), 50, 'g', 50, 'sucre'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '17440'), 120, 'ml', 110, 'huile de friture'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '31008'), 150, 'g', 150, 'miel')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Mélange farine, œufs, jus d''orange, sucre et levure en pâte souple.'),
  ((select id from r), 1, 'Forme des anneaux et laisse reposer 20 minutes.'),
  ((select id from r), 2, 'Fais frire jusqu''à belle couleur.'),
  ((select id from r), 3, 'Trempe dans le miel citronné et laisse égoutter.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Debla', 'debla', 'Rubans de pâte frits en rosace, nappés de miel — la fleur des fêtes.', 'tunisie', 'dessert', 'difficile', 45, 20,
     10, 'parve', false, 1.0, array['fete'], 'community', 'boutargue',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '9435'), 350, 'g', 350, 'farine'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '22000'), 3, 'pièce', 150, 'œufs'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '17440'), 130, 'ml', 120, 'huile de friture'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '31008'), 250, 'g', 250, 'miel'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '15203'), 20, 'g', 20, 'graines de sésame'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '13009'), 20, 'g', 20, 'citron')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Prépare une pâte ferme aux œufs, étale-la très finement en longs rubans.'),
  ((select id from r), 1, 'Enroule chaque ruban sur une fourchette dans l''huile chaude pour former la rosace.'),
  ((select id from r), 2, 'Égoutte puis trempe dans le miel au citron.'),
  ((select id from r), 3, 'Parsème de sésame et laisse sécher.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Banatages', 'banatages', 'Croquettes de pomme de terre farcies à la viande, dorées à la poêle.', 'tunisie', 'entree', 'moyen', 40, 20,
     6, 'bassari', false, 1.0, array['fete'], 'community', 'boutargue',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '4026'), 800, 'g', 800, 'pommes de terre'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '6254'), 350, 'g', 350, 'bœuf haché'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20034'), 100, 'g', 100, 'oignon'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '22000'), 2, 'pièce', 100, 'œufs'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '11014'), 15, 'g', 15, 'persil'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '17440'), 80, 'ml', 74, 'huile de friture')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Écrase les pommes de terre cuites en purée ferme.'),
  ((select id from r), 1, 'Fais revenir le haché avec oignon et persil.'),
  ((select id from r), 2, 'Farcis des galettes de purée avec la viande, referme en quenelles.'),
  ((select id from r), 3, 'Passe à l''œuf battu et fais dorer à la poêle.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Mafroum', 'mafroum', 'Pommes de terre farcies à la viande, mijotées en sauce rouge — trésor de Tripoli.', 'tunisie', 'plat', 'difficile', 50, 90,
     6, 'bassari', false, 1.0, array['chabbat','fete'], 'community', 'boutargue',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '4026'), 1000, 'g', 1000, 'pommes de terre'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '6254'), 500, 'g', 500, 'bœuf haché'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20034'), 120, 'g', 120, 'oignon'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '11014'), 25, 'g', 25, 'persil et coriandre'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '22000'), 1, 'pièce', 50, 'œuf'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '20068'), 60, 'g', 60, 'concentré de tomate'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '17440'), 60, 'ml', 55, 'huile')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Taille les pommes de terre en portefeuilles, farcis-les du haché assaisonné.'),
  ((select id from r), 1, 'Passe à la farine et à l''œuf, fais dorer.'),
  ((select id from r), 2, 'Range dans la sauce tomate et mijote 1 h 15 à couvert.'),
  ((select id from r), 3, 'Sers avec semoule ou pain, la sauce doit napper.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Salade d''oranges aux olives', 'salade-orange-olive', 'Oranges, olives noires, oignon doux et cumin — fraîcheur d''hiver.', 'maroc', 'kemia', 'facile', 10, 0,
     4, 'parve', false, 1.0, array['express','sans-gluten'], 'community', 'proteine',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '2070'), 500, 'g', 500, 'oranges'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '13033'), 80, 'g', 80, 'olives noires'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20034'), 60, 'g', 60, 'oignon rouge'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 20, 'ml', 18, 'huile d''olive'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '11042'), 3, 'g', 3, 'cumin')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Pèle les oranges à vif et tranche-les en rondelles.'),
  ((select id from r), 1, 'Répartis olives et oignon émincé par-dessus.'),
  ((select id from r), 2, 'Assaisonne d''huile d''olive, cumin et une pincée de piment.'),
  ((select id from r), 3, 'Sers très frais.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, origin, category, difficulty, prep_min, cook_min,
     servings, kashrut_class, is_fish, kashrut_confidence, tags, visibility, version_kind,
     parent_recipe_id, status)
  values
    (null, 'Harira', 'harira', 'La soupe marocaine aux pois chiches, lentilles et tomates.', 'maroc', 'plat', 'moyen', 20, 50,
     6, 'parve', false, 1.0, array['meal-prep'], 'community', 'proteine',
     null, 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '20532'), 300, 'g', 300, 'pois chiches'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '20515'), 150, 'g', 150, 'pois cassés ou lentilles'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20047'), 500, 'g', 500, 'tomates'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '20034'), 120, 'g', 120, 'oignon'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '20023'), 60, 'g', 60, 'céleri et coriandre'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 30, 'ml', 28, 'huile d''olive'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '9435'), 30, 'g', 30, 'farine (liaison)')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text)
select * from (values
  ((select id from r), 0, 'Fais revenir oignon, céleri et épices dans l''huile.'),
  ((select id from r), 1, 'Ajoute tomates mixées, légumineuses et 1,5 L d''eau ; mijote 40 minutes.'),
  ((select id from r), 2, 'Lie avec la farine délayée, cuis 5 minutes.'),
  ((select id from r), 3, 'Sers avec coriandre fraîche, citron et dattes.')
) as v(recipe_id, position, text)
where exists (select 1 from r);

update public.recipes
set nutrition_per_serving = coalesce(public.compute_recipe_nutrition(id), '{}'::jsonb)
where author_id is null;
