# Starter recipes, theme "brunch & apéro": breakfasts, breads, apéro bites,
# drinks and sides. Original texts; ingredients pinned to Ciqual foods by
# external_id. Same tuple shape as scripts/seed-world-recipes.py.

R = [
    # ── Petit-déjeuner ────────────────────────────────────────────────
    (
        "granola-maison", "Granola maison",
        "Des flocons d'avoine grillés au four avec amandes, noisettes et sirop d'érable, pour des matins croustillants.",
        "🥣", "etats_unis", "petit_dej", "facile", 10, 25, 10, ["batch-cooking", "four", "vegan"],
        [
            ("flocons d'avoine", 300, "g", 300, "9311"),
            ("amandes", 80, "g", 80, "15000"),
            ("noisettes", 60, "g", 60, "15004"),
            ("sirop d'érable", 8, "càs", 120, "31034"),
            ("huile de tournesol", 4, "càs", 50, "17440"),
            ("cannelle en poudre", 1, "càc", 3, "11025"),
            ("raisins secs", 60, "g", 60, "13046"),
            ("sel", 1, "pincée", 1, None),
        ],
        [
            ("Préchauffe le four à 160 °C et couvre une grande plaque de papier cuisson.", None),
            ("Concasse grossièrement les amandes et les noisettes.", None),
            ("Mélange les flocons, les fruits secs concassés, la cannelle et le sel.", None),
            ("Ajoute le sirop d'érable et l'huile, remue pour bien enrober le tout.", None),
            ("Étale sur la plaque et enfourne en remuant à mi-cuisson, jusqu'à ce que ce soit doré.", 25),
            ("Laisse refroidir sans toucher pour garder des grappes, puis ajoute les raisins secs et conserve en bocal.", None),
        ],
    ),
    (
        "avocado-toast", "Avocado toast",
        "Une tartine de pain de campagne grillé, avocat écrasé au citron vert, graines de sésame et une pointe de piment.",
        "🥑", "autre", "petit_dej", "facile", 10, 3, 2, ["express", "vegan"],
        [
            ("pain de campagne", 2, "tranche", 100, "7261"),
            ("avocat bien mûr", 1, "pièce", 150, "13004"),
            ("citron vert", 0.5, "pièce", 20, "13067"),
            ("huile d'olive", 1, "càs", 10, "17270"),
            ("graines de sésame", 1, "càc", 4, "15010"),
            ("piment en flocons (facultatif)", 1, "pincée", 1, "11088"),
            ("sel", 1, "pincée", 1, None),
        ],
        [
            ("Fais griller les tranches de pain jusqu'à ce qu'elles soient bien croustillantes.", 3),
            ("Écrase la chair de l'avocat à la fourchette avec le jus de citron vert et le sel.", None),
            ("Arrose le pain d'un filet d'huile d'olive, puis étale l'avocat en gardant un peu de texture.", None),
            ("Parsème de sésame et de piment, et déguste aussitôt.", None),
        ],
    ),
    (
        "oeufs-benedicte", "Œufs Bénédicte",
        "Des œufs pochés sur muffin anglais et jambon, nappés d'une sauce hollandaise au citron : le grand classique du brunch à l'américaine.",
        "🍳", "etats_unis", "petit_dej", "moyen", 20, 15, 2, ["brunch", "week-end"],
        [
            ("muffins anglais", 2, "pièce", 120, "7257"),
            ("jambon cuit", 2, "tranche", 80, "28910"),
            ("œufs", 4, "pièce", 220, "22000"),
            ("jaunes d'œufs", 2, "pièce", 36, "22002"),
            ("beurre", 100, "g", 100, "16400"),
            ("citron", 0.5, "pièce", 20, "13009"),
            ("vinaigre blanc", 2, "càs", 30, "11018"),
            ("ciboulette (facultatif)", 4, "brins", 3, "11003"),
            ("sel", 1, "pincée", 1, None),
        ],
        [
            ("Fais fondre le beurre doucement et garde-le tiède.", 3),
            ("Au bain-marie, fouette les jaunes avec 1 càs d'eau jusqu'à ce qu'ils moussent, puis verse le beurre en filet sans cesser de fouetter ; ajoute le jus de citron et le sel.", 5),
            ("Porte une casserole d'eau vinaigrée à frémissement, crée un tourbillon et fais glisser les œufs un par un.", None),
            ("Laisse pocher 3 minutes, puis égoutte-les sur du papier absorbant.", 3),
            ("Toaste les muffins coupés en deux et réchauffe le jambon dans une poêle.", 3),
            ("Monte chaque muffin avec le jambon et un œuf, nappe de hollandaise et parsème de ciboulette.", None),
        ],
    ),
    (
        "pain-perdu", "Pain perdu",
        "Des tranches de pain rassis trempées dans un lait aux œufs puis dorées au beurre, pour ne rien jeter.",
        "🍞", "france", "petit_dej", "facile", 10, 10, 4, ["anti-gaspi", "brunch"],
        [
            ("pain rassis", 8, "tranche", 320, "7001"),
            ("lait", 30, "cl", 300, "19041"),
            ("œufs", 3, "pièce", 165, "22000"),
            ("sucre", 40, "g", 40, "31016"),
            ("cannelle en poudre", 1, "càc", 3, "11025"),
            ("beurre", 30, "g", 30, "16400"),
        ],
        [
            ("Fouette les œufs avec le lait, le sucre et la cannelle dans un plat creux.", None),
            ("Trempe les tranches de pain quelques secondes de chaque côté, sans les détremper.", None),
            ("Fais mousser un peu de beurre dans une poêle à feu moyen.", 1),
            ("Dore les tranches 2 à 3 minutes par face, en ajoutant du beurre entre chaque fournée.", 8),
            ("Sers tiède, avec des fruits frais ou un filet de sirop si tu aimes.", None),
        ],
    ),
    (
        "smoothie-bowl-fruits-rouges", "Smoothie bowl aux fruits rouges",
        "Un bol épais de banane et fruits rouges mixés, inspiré des bols d'açaí brésiliens, couvert de fruits et de granola.",
        "🫐", "amerique_sud", "petit_dej", "facile", 10, 0, 2, ["sans-cuisson", "vegan", "ete"],
        [
            ("bananes congelées", 2, "pièce", 240, "13005"),
            ("fruits rouges surgelés (framboises, myrtilles)", 250, "g", 250, "13015"),
            ("boisson à l'amande", 10, "cl", 100, "18107"),
            ("kiwi", 1, "pièce", 80, "13021"),
            ("myrtilles fraîches", 60, "g", 60, "13028"),
            ("noix de coco râpée", 2, "càs", 10, "15007"),
            ("graines de chia (facultatif)", 1, "càs", 10, "15047"),
        ],
        [
            ("Coupe les bananes en rondelles avant de les congeler, idéalement la veille.", None),
            ("Mixe les bananes, les fruits rouges et la boisson à l'amande en raclant les parois : la texture doit rester épaisse.", 2),
            ("Répartis dans deux bols bien froids.", None),
            ("Décore de rondelles de kiwi, de myrtilles, de noix de coco et de graines de chia.", None),
            ("Déguste tout de suite, à la cuillère.", None),
        ],
    ),
    # ── Pains ─────────────────────────────────────────────────────────
    (
        "focaccia", "Focaccia au romarin",
        "Le pain plat de Ligurie, moelleux dedans, croustillant dessous, généreusement arrosé d'huile d'olive.",
        "🫓", "italie", "pain", "moyen", 20, 25, 8, ["four", "vegan", "apero"],
        [
            ("farine T55", 500, "g", 500, "9436"),
            ("eau tiède", 38, "cl", 380, None),
            ("levure de boulanger déshydratée", 7, "g", 7, "11045"),
            ("huile d'olive", 8, "càs", 90, "17270"),
            ("romarin frais", 3, "brins", 6, "11068"),
            ("sel", 10, "g", 10, None),
            ("fleur de sel", 1, "càc", 4, None),
        ],
        [
            ("Délaye la levure dans l'eau tiède, puis ajoute la farine, le sel et 2 càs d'huile ; mélange jusqu'à obtenir une pâte très collante.", 5),
            ("Couvre et laisse pousser jusqu'à ce que la pâte double, en la rabattant sur elle-même deux fois.", 90),
            ("Verse 3 càs d'huile dans un grand plat, étale la pâte du bout des doigts et laisse-la gonfler encore.", 30),
            ("Préchauffe le four à 220 °C. Enfonce les doigts dans la pâte pour creuser des alvéoles.", None),
            ("Arrose du reste d'huile, parsème de romarin et de fleur de sel.", None),
            ("Enfourne jusqu'à ce que le dessus soit bien doré, puis laisse tiédir sur une grille.", 25),
        ],
    ),
    (
        "cheese-naan", "Cheese naan",
        "Des pains indiens moelleux au yaourt, fourrés de fromage fondant et cuits à la poêle.",
        "🧀", "inde", "pain", "moyen", 25, 15, 6, ["poele", "fromage"],
        [
            ("farine T55", 400, "g", 400, "9436"),
            ("yaourt nature", 1, "pot", 125, "19600"),
            ("lait tiède", 12, "cl", 120, "19041"),
            ("levure de boulanger déshydratée", 5, "g", 5, "11045"),
            ("levure chimique", 1, "càc", 4, "11046"),
            ("sucre", 1, "càc", 5, "31016"),
            ("fromage à pâte fondante (mozzarella ou cheddar)", 200, "g", 200, "19590"),
            ("beurre fondu", 30, "g", 30, "16400"),
            ("gousse d'ail", 1, "pièce", 5, "11000"),
            ("sel", 1, "càc", 5, None),
        ],
        [
            ("Mélange la farine, les deux levures, le sucre et le sel, puis ajoute le yaourt et le lait ; pétris jusqu'à obtenir une pâte souple.", 8),
            ("Couvre et laisse reposer jusqu'à ce que la pâte gonfle nettement.", 60),
            ("Divise en 6 boules, aplatis chacune, pose du fromage au centre et referme bien en pinçant les bords.", None),
            ("Abaisse délicatement chaque naan au rouleau en une galette d'un demi-centimètre.", None),
            ("Cuis dans une poêle très chaude, à sec, jusqu'à ce que des bulles dorées apparaissent de chaque côté.", 15),
            ("Badigeonne de beurre fondu mélangé à l'ail écrasé et sers bien chaud.", None),
        ],
    ),
    (
        "pao-de-queijo", "Pão de queijo",
        "Les petites boules au fromage du Brésil, croustillantes dehors et élastiques dedans, à base de fécule de manioc.",
        "🧀", "amerique_sud", "pain", "facile", 15, 25, 6, ["apero", "sans-gluten", "four"],
        [
            ("fécule de manioc (tapioca)", 250, "g", 250, "4000"),
            ("lait", 12, "cl", 120, "19041"),
            ("huile de tournesol", 6, "cl", 55, "17440"),
            ("œufs", 2, "pièce", 110, "22000"),
            ("parmesan râpé", 80, "g", 80, "12120"),
            ("gruyère râpé", 70, "g", 70, "12114"),
            ("sel", 1, "càc", 5, None),
        ],
        [
            ("Préchauffe le four à 190 °C.", None),
            ("Porte le lait, l'huile et le sel à ébullition, puis verse d'un coup sur la fécule en mélangeant vivement.", 3),
            ("Laisse tiédir quelques minutes, puis incorpore les œufs un à un jusqu'à obtenir une pâte lisse et collante.", 5),
            ("Ajoute les fromages et mélange bien.", None),
            ("Forme des boules de la taille d'une noix avec les mains huilées et dépose-les sur une plaque couverte de papier cuisson.", None),
            ("Enfourne jusqu'à ce qu'elles soient gonflées et blondes ; sers tiède.", 22),
        ],
    ),
    (
        "cornbread", "Cornbread",
        "Le pain de maïs du sud des États-Unis, doré et légèrement sucré, parfait avec un chili ou au brunch.",
        "🌽", "etats_unis", "pain", "facile", 10, 25, 8, ["four", "brunch"],
        [
            ("semoule de maïs fine (polenta)", 150, "g", 150, "9614"),
            ("farine T65", 120, "g", 120, "9435"),
            ("sucre", 40, "g", 40, "31016"),
            ("levure chimique", 1, "sachet", 11, "11046"),
            ("lait", 25, "cl", 250, "19041"),
            ("œufs", 2, "pièce", 110, "22000"),
            ("beurre fondu", 80, "g", 80, "16400"),
            ("sel", 1, "càc", 5, None),
        ],
        [
            ("Préchauffe le four à 200 °C et beurre un moule carré ou une poêle en fonte.", None),
            ("Mélange la semoule de maïs, la farine, le sucre, la levure et le sel.", None),
            ("Fouette à part le lait, les œufs et le beurre fondu.", None),
            ("Verse le liquide sur les poudres et mélange juste assez pour qu'il ne reste plus de farine sèche.", None),
            ("Verse dans le moule et enfourne jusqu'à ce qu'une lame en ressorte sèche.", 25),
            ("Laisse tiédir 10 minutes avant de couper en carrés.", None),
        ],
    ),
    # ── Apéro ─────────────────────────────────────────────────────────
    (
        "tapenade", "Tapenade",
        "La pâte provençale d'olives noires, câpres et anchois, à tartiner sur du pain grillé.",
        "🫒", "france", "kemia", "facile", 10, 0, 6, ["apero", "sans-cuisson", "express"],
        [
            ("olives noires dénoyautées", 200, "g", 200, "13131"),
            ("câpres", 2, "càs", 20, "11040"),
            ("filets d'anchois", 4, "pièce", 16, "26000"),
            ("gousse d'ail", 1, "pièce", 5, "11000"),
            ("huile d'olive", 5, "càs", 50, "17270"),
            ("citron", 0.5, "pièce", 20, "13009"),
            ("thym séché", 1, "pincée", 1, "11038"),
            ("poivre", 1, "pincée", 1, "11015"),
        ],
        [
            ("Égoutte les olives et rince rapidement les câpres.", None),
            ("Mixe les olives, les câpres, les anchois, l'ail et le thym par à-coups.", 1),
            ("Ajoute l'huile en filet et le jus de citron, et mixe jusqu'à la texture voulue, plus ou moins lisse.", 1),
            ("Poivre, goûte, puis laisse reposer au frais 30 minutes pour que les saveurs se mêlent.", None),
        ],
    ),
    (
        "baba-ghanouj", "Baba ghanouj",
        "Le caviar d'aubergine du Liban, fumé et crémeux grâce au tahin, à saucer avec du pain pita.",
        "🍆", "liban", "kemia", "facile", 15, 40, 6, ["apero", "vegan", "sans-gluten"],
        [
            ("aubergines", 2, "pièce", 600, "20300"),
            ("tahin", 3, "càs", 45, "15203"),
            ("citron", 1, "pièce", 40, "13009"),
            ("gousse d'ail", 1, "pièce", 5, "11000"),
            ("cumin en poudre", 0.5, "càc", 1, "11042"),
            ("huile d'olive", 2, "càs", 20, "17270"),
            ("persil plat", 3, "brins", 5, "11014"),
            ("graines de grenade (facultatif)", 2, "càs", 30, "13018"),
            ("sel", 1, "pincée", 1, None),
        ],
        [
            ("Pique les aubergines et fais-les griller au four à 220 °C, ou directement sur la flamme, jusqu'à ce que la peau soit noircie et la chair fondante.", 40),
            ("Laisse tiédir, puis récupère la chair à la cuillère et laisse-la s'égoutter dans une passoire.", 10),
            ("Écrase la chair à la fourchette avec le tahin, le jus de citron, l'ail râpé, le cumin et le sel.", None),
            ("Verse dans un plat creux et trace un sillon à la cuillère.", None),
            ("Arrose d'huile d'olive, parsème de persil haché et de grenade.", None),
        ],
    ),
    (
        "gougeres", "Gougères au comté",
        "Des petits choux au fromage de Bourgogne, gonflés et dorés, à servir tièdes à l'apéritif.",
        "🧀", "france", "kemia", "moyen", 20, 25, 6, ["apero", "four"],
        [
            ("eau", 25, "cl", 250, None),
            ("beurre", 90, "g", 90, "16400"),
            ("farine T45", 150, "g", 150, "9440"),
            ("œufs", 4, "pièce", 220, "22000"),
            ("comté râpé", 120, "g", 120, "12110"),
            ("noix de muscade", 1, "pincée", 1, "11048"),
            ("poivre", 1, "pincée", 1, "11015"),
            ("sel", 1, "càc", 5, None),
        ],
        [
            ("Préchauffe le four à 190 °C. Porte l'eau, le beurre et le sel à ébullition.", 3),
            ("Hors du feu, verse la farine d'un coup et remue vivement, puis dessèche la pâte sur feu doux jusqu'à ce qu'elle forme une boule.", 2),
            ("Hors du feu, incorpore les œufs un à un en battant bien entre chaque ajout ; la pâte doit être lisse et brillante.", 5),
            ("Ajoute les trois quarts du comté, la muscade et le poivre.", None),
            ("Dresse de petits tas sur une plaque couverte de papier cuisson et parsème du reste de comté.", None),
            ("Enfourne sans ouvrir la porte jusqu'à ce qu'elles soient bien gonflées et dorées.", 25),
        ],
    ),
    (
        "bruschetta-tomates", "Bruschetta aux tomates",
        "Du pain grillé frotté à l'ail, couvert de tomates mûres au basilic : l'apéro d'été à l'italienne.",
        "🍅", "italie", "kemia", "facile", 15, 5, 4, ["apero", "vegan", "ete"],
        [
            ("baguette ou pain de campagne", 8, "tranche", 200, "7001"),
            ("tomates bien mûres", 4, "pièce", 400, "20047"),
            ("gousses d'ail", 2, "pièce", 10, "11000"),
            ("basilic frais", 1, "bouquet", 15, "11033"),
            ("huile d'olive", 4, "càs", 40, "17270"),
            ("vinaigre balsamique (facultatif)", 1, "càc", 5, "11091"),
            ("sel", 1, "pincée", 1, None),
        ],
        [
            ("Coupe les tomates en petits dés et laisse-les égoutter 10 minutes avec une pincée de sel.", 10),
            ("Mélange les tomates avec le basilic ciselé, 2 càs d'huile et le balsamique.", None),
            ("Fais griller les tranches de pain au four ou à la poêle jusqu'à ce qu'elles soient croustillantes.", 5),
            ("Frotte chaque tranche encore chaude avec une gousse d'ail coupée et arrose du reste d'huile.", None),
            ("Garnis de tomates au dernier moment pour que le pain reste croquant.", None),
        ],
    ),
    (
        "gambas-al-ajillo", "Gambas al ajillo",
        "Des crevettes saisies dans une huile d'olive à l'ail et au piment, comme dans les bars à tapas espagnols.",
        "🦐", "espagne", "kemia", "facile", 10, 5, 4, ["apero", "express", "sans-gluten"],
        [
            ("crevettes crues décortiquées", 400, "g", 400, "10021"),
            ("gousses d'ail", 6, "pièce", 30, "11000"),
            ("huile d'olive", 10, "cl", 90, "17270"),
            ("piment de Cayenne", 1, "pincée", 1, "11088"),
            ("persil plat", 4, "brins", 8, "11014"),
            ("citron", 0.5, "pièce", 20, "13009"),
            ("sel", 1, "pincée", 1, None),
            ("pain pour saucer (facultatif)", 4, "tranche", 120, "7001"),
        ],
        [
            ("Sèche bien les crevettes dans du papier absorbant et sale-les légèrement.", None),
            ("Émince l'ail finement et fais-le chauffer doucement dans l'huile avec le piment, sans le laisser brunir.", 2),
            ("Monte le feu, ajoute les crevettes et fais-les cuire jusqu'à ce qu'elles soient roses, en les retournant une fois.", 3),
            ("Hors du feu, parsème de persil haché et arrose d'un trait de citron.", None),
            ("Sers dans le plat de cuisson, avec du pain pour l'huile parfumée.", None),
        ],
    ),
    # ── Boissons ──────────────────────────────────────────────────────
    (
        "lassi-mangue", "Lassi à la mangue",
        "La boisson indienne au yaourt et à la mangue, onctueuse et parfumée à la cardamome.",
        "🥭", "inde", "boisson", "facile", 5, 0, 2, ["sans-cuisson", "express", "ete"],
        [
            ("mangue bien mûre", 1, "pièce", 250, "13025"),
            ("yaourt nature", 2, "pot", 250, "19600"),
            ("lait froid", 10, "cl", 100, "19041"),
            ("sucre (facultatif)", 1, "càs", 12, "31016"),
            ("cardamome en poudre", 1, "pincée", 1, "11075"),
            ("glaçons", 4, "pièce", 80, None),
        ],
        [
            ("Pèle la mangue et coupe la chair en morceaux.", None),
            ("Mixe la mangue avec le yaourt, le lait, le sucre et la cardamome jusqu'à obtenir une boisson bien lisse.", 1),
            ("Goûte et ajuste la douceur selon la maturité du fruit.", None),
            ("Verse sur les glaçons et sers aussitôt.", None),
        ],
    ),
    (
        "jus-de-gingembre", "Jus de gingembre",
        "La boisson d'Afrique de l'Ouest au gingembre frais, citron et menthe, vive et rafraîchissante.",
        "🫚", "afrique_ouest", "boisson", "facile", 20, 0, 8, ["sans-cuisson", "vegan", "ete"],
        [
            ("gingembre frais", 200, "g", 200, "11074"),
            ("eau", 150, "cl", 1500, None),
            ("citrons", 2, "pièce", 80, "13009"),
            ("sucre", 150, "g", 150, "31016"),
            ("ananas (facultatif)", 200, "g", 200, "13002"),
            ("menthe fraîche", 6, "brins", 10, "11027"),
        ],
        [
            ("Pèle le gingembre à la cuillère et coupe-le en rondelles.", None),
            ("Mixe-le avec 50 cl d'eau et l'ananas si tu en mets, jusqu'à obtenir une purée fine.", 2),
            ("Filtre à travers une passoire fine ou un torchon propre en pressant bien.", None),
            ("Ajoute le reste d'eau, le jus des citrons et le sucre, remue jusqu'à ce qu'il soit dissous.", None),
            ("Ajoute la menthe et laisse infuser au frais au moins 2 heures avant de servir bien froid.", None),
        ],
    ),
    (
        "cafe-glace-vietnamien", "Café glacé vietnamien",
        "Un café noir très serré versé sur du lait concentré sucré et des glaçons, comme à Hô Chi Minh-Ville.",
        "☕", "vietnam", "boisson", "facile", 5, 5, 2, ["express", "ete"],
        [
            ("café fort, fraîchement préparé", 20, "cl", 200, "18004"),
            ("lait concentré sucré", 4, "càs", 60, "19027"),
            ("glaçons", 10, "pièce", 200, None),
        ],
        [
            ("Prépare un café très corsé, au filtre vietnamien ou à la cafetière italienne.", 5),
            ("Verse 2 càs de lait concentré au fond de chaque verre.", None),
            ("Ajoute le café chaud et mélange pour dissoudre le lait.", None),
            ("Remplis de glaçons, remue encore et déguste bien frais.", None),
        ],
    ),
    (
        "sangria", "Sangria",
        "Le vin rouge espagnol aux fruits de saison et à la cannelle, à préparer à l'avance pour une grande tablée.",
        "🍷", "espagne", "boisson", "facile", 15, 0, 8, ["apero", "ete", "a-l-avance"],
        [
            ("vin rouge", 75, "cl", 750, "5214"),
            ("oranges", 2, "pièce", 300, "13034"),
            ("citron", 1, "pièce", 80, "13009"),
            ("pomme", 1, "pièce", 150, "13191"),
            ("sucre", 50, "g", 50, "31016"),
            ("bâton de cannelle", 1, "pièce", 3, "11025"),
            ("eau gazeuse", 50, "cl", 500, "18046"),
        ],
        [
            ("Coupe une orange et le citron en rondelles, la pomme en dés ; presse la seconde orange.", None),
            ("Dans une grande carafe, mélange le vin, le jus d'orange, le sucre et la cannelle jusqu'à dissoudre le sucre.", None),
            ("Ajoute les fruits, couvre et laisse macérer au frais au moins 4 heures.", None),
            ("Au moment de servir, allonge avec l'eau gazeuse bien froide et sers sur des glaçons.", None),
        ],
    ),
    # ── Accompagnements ───────────────────────────────────────────────
    (
        "tostones", "Tostones",
        "Des rondelles de banane plantain verte frites deux fois et aplaties, croustillantes, comme aux Antilles.",
        "🍌", "antilles", "accompagnement", "facile", 10, 15, 4, ["vegan", "sans-gluten", "apero"],
        [
            ("bananes plantain vertes", 2, "pièce", 500, "53101"),
            ("huile de tournesol pour la friture", 30, "cl", 60, "17440"),
            ("gousse d'ail", 1, "pièce", 5, "11000"),
            ("citron vert", 1, "pièce", 40, "13067"),
            ("sel", 1, "càc", 5, None),
        ],
        [
            ("Pèle les bananes plantain en incisant la peau sur la longueur, puis coupe-les en tronçons de 3 cm.", None),
            ("Fais-les frire une première fois dans l'huile chaude jusqu'à ce qu'elles soient tendres mais pas dorées.", 5),
            ("Égoutte-les et écrase chaque tronçon avec le fond d'un verre pour former des galettes.", None),
            ("Replonge-les dans l'huile jusqu'à ce qu'elles soient dorées et croustillantes.", 5),
            ("Égoutte, sale aussitôt et sers avec une sauce à l'ail écrasé et au citron vert.", None),
        ],
    ),
    (
        "riz-pilaf-vermicelles", "Riz pilaf aux vermicelles",
        "Le pilaf turc au beurre, où de fins vermicelles dorés se mêlent à un riz aux grains bien détachés.",
        "🍚", "turquie", "accompagnement", "facile", 5, 25, 4, ["classique", "express"],
        [
            ("riz blanc long", 300, "g", 300, "9119"),
            ("vermicelles de blé", 50, "g", 50, "9810"),
            ("beurre", 40, "g", 40, "16400"),
            ("huile de tournesol", 1, "càs", 10, "17440"),
            ("bouillon de légumes", 50, "cl", 500, "25948"),
            ("sel", 1, "càc", 5, None),
        ],
        [
            ("Rince le riz à l'eau froide jusqu'à ce qu'elle soit claire, puis laisse-le tremper 20 minutes et égoutte-le.", 20),
            ("Fais fondre le beurre avec l'huile et dore les vermicelles en remuant sans cesse.", 3),
            ("Ajoute le riz et nacre-le 2 minutes pour enrober chaque grain.", 2),
            ("Verse le bouillon chaud, sale, porte à ébullition puis couvre et cuis à feu très doux.", 15),
            ("Coupe le feu, pose un torchon sous le couvercle et laisse reposer 10 minutes avant d'égrainer à la fourchette.", 10),
        ],
    ),
]
