# Starter recipes, theme "desserts": 20 desserts and sweet treats from many
# cuisines. Same tuple shape as scripts/seed-world-recipes.py.
# (slug, title, description, icon, cuisine, category, difficulty, prep, cook,
#  servings, tags, ingredients[(label, qty, unit, grams, ciqual)],
#  steps[(text, minutes|None)])

R = [
    (
        "mousse-au-chocolat", "Mousse au chocolat",
        "La mousse française la plus simple : du chocolat noir, des œufs et un peu de patience.",
        "🍫", "france", "dessert", "facile", 20, 0, 6, ["sans-cuisson", "classique"],
        [
            ("chocolat noir pâtissier", 200, "g", 200, "31074"),
            ("œufs", 6, "pièce", 330, "22000"),
            ("beurre", 20, "g", 20, "16400"),
            ("sucre", 30, "g", 30, "31016"),
            ("sel", 1, "pincée", 1, None),
        ],
        [
            ("Fais fondre le chocolat avec le beurre au bain-marie, puis laisse tiédir.", 5),
            ("Sépare les blancs des jaunes ; incorpore les jaunes un par un au chocolat.", None),
            ("Monte les blancs en neige avec le sel, ajoute le sucre en fin de course pour les serrer.", 5),
            ("Mélange un tiers des blancs au chocolat pour l'assouplir, puis ajoute le reste délicatement à la spatule.", None),
            ("Répartis en verrines et laisse prendre au frais au moins 4 heures.", None),
        ],
    ),
    (
        "tarte-aux-pommes", "Tarte aux pommes",
        "Une pâte brisée, une couche de compote et des lamelles de pommes dorées au four.",
        "🍎", "france", "dessert", "facile", 25, 40, 8, ["four", "automne"],
        [
            ("pâte brisée pur beurre", 1, "pièce", 230, "23414"),
            ("pommes golden", 5, "pièce", 750, "13086"),
            ("compote de pommes", 200, "g", 200, "13038"),
            ("beurre", 30, "g", 30, "16400"),
            ("sucre", 40, "g", 40, "31016"),
            ("cannelle (facultatif)", 1, "càc", 2, "11025"),
        ],
        [
            ("Préchauffe le four à 190 °C et fonce un moule avec la pâte, pique le fond à la fourchette.", None),
            ("Étale la compote sur la pâte.", None),
            ("Épluche les pommes, coupe-les en fines lamelles et dispose-les en rosace en les faisant se chevaucher.", None),
            ("Parsème de noisettes de beurre, de sucre et de cannelle si tu aimes.", None),
            ("Enfourne jusqu'à ce que les pommes soient caramélisées sur les bords.", 40),
        ],
    ),
    (
        "fondant-au-chocolat", "Fondant au chocolat",
        "Un gâteau dense et moelleux, à peine cuit au cœur.",
        "🍰", "france", "dessert", "facile", 15, 22, 8, ["four", "express"],
        [
            ("chocolat noir pâtissier", 200, "g", 200, "31074"),
            ("beurre", 150, "g", 150, "16400"),
            ("sucre", 120, "g", 120, "31016"),
            ("œufs", 4, "pièce", 220, "22000"),
            ("farine", 50, "g", 50, "9440"),
        ],
        [
            ("Préchauffe le four à 180 °C et beurre un moule de 22 cm.", None),
            ("Fais fondre le chocolat et le beurre ensemble à feu très doux.", 5),
            ("Fouette les œufs et le sucre jusqu'à ce que le mélange blanchisse.", 3),
            ("Ajoute le chocolat fondu, puis la farine, sans trop travailler la pâte.", None),
            ("Verse dans le moule et enfourne : le centre doit rester tremblotant.", 22),
            ("Laisse tiédir avant de démouler.", None),
        ],
    ),
    (
        "creme-brulee", "Crème brûlée",
        "Une crème vanillée onctueuse sous une fine croûte de sucre caramélisé.",
        "🍮", "france", "dessert", "moyen", 20, 50, 6, ["four", "sans-gluten"],
        [
            ("crème liquide entière", 50, "cl", 500, "19415"),
            ("lait entier", 10, "cl", 100, "19023"),
            ("jaunes d'œufs", 6, "pièce", 110, "22000"),
            ("sucre", 90, "g", 90, "31016"),
            ("gousse de vanille", 1, "pièce", 3, "11057"),
            ("sucre roux", 40, "g", 40, "31017"),
        ],
        [
            ("Préchauffe le four à 100 °C. Fais chauffer la crème et le lait avec la vanille fendue et grattée, puis laisse infuser.", 15),
            ("Mélange les jaunes et le sucre sans les faire mousser.", None),
            ("Verse la crème tiède sur les jaunes en remuant doucement, puis filtre.", None),
            ("Répartis dans des ramequins et enfourne jusqu'à ce que la crème soit prise mais encore souple.", 50),
            ("Laisse refroidir, puis mets au frais au moins 3 heures.", None),
            ("Au moment de servir, saupoudre de sucre roux et caramélise au chalumeau ou sous le gril.", 2),
        ],
    ),
    (
        "clafoutis-cerises", "Clafoutis aux cerises",
        "Des cerises noyées dans un flan épais, le dessert de saison du Limousin.",
        "🍒", "france", "dessert", "facile", 15, 40, 6, ["four", "ete"],
        [
            ("cerises", 500, "g", 500, "13008"),
            ("œufs", 3, "pièce", 165, "22000"),
            ("farine", 80, "g", 80, "9440"),
            ("sucre", 80, "g", 80, "31016"),
            ("lait entier", 30, "cl", 300, "19023"),
            ("beurre", 20, "g", 20, "16400"),
        ],
        [
            ("Préchauffe le four à 180 °C et beurre un plat à gratin.", None),
            ("Lave et équeute les cerises ; tu peux garder les noyaux, ils parfument le flan.", None),
            ("Fouette les œufs et le sucre, ajoute la farine, puis le lait petit à petit pour éviter les grumeaux.", None),
            ("Dispose les cerises dans le plat et verse la pâte par-dessus.", None),
            ("Enfourne jusqu'à ce que le clafoutis soit gonflé et doré ; sers tiède.", 40),
        ],
    ),
    (
        "tarte-citron-meringuee", "Tarte au citron meringuée",
        "Une crème au citron acidulée, une pâte sablée et une meringue dorée.",
        "🍋", "france", "dessert", "difficile", 45, 35, 8, ["four", "week-end"],
        [
            ("pâte sablée pur beurre", 1, "pièce", 250, "23444"),
            ("citrons", 4, "pièce", 200, "13009"),
            ("zeste de citron", 2, "pièce", 6, "13125"),
            ("œufs", 3, "pièce", 165, "22000"),
            ("blancs d'œufs", 3, "pièce", 100, "22000"),
            ("sucre", 250, "g", 250, "31016"),
            ("beurre", 80, "g", 80, "16400"),
            ("fécule de maïs", 20, "g", 20, "9510"),
        ],
        [
            ("Préchauffe le four à 180 °C, étale la pâte dans un moule, couvre de papier et de billes de cuisson, et fais-la cuire à blanc.", 20),
            ("Dans une casserole, mélange le jus des citrons, les zestes, les œufs, 100 g de sucre et la fécule.", None),
            ("Fais épaissir à feu doux sans cesser de fouetter, puis ajoute le beurre en morceaux hors du feu.", 6),
            ("Verse la crème sur le fond de tarte et laisse refroidir.", None),
            ("Monte les blancs en neige ferme en ajoutant le reste du sucre en pluie, jusqu'à obtenir une meringue brillante.", 8),
            ("Étale la meringue sur la tarte et dore-la quelques minutes sous le gril ou au chalumeau.", 3),
        ],
    ),
    (
        "gateau-au-yaourt", "Gâteau au yaourt",
        "Le gâteau qu'on mesure avec le pot de yaourt, moelleux et prêt en un rien de temps.",
        "🧁", "france", "dessert", "facile", 10, 35, 8, ["four", "enfants"],
        [
            ("yaourt nature", 1, "pot", 125, "19600"),
            ("sucre", 2, "pots", 200, "31016"),
            ("farine", 3, "pots", 210, "9440"),
            ("huile de tournesol", 0.5, "pot", 50, "17440"),
            ("œufs", 3, "pièce", 165, "22000"),
            ("levure chimique", 1, "sachet", 11, "11046"),
            ("zeste de citron (facultatif)", 1, "pièce", 3, "13125"),
        ],
        [
            ("Préchauffe le four à 180 °C et huile un moule à cake ou rond.", None),
            ("Verse le yaourt dans un saladier et garde le pot pour mesurer le reste.", None),
            ("Ajoute les œufs et le sucre, mélange, puis la farine et la levure.", None),
            ("Incorpore l'huile et le zeste si tu en mets, jusqu'à obtenir une pâte lisse.", None),
            ("Enfourne jusqu'à ce qu'une lame plantée au centre ressorte sèche.", 35),
        ],
    ),
    (
        "panna-cotta-framboise", "Panna cotta, coulis de framboise",
        "La crème cuite italienne à la vanille, prise à la gélatine et nappée d'un coulis de framboise.",
        "🍮", "italie", "dessert", "facile", 15, 10, 6, ["sans-gluten", "a-l-avance"],
        [
            ("crème liquide entière", 50, "cl", 500, "19415"),
            ("lait entier", 10, "cl", 100, "19023"),
            ("sucre", 80, "g", 80, "31016"),
            ("gélatine en feuilles", 3, "feuilles", 6, "11007"),
            ("gousse de vanille", 1, "pièce", 3, "11057"),
            ("framboises", 250, "g", 250, "13015"),
        ],
        [
            ("Fais ramollir la gélatine dans un bol d'eau froide.", 5),
            ("Chauffe la crème, le lait, 50 g de sucre et la vanille grattée jusqu'au frémissement.", 5),
            ("Hors du feu, ajoute la gélatine essorée et remue jusqu'à ce qu'elle soit dissoute.", None),
            ("Verse dans des verrines et laisse prendre au frais au moins 4 heures.", None),
            ("Mixe les framboises avec le reste du sucre, filtre pour ôter les pépins et nappe au moment de servir.", 5),
        ],
    ),
    (
        "cheesecake-new-yorkais", "Cheesecake new-yorkais",
        "Un gâteau au fromage frais dense et crémeux sur une base de biscuits, cuit doucement au four.",
        "🍰", "etats_unis", "dessert", "moyen", 25, 60, 10, ["four", "a-l-avance"],
        [
            ("biscuits secs type petit-beurre", 200, "g", 200, "24015"),
            ("beurre", 80, "g", 80, "16400"),
            ("fromage frais à tartiner", 600, "g", 600, "12315"),
            ("crème fraîche épaisse", 20, "cl", 200, "19410"),
            ("sucre", 150, "g", 150, "31016"),
            ("œufs", 3, "pièce", 165, "22000"),
            ("fécule de maïs", 20, "g", 20, "9510"),
            ("citron", 1, "pièce", 50, "13009"),
        ],
        [
            ("Préchauffe le four à 160 °C. Écrase les biscuits, mélange-les au beurre fondu et tasse-les au fond d'un moule à charnière.", None),
            ("Fouette le fromage frais avec le sucre et la fécule jusqu'à ce qu'il soit lisse.", None),
            ("Ajoute la crème, le jus du citron, puis les œufs un par un, sans trop battre.", None),
            ("Verse sur la base et enfourne : les bords doivent être pris et le centre encore tremblotant.", 60),
            ("Laisse refroidir dans le four entrouvert, puis une nuit au frais avant de démouler.", None),
        ],
    ),
    (
        "brownies-noix-pecan", "Brownies aux noix de pécan",
        "Des carrés au chocolat fondants à cœur, avec le croquant des noix de pécan.",
        "🟫", "etats_unis", "dessert", "facile", 15, 25, 12, ["four", "gouter"],
        [
            ("chocolat noir pâtissier", 200, "g", 200, "31074"),
            ("beurre", 150, "g", 150, "16400"),
            ("sucre roux", 180, "g", 180, "31017"),
            ("œufs", 3, "pièce", 165, "22000"),
            ("farine", 90, "g", 90, "9440"),
            ("cacao non sucré", 20, "g", 20, "18100"),
            ("noix de pécan", 100, "g", 100, "15026"),
        ],
        [
            ("Préchauffe le four à 175 °C et chemise un moule carré de papier cuisson.", None),
            ("Fais fondre le chocolat et le beurre, puis ajoute le sucre roux.", 5),
            ("Incorpore les œufs un à un, puis la farine et le cacao tamisés.", None),
            ("Ajoute les noix de pécan concassées et verse dans le moule.", None),
            ("Enfourne en surveillant : la surface doit craqueler et le centre rester humide.", 25),
            ("Laisse refroidir complètement avant de couper en carrés.", None),
        ],
    ),
    (
        "banana-bread-vegan", "Banana bread vegan",
        "Un cake moelleux aux bananes bien mûres, sans œuf ni produit laitier.",
        "🍌", "etats_unis", "dessert", "facile", 15, 55, 10, ["vegan", "four", "anti-gaspi"],
        [
            ("bananes bien mûres", 3, "pièce", 360, "13005"),
            ("farine", 250, "g", 250, "9440"),
            ("sucre roux", 120, "g", 120, "31017"),
            ("huile de colza", 8, "cl", 75, "17130"),
            ("boisson au soja", 10, "cl", 100, "18900"),
            ("levure chimique", 1, "sachet", 11, "11046"),
            ("cannelle", 1, "càc", 2, "11025"),
            ("noix (facultatif)", 60, "g", 60, "15023"),
        ],
        [
            ("Préchauffe le four à 180 °C et chemise un moule à cake.", None),
            ("Écrase les bananes à la fourchette, puis ajoute le sucre, l'huile et la boisson au soja.", None),
            ("Mélange la farine, la levure et la cannelle, puis incorpore-les sans trop travailler la pâte.", None),
            ("Ajoute les noix concassées si tu en mets et verse dans le moule.", None),
            ("Enfourne jusqu'à ce qu'une lame ressorte sèche ; couvre d'aluminium si le dessus colore trop vite.", 55),
        ],
    ),
    (
        "baklava-pistaches", "Baklava aux pistaches",
        "Des feuilles de filo beurrées, un cœur de pistaches et de noix, imbibées d'un sirop au miel.",
        "🥮", "turquie", "dessert", "difficile", 45, 45, 24, ["four", "a-l-avance"],
        [
            ("pâte filo", 1, "paquet", 400, "23445"),
            ("pistaches non salées", 200, "g", 200, "15044"),
            ("noix", 100, "g", 100, "15023"),
            ("beurre", 200, "g", 200, "16400"),
            ("sucre", 250, "g", 250, "31016"),
            ("miel", 80, "g", 80, "31008"),
            ("eau", 20, "cl", 200, None),
            ("citron", 0.5, "pièce", 25, "13009"),
            ("cannelle", 1, "càc", 2, "11025"),
        ],
        [
            ("Préchauffe le four à 170 °C. Hache grossièrement les pistaches et les noix, mélange-les à la cannelle.", None),
            ("Beurre un plat, superpose la moitié des feuilles de filo en badigeonnant chacune de beurre fondu.", None),
            ("Répartis les fruits secs, puis recouvre avec le reste des feuilles beurrées.", None),
            ("Découpe en losanges avec un couteau bien aiguisé avant la cuisson, puis enfourne jusqu'à ce que ce soit bien doré.", 45),
            ("Pendant ce temps, fais bouillir l'eau, le sucre, le miel et le jus de citron pour obtenir un sirop.", 10),
            ("Verse le sirop froid sur le baklava chaud et laisse imbiber plusieurs heures avant de servir.", None),
        ],
    ),
    (
        "churros", "Churros",
        "Les beignets espagnols croustillants, roulés dans le sucre à la cannelle.",
        "🥖", "espagne", "dessert", "moyen", 15, 15, 4, ["vegan", "friture"],
        [
            ("farine", 200, "g", 200, "9440"),
            ("eau", 25, "cl", 250, None),
            ("sel", 1, "pincée", 1, None),
            ("huile de tournesol", 1, "l", 100, "17440"),
            ("sucre", 60, "g", 60, "31016"),
            ("cannelle", 1, "càc", 2, "11025"),
        ],
        [
            ("Porte l'eau salée à ébullition, verse la farine d'un coup et mélange vivement jusqu'à obtenir une pâte lisse.", 3),
            ("Laisse tiédir, puis mets la pâte dans une poche munie d'une douille cannelée.", None),
            ("Chauffe l'huile à 180 °C dans une casserole à bords hauts.", 8),
            ("Forme des bâtonnets directement au-dessus de l'huile et coupe-les aux ciseaux ; fais-les dorer par petites quantités.", 4),
            ("Égoutte-les sur du papier absorbant et roule-les aussitôt dans le sucre mélangé à la cannelle.", None),
        ],
    ),
    (
        "pasteis-de-nata", "Pastéis de nata",
        "Les petits flans portugais sur pâte feuilletée, caramélisés au four très chaud.",
        "🥧", "portugal", "dessert", "difficile", 30, 20, 12, ["four", "week-end"],
        [
            ("pâte feuilletée pur beurre", 1, "pièce", 230, "23424"),
            ("lait entier", 25, "cl", 250, "19023"),
            ("crème liquide entière", 10, "cl", 100, "19415"),
            ("jaunes d'œufs", 5, "pièce", 90, "22000"),
            ("sucre", 120, "g", 120, "31016"),
            ("fécule de maïs", 20, "g", 20, "9510"),
            ("zeste de citron", 1, "pièce", 3, "13125"),
            ("cannelle (facultatif)", 1, "càc", 2, "11025"),
        ],
        [
            ("Préchauffe le four au maximum (250 à 280 °C). Roule la pâte en boudin serré, coupe-la en 12 tranches.", None),
            ("Place chaque tranche dans un moule à muffins et étire-la du pouce en remontant sur les bords.", None),
            ("Fais épaissir le lait, la crème, le sucre, la fécule et le zeste à feu doux en fouettant.", 6),
            ("Hors du feu, laisse tiédir, retire le zeste et incorpore les jaunes.", None),
            ("Remplis les fonds aux trois quarts et enfourne jusqu'à ce que le dessus soit tacheté de brun.", 15),
            ("Sers tiède, saupoudré de cannelle si tu aimes.", None),
        ],
    ),
    (
        "kheer-cardamome", "Kheer à la cardamome",
        "Le riz au lait indien, parfumé à la cardamome et parsemé de pistaches et d'amandes.",
        "🍚", "inde", "dessert", "facile", 5, 45, 6, ["sans-gluten", "reconfort"],
        [
            ("riz basmati", 80, "g", 80, "9100"),
            ("lait entier", 1, "l", 1000, "19023"),
            ("sucre", 90, "g", 90, "31016"),
            ("cardamome en poudre", 1, "càc", 2, "11075"),
            ("amandes effilées", 30, "g", 30, "15000"),
            ("pistaches non salées", 30, "g", 30, "15044"),
            ("raisins secs (facultatif)", 30, "g", 30, "13046"),
        ],
        [
            ("Rince le riz et laisse-le tremper 20 minutes, puis égoutte-le.", None),
            ("Porte le lait à ébullition dans une casserole à fond épais, ajoute le riz et baisse le feu.", 5),
            ("Laisse cuire à petit frémissement en remuant souvent, jusqu'à ce que le lait ait réduit et épaissi.", 35),
            ("Ajoute le sucre, la cardamome et les raisins secs, puis prolonge la cuisson.", 5),
            ("Sers tiède ou froid, parsemé d'amandes et de pistaches concassées.", None),
        ],
    ),
    (
        "mahalabia-fleur-oranger", "Mahalabia à la fleur d'oranger",
        "Une crème de lait libanaise, prise à la fécule et parfumée à la fleur d'oranger.",
        "🥛", "liban", "dessert", "facile", 10, 10, 6, ["sans-gluten", "a-l-avance"],
        [
            ("lait entier", 75, "cl", 750, "19023"),
            ("fécule de maïs", 60, "g", 60, "9510"),
            ("sucre", 80, "g", 80, "31016"),
            ("eau de fleur d'oranger", 2, "càs", 30, None),
            ("pistaches non salées", 30, "g", 30, "15044"),
        ],
        [
            ("Délaye la fécule dans un verre de lait froid.", None),
            ("Chauffe le reste du lait avec le sucre, puis verse la fécule délayée en fouettant.", 3),
            ("Laisse épaissir à feu doux sans cesser de remuer, jusqu'à la consistance d'une crème.", 7),
            ("Hors du feu, ajoute l'eau de fleur d'oranger et répartis dans des coupelles.", None),
            ("Laisse prendre au frais au moins 2 heures et parsème de pistaches hachées.", None),
        ],
    ),
    (
        "bananes-flambees-rhum", "Bananes flambées au rhum",
        "Des bananes dorées au beurre et au sucre roux, flambées au rhum ambré.",
        "🔥", "antilles", "dessert", "facile", 5, 10, 4, ["express", "sans-gluten"],
        [
            ("bananes", 4, "pièce", 480, "13005"),
            ("beurre", 30, "g", 30, "16400"),
            ("sucre roux", 40, "g", 40, "31017"),
            ("rhum ambré", 5, "cl", 50, "1004"),
            ("citron vert", 1, "pièce", 60, "13067"),
            ("gousse de vanille (facultatif)", 1, "pièce", 3, "11057"),
        ],
        [
            ("Épluche les bananes et coupe-les en deux dans la longueur.", None),
            ("Fais fondre le beurre dans une grande poêle, ajoute le sucre roux et la vanille grattée.", 2),
            ("Dépose les bananes et laisse-les dorer des deux côtés en les arrosant de caramel.", 5),
            ("Verse le rhum, fais-le chauffer quelques secondes puis flambe en éloignant le visage et hotte éteinte.", 1),
            ("Arrose d'un filet de jus de citron vert et sers aussitôt.", None),
        ],
    ),
    (
        "salade-fruits-exotiques", "Salade de fruits exotiques",
        "Mangue, ananas, papaye et fruit de la passion relevés de citron vert et de menthe.",
        "🥭", "amerique_sud", "dessert", "facile", 20, 0, 6, ["vegan", "sans-cuisson", "ete"],
        [
            ("mangue", 1, "pièce", 350, "13025"),
            ("ananas", 0.5, "pièce", 400, "13002"),
            ("papaye", 1, "pièce", 300, "13035"),
            ("kiwis", 2, "pièce", 150, "13021"),
            ("fruits de la passion", 3, "pièce", 90, "13016"),
            ("citron vert", 1, "pièce", 60, "13067"),
            ("sucre roux", 20, "g", 20, "31017"),
            ("menthe fraîche", 6, "feuilles", 3, "11027"),
        ],
        [
            ("Épluche la mangue, l'ananas, la papaye et les kiwis, puis coupe-les en dés réguliers.", None),
            ("Mélange le jus et le zeste du citron vert avec le sucre roux jusqu'à ce qu'il fonde.", None),
            ("Verse ce sirop sur les fruits et ajoute la pulpe des fruits de la passion.", None),
            ("Laisse reposer au frais 30 minutes pour que les saveurs se mêlent.", None),
            ("Parsème de menthe ciselée juste avant de servir.", None),
        ],
    ),
    (
        "daifuku-mangue", "Daifuku à la mangue",
        "Des petites bouchées japonaises de pâte de riz gluant, fourrées d'un dé de mangue.",
        "🍡", "japon", "dessert", "moyen", 30, 5, 8, ["vegan", "sans-gluten"],
        [
            ("farine de riz gluant", 150, "g", 150, "9520"),
            ("sucre", 50, "g", 50, "31016"),
            ("eau", 18, "cl", 180, None),
            ("mangue bien mûre", 1, "pièce", 300, "13025"),
            ("fécule de maïs", 40, "g", 40, "9510"),
        ],
        [
            ("Coupe la mangue en 8 gros dés et réserve-les au frais.", None),
            ("Mélange la farine de riz gluant, le sucre et l'eau jusqu'à obtenir une pâte lisse et liquide.", None),
            ("Cuis au micro-ondes par tranches d'une minute en remuant entre chaque, jusqu'à ce que la pâte devienne translucide et élastique.", 4),
            ("Verse-la sur un plan généreusement fariné de fécule et divise-la en 8 portions avec les mains poudrées.", None),
            ("Aplatis chaque portion, dépose un dé de mangue au centre et referme en pinçant ; sers dans la journée.", None),
        ],
    ),
    (
        "crumble-fruits-rouges-sans-gluten", "Crumble aux fruits rouges sans gluten",
        "Des fruits rouges juteux sous un sablé croustillant à la farine de riz et aux amandes.",
        "🫐", "autre", "dessert", "facile", 15, 30, 6, ["vegan", "sans-gluten", "four"],
        [
            ("framboises", 200, "g", 200, "13015"),
            ("myrtilles", 200, "g", 200, "13028"),
            ("mûres", 150, "g", 150, "13029"),
            ("farine de riz", 100, "g", 100, "9520"),
            ("amandes en poudre", 80, "g", 80, "15000"),
            ("sucre roux", 90, "g", 90, "31017"),
            ("margarine végétale", 90, "g", 90, "16615"),
        ],
        [
            ("Préchauffe le four à 190 °C et répartis les fruits dans un plat, surgelés ou frais.", None),
            ("Mélange la farine de riz, la poudre d'amande et le sucre roux.", None),
            ("Ajoute la margarine froide en dés et sable du bout des doigts jusqu'à obtenir de grosses miettes.", 5),
            ("Parsème les miettes sur les fruits sans tasser.", None),
            ("Enfourne jusqu'à ce que le dessus soit doré et que le jus bouillonne sur les bords.", 30),
        ],
    ),
]
