# Starter recipes, theme "poissons": fish and seafood dishes.
# Same tuple shape as scripts/seed-world-recipes.py.
R = [
    (
        "saumon-teriyaki", "Saumon teriyaki",
        "Des pavés de saumon laqués d'une sauce soja sucrée et brillante, une recette venue du Japon.",
        "🍣", "japon", "plat", "facile", 10, 15, 4, ["express"],
        [
            ("pavés de saumon", 4, "pièce", 560, "26036"),
            ("sauce soja", 6, "càs", 90, "11104"),
            ("saké", 4, "càs", 60, "1026"),
            ("sucre", 2, "càs", 25, "31016"),
            ("gingembre frais", 1, "morceau", 10, "11074"),
            ("huile de tournesol", 1, "càs", 10, "17440"),
            ("riz blanc", 280, "g", 280, "9100"),
            ("ciboulette (facultatif)", 1, "botte", 10, "11003"),
        ],
        [
            ("Lance la cuisson du riz selon le paquet.", 15),
            ("Mélange la sauce soja, le saké, le sucre et le gingembre râpé.", None),
            ("Saisis les pavés côté peau dans l'huile chaude, puis retourne-les.", 6),
            ("Verse la sauce dans la poêle et laisse-la réduire en arrosant le saumon jusqu'à ce qu'il soit bien laqué.", 4),
            ("Sers sur le riz, parsemé de ciboulette ciselée.", None),
        ],
    ),
    (
        "poke-bowl-saumon", "Poke bowl au saumon",
        "Un bol hawaïen de riz tiède, saumon mariné, avocat et mangue, frais et coloré.",
        "🥗", "etats_unis", "plat", "facile", 25, 15, 2, ["sans-cuisson", "ete"],
        [
            ("filet de saumon très frais", 250, "g", 250, "26036"),
            ("riz blanc", 150, "g", 150, "9100"),
            ("sauce soja", 3, "càs", 45, "11104"),
            ("huile de sésame", 1, "càs", 10, "17400"),
            ("avocat", 1, "pièce", 150, "13004"),
            ("mangue", 0.5, "pièce", 150, "13025"),
            ("concombre", 0.5, "pièce", 150, "20019"),
            ("graines de sésame", 1, "càs", 10, "15010"),
            ("feuille de nori (facultatif)", 1, "pièce", 3, "20987"),
        ],
        [
            ("Fais cuire le riz, puis laisse-le tiédir.", 15),
            ("Coupe le saumon en dés et fais-le mariner au frais dans la sauce soja et l'huile de sésame.", 10),
            ("Taille l'avocat, la mangue et le concombre en dés.", None),
            ("Répartis le riz dans deux bols et dispose par-dessus le saumon et les fruits en petits tas.", None),
            ("Parsème de sésame et de nori en lanières, puis arrose du reste de marinade.", None),
        ],
    ),
    (
        "paella-fruits-de-mer", "Paella aux fruits de mer",
        "Le grand plat de riz espagnol au safran, garni de crevettes, moules et calamars.",
        "🥘", "espagne", "plat", "moyen", 30, 40, 6, ["partage", "ete"],
        [
            ("riz rond", 400, "g", 400, "9100"),
            ("crevettes crues", 12, "pièce", 400, "10021"),
            ("moules", 500, "g", 500, "10014"),
            ("anneaux de calamar", 300, "g", 300, "10001"),
            ("chorizo (facultatif)", 100, "g", 100, "30315"),
            ("poivron rouge", 1, "pièce", 150, "20087"),
            ("oignon", 1, "pièce", 150, "20239"),
            ("tomates", 2, "pièce", 250, "20047"),
            ("petits pois", 150, "g", 150, "20326"),
            ("safran", 1, "dose", 0.2, "11039"),
            ("huile d'olive", 4, "càs", 50, "17270"),
            ("eau chaude", 1.2, "l", 1200, None),
        ],
        [
            ("Dans une grande poêle à paella, fais dorer les crevettes dans l'huile, puis réserve-les.", 4),
            ("Fais revenir l'oignon, le poivron, le chorizo et les calamars, puis ajoute les tomates râpées.", 10),
            ("Verse le riz, remue pour bien l'enrober, puis ajoute l'eau chaude, le safran et du sel.", None),
            ("Laisse cuire sans remuer à feu moyen.", 12),
            ("Enfonce les moules et les petits pois dans le riz, puis dépose les crevettes.", None),
            ("Poursuis la cuisson jusqu'à ce que le riz ait bu le liquide, puis laisse reposer sous un torchon.", 12),
        ],
    ),
    (
        "crevettes-a-l-ail", "Crevettes à l'ail",
        "Des crevettes grésillantes dans l'huile d'olive à l'ail et au piment, comme dans les bars à tapas espagnols.",
        "🍤", "espagne", "entree", "facile", 10, 6, 4, ["express", "apero"],
        [
            ("crevettes crues décortiquées", 500, "g", 500, "10021"),
            ("gousses d'ail", 6, "pièce", 30, "11000"),
            ("huile d'olive", 10, "cl", 90, "17270"),
            ("piment de Cayenne", 1, "pincée", 1, "11088"),
            ("persil plat", 0.5, "bouquet", 10, "11014"),
            ("pain de campagne (facultatif)", 4, "tranche", 160, "7261"),
        ],
        [
            ("Éponge les crevettes et émince finement l'ail.", None),
            ("Fais chauffer doucement l'huile avec l'ail et le piment dans une petite cocotte en fonte, sans laisser brunir l'ail.", 2),
            ("Monte le feu, ajoute les crevettes et sale.", None),
            ("Retourne-les dès qu'elles rosissent ; elles cuisent très vite.", 3),
            ("Parsème de persil et sers bien chaud, avec du pain pour saucer l'huile.", None),
        ],
    ),
    (
        "brandade-de-morue", "Brandade de morue",
        "Une purée onctueuse de morue, pommes de terre, lait et huile d'olive, gratinée au four, spécialité du sud de la France.",
        "🐟", "france", "plat", "moyen", 20, 45, 6, ["four", "hiver"],
        [
            ("morue salée", 600, "g", 600, "26098"),
            ("pommes de terre", 800, "g", 800, "4008"),
            ("lait", 30, "cl", 300, "19041"),
            ("huile d'olive", 10, "cl", 90, "17270"),
            ("gousses d'ail", 3, "pièce", 15, "11000"),
            ("feuille de laurier", 1, "pièce", 1, "11053"),
            ("poivre", 1, "pincée", 1, "11015"),
        ],
        [
            ("La veille, fais dessaler la morue dans l'eau froide en changeant l'eau quatre ou cinq fois.", None),
            ("Poche la morue dans le lait frémissant avec le laurier, puis effeuille-la en retirant peau et arêtes.", 10),
            ("Fais cuire les pommes de terre à l'eau et écrase-les.", 20),
            ("Mélange la morue, les pommes de terre et l'ail écrasé en versant peu à peu l'huile et un peu du lait de cuisson, jusqu'à obtenir une purée souple.", None),
            ("Poivre, étale dans un plat et fais gratiner au four à 210 °C.", 15),
        ],
    ),
    (
        "fish-and-chips", "Fish and chips",
        "Le classique britannique : poisson blanc en pâte à la bière croustillante et frites épaisses.",
        "🍟", "autre", "plat", "moyen", 25, 30, 4, ["friture", "classique"],
        [
            ("filets de cabillaud", 4, "pièce", 600, "26043"),
            ("farine", 200, "g", 200, "9435"),
            ("bière blonde bien froide", 25, "cl", 250, "5009"),
            ("pommes de terre", 1, "kg", 1000, "4008"),
            ("huile de tournesol pour friture", 1, "l", 150, "17440"),
            ("citron", 1, "pièce", 100, "13009"),
            ("petits pois (facultatif)", 300, "g", 300, "20326"),
        ],
        [
            ("Coupe les pommes de terre en grosses frites, rince-les et sèche-les bien.", None),
            ("Fais-les frire une première fois à 160 °C jusqu'à ce qu'elles soient tendres, puis égoutte-les.", 8),
            ("Fouette la farine avec la bière froide et une pincée de sel pour obtenir une pâte nappante.", None),
            ("Sèche le poisson, farine-le légèrement, trempe-le dans la pâte et fais-le frire à 180 °C jusqu'à ce qu'il soit doré.", 6),
            ("Replonge les frites à 180 °C pour les rendre croustillantes.", 4),
            ("Égoutte sur du papier absorbant, sale et sers avec le citron en quartiers et les petits pois écrasés.", None),
        ],
    ),
    (
        "curry-poisson-coco", "Curry de poisson au lait de coco",
        "Un curry doux du sud de l'Inde où le poisson blanc mijote dans une sauce coco, tomate et curcuma.",
        "🍛", "inde", "plat", "facile", 15, 25, 4, ["reconfort"],
        [
            ("filets de lieu noir", 600, "g", 600, "26134"),
            ("lait de coco", 40, "cl", 400, "18041"),
            ("oignon", 1, "pièce", 150, "20239"),
            ("tomates", 2, "pièce", 250, "20047"),
            ("gousses d'ail", 2, "pièce", 10, "11000"),
            ("gingembre frais", 1, "morceau", 15, "11074"),
            ("curry en poudre", 2, "càc", 6, "11005"),
            ("curcuma", 1, "càc", 3, "11089"),
            ("huile de tournesol", 2, "càs", 20, "17440"),
            ("coriandre fraîche (facultatif)", 0.5, "bouquet", 10, "11094"),
            ("riz blanc", 280, "g", 280, "9100"),
        ],
        [
            ("Fais revenir l'oignon émincé dans l'huile jusqu'à ce qu'il soit doré.", 8),
            ("Ajoute l'ail, le gingembre râpé, le curry et le curcuma, remue une minute.", 1),
            ("Verse les tomates en dés et le lait de coco, sale et laisse épaissir.", 8),
            ("Dépose le poisson en gros morceaux dans la sauce, couvre et laisse cuire à petit feu sans trop remuer.", 8),
            ("Parsème de coriandre et sers avec le riz.", None),
        ],
    ),
    (
        "papillote-cabillaud", "Papillote de cabillaud",
        "Du cabillaud cuit à l'étouffée avec courgette, tomates cerises et citron, tout le parfum reste dans la papillote.",
        "🐟", "france", "plat", "facile", 15, 18, 4, ["four", "express"],
        [
            ("dos de cabillaud", 4, "pièce", 600, "26043"),
            ("courgette", 1, "pièce", 250, "20020"),
            ("tomates cerises", 16, "pièce", 200, "20172"),
            ("citron", 1, "pièce", 100, "13009"),
            ("thym frais", 4, "brins", 4, "11070"),
            ("huile d'olive", 3, "càs", 35, "17270"),
            ("poivre", 1, "pincée", 1, "11015"),
        ],
        [
            ("Préchauffe le four à 200 °C et découpe quatre grandes feuilles de papier cuisson.", None),
            ("Taille la courgette en fines rondelles et coupe les tomates cerises en deux.", None),
            ("Dispose les légumes au centre de chaque feuille, puis le poisson, une rondelle de citron et un brin de thym.", None),
            ("Arrose d'huile, sale, poivre et referme bien les papillotes.", None),
            ("Enfourne et ouvre les papillotes à table.", 18),
        ],
    ),
    (
        "sardines-grillees", "Sardines grillées",
        "Des sardines entières grillées au gros sel, servies avec une salade de poivrons, comme au Portugal.",
        "🐟", "portugal", "plat", "facile", 15, 10, 4, ["barbecue", "ete"],
        [
            ("sardines fraîches", 16, "pièce", 1000, "26065"),
            ("gros sel", 1, "càs", 15, None),
            ("poivrons rouges", 2, "pièce", 300, "20087"),
            ("oignon rouge", 1, "pièce", 120, "20238"),
            ("huile d'olive", 4, "càs", 45, "17270"),
            ("citron", 1, "pièce", 100, "13009"),
            ("pain de campagne", 4, "tranche", 160, "7261"),
        ],
        [
            ("Rince les sardines sans les vider et sèche-les ; parsème-les de gros sel.", None),
            ("Fais griller les poivrons entiers jusqu'à ce que la peau noircisse, puis pèle-les et coupe-les en lanières.", 10),
            ("Mélange les poivrons avec l'oignon rouge émincé, un filet d'huile et du sel.", None),
            ("Fais griller les sardines sur un barbecue ou une plancha très chaude.", 3),
            ("Retourne-les délicatement et poursuis la cuisson.", 3),
            ("Sers avec la salade de poivrons, le citron et le pain.", None),
        ],
    ),
    (
        "bouillabaisse-simplifiee", "Bouillabaisse simplifiée",
        "Une soupe de poissons marseillaise au safran et au fenouil, en version facile pour la maison.",
        "🍲", "france", "plat", "moyen", 30, 40, 6, ["partage"],
        [
            ("filets de rouget", 400, "g", 400, "26085"),
            ("lotte", 400, "g", 400, "26018"),
            ("merlu", 400, "g", 400, "26044"),
            ("pommes de terre", 500, "g", 500, "4008"),
            ("fenouil", 1, "pièce", 250, "20028"),
            ("oignon", 1, "pièce", 150, "20239"),
            ("tomates", 4, "pièce", 500, "20047"),
            ("gousses d'ail", 3, "pièce", 15, "11000"),
            ("safran", 1, "dose", 0.2, "11039"),
            ("pastis (facultatif)", 2, "càs", 30, "1000"),
            ("huile d'olive", 5, "càs", 60, "17270"),
            ("eau", 1.5, "l", 1500, None),
            ("baguette pour les croûtons", 0.5, "pièce", 125, "7001"),
        ],
        [
            ("Fais revenir l'oignon, le fenouil émincé et l'ail dans l'huile.", 8),
            ("Ajoute les tomates en morceaux, le safran, le pastis et l'eau, sale et poivre.", None),
            ("Ajoute les pommes de terre en rondelles épaisses et laisse bouillir franchement.", 20),
            ("Plonge d'abord la lotte, puis le merlu et enfin le rouget, en les laissant juste cuire.", 8),
            ("Fais griller les tranches de baguette.", 4),
            ("Sers le bouillon sur les croûtons, puis le poisson et les pommes de terre à part.", None),
        ],
    ),
    (
        "risotto-crevettes", "Risotto aux crevettes",
        "Un risotto italien crémeux au vin blanc et au citron, garni de crevettes juste saisies.",
        "🍤", "italie", "plat", "moyen", 15, 25, 4, ["reconfort"],
        [
            ("riz rond pour risotto", 320, "g", 320, "9100"),
            ("crevettes crues décortiquées", 400, "g", 400, "10021"),
            ("échalotes", 2, "pièce", 60, "20097"),
            ("vin blanc sec", 12, "cl", 120, "5215"),
            ("bouillon de légumes chaud", 1, "l", 1000, "25948"),
            ("beurre", 40, "g", 40, "16400"),
            ("huile d'olive", 2, "càs", 20, "17270"),
            ("citron", 1, "pièce", 100, "13009"),
            ("persil plat", 0.5, "bouquet", 10, "11014"),
        ],
        [
            ("Saisis les crevettes dans l'huile, sale-les et réserve-les.", 3),
            ("Dans la même casserole, fais fondre les échalotes ciselées dans la moitié du beurre, puis ajoute le riz et remue jusqu'à ce qu'il devienne nacré.", 3),
            ("Verse le vin blanc et laisse-le s'évaporer.", 2),
            ("Ajoute le bouillon louche par louche en remuant, en attendant chaque fois qu'il soit absorbé.", 18),
            ("Hors du feu, incorpore le reste du beurre, le zeste et un peu de jus de citron, puis les crevettes et le persil.", None),
        ],
    ),
    (
        "tacos-de-poisson", "Tacos de poisson",
        "Des tortillas de maïs garnies de poisson épicé, chou croquant et crème au citron vert, à la mexicaine.",
        "🌮", "mexique", "plat", "facile", 20, 10, 4, ["express", "street-food"],
        [
            ("filets de merlu", 500, "g", 500, "26044"),
            ("tortillas de maïs", 8, "pièce", 240, "7813"),
            ("chou rouge", 0.25, "pièce", 200, "20014"),
            ("citrons verts", 2, "pièce", 120, "13067"),
            ("yaourt nature", 1, "pot", 125, "19600"),
            ("paprika", 1, "càc", 3, "11049"),
            ("cumin", 1, "càc", 3, "11042"),
            ("huile de tournesol", 2, "càs", 20, "17440"),
            ("avocat", 1, "pièce", 150, "13004"),
            ("coriandre fraîche", 0.5, "bouquet", 10, "11094"),
        ],
        [
            ("Émince finement le chou et mélange-le avec le jus d'un citron vert et du sel.", None),
            ("Mélange le yaourt avec le zeste et le jus du second citron vert.", None),
            ("Frotte le poisson avec le paprika, le cumin et le sel, puis poêle-le dans l'huile.", 6),
            ("Réchauffe les tortillas à sec dans une poêle.", 2),
            ("Garnis chaque tortilla de poisson émietté, de chou, d'avocat en tranches, de crème au citron vert et de coriandre.", None),
        ],
    ),
    (
        "thon-mi-cuit-sesame", "Thon mi-cuit au sésame",
        "Un pavé de thon en croûte de sésame, saisi à l'extérieur et fondant au cœur, à la japonaise.",
        "🐟", "japon", "plat", "moyen", 15, 8, 4, ["express"],
        [
            ("pavés de thon rouge", 4, "pièce", 600, "26069"),
            ("graines de sésame", 60, "g", 60, "15010"),
            ("sauce soja", 4, "càs", 60, "11104"),
            ("huile de sésame", 1, "càs", 10, "17400"),
            ("gingembre frais", 1, "morceau", 10, "11074"),
            ("citron vert", 1, "pièce", 60, "13067"),
            ("pak-choï", 4, "pièce", 400, "20167"),
            ("huile de tournesol", 1, "càs", 10, "17440"),
        ],
        [
            ("Mélange la sauce soja, l'huile de sésame, le gingembre râpé et le jus de citron vert.", None),
            ("Badigeonne les pavés d'un peu de cette sauce, puis roule-les dans le sésame.", None),
            ("Saisis-les dans une poêle très chaude avec l'huile, une minute par face, le cœur doit rester rosé.", 4),
            ("Dans la même poêle, fais sauter les pak-choïs coupés en deux.", 4),
            ("Tranche le thon et sers-le sur les pak-choïs, nappé du reste de sauce.", None),
        ],
    ),
    (
        "calamars-a-la-romaine", "Calamars à la romaine",
        "Des anneaux de calamar en beignets dorés et croustillants, à picorer avec un filet de citron.",
        "🦑", "espagne", "entree", "facile", 15, 10, 4, ["friture", "apero"],
        [
            ("anneaux de calamar", 500, "g", 500, "10001"),
            ("farine", 150, "g", 150, "9435"),
            ("œuf", 1, "pièce", 55, "22000"),
            ("eau pétillante bien froide", 15, "cl", 150, None),
            ("huile de tournesol pour friture", 1, "l", 80, "17440"),
            ("citron", 1, "pièce", 100, "13009"),
            ("sel", 1, "pincée", 1, None),
        ],
        [
            ("Rince les anneaux de calamar et sèche-les soigneusement dans un torchon.", None),
            ("Fouette la farine, l'œuf, l'eau pétillante et le sel pour obtenir une pâte lisse.", None),
            ("Fais chauffer l'huile à 180 °C.", 8),
            ("Trempe les anneaux dans la pâte et fais-les frire par petites quantités jusqu'à ce qu'ils soient dorés.", 2),
            ("Égoutte-les sur du papier absorbant et sers aussitôt avec le citron en quartiers.", None),
        ],
    ),
    (
        "moqueca-bresilienne", "Moqueca brésilienne",
        "Un ragoût de poisson et crevettes du Brésil, mijoté dans le lait de coco avec poivrons et tomates.",
        "🍲", "amerique_sud", "plat", "facile", 20, 25, 4, ["reconfort"],
        [
            ("filets de mérou ou poisson blanc ferme", 500, "g", 500, "26178"),
            ("crevettes crues décortiquées", 250, "g", 250, "10021"),
            ("lait de coco", 40, "cl", 400, "18041"),
            ("poivron rouge", 1, "pièce", 150, "20087"),
            ("poivron jaune", 1, "pièce", 150, "20168"),
            ("tomates", 3, "pièce", 350, "20047"),
            ("oignon", 1, "pièce", 150, "20239"),
            ("gousses d'ail", 2, "pièce", 10, "11000"),
            ("citron vert", 1, "pièce", 60, "13067"),
            ("huile de palme", 2, "càs", 20, "16129"),
            ("coriandre fraîche", 0.5, "bouquet", 10, "11094"),
            ("riz blanc", 280, "g", 280, "9100"),
        ],
        [
            ("Fais mariner le poisson en gros morceaux et les crevettes avec l'ail écrasé, le jus du citron vert et du sel.", 10),
            ("Dans une cocotte, superpose l'oignon, les poivrons et les tomates en rondelles, puis le poisson.", None),
            ("Verse le lait de coco et l'huile de palme, couvre et laisse mijoter à feu doux.", 12),
            ("Ajoute les crevettes et poursuis la cuisson jusqu'à ce qu'elles rosissent.", 4),
            ("Parsème de coriandre et sers avec du riz blanc.", None),
        ],
    ),
    (
        "lotte-a-l-armoricaine", "Lotte à l'armoricaine",
        "Des médaillons de lotte dans une sauce tomate au vin blanc et au cognac, un grand classique breton.",
        "🍷", "france", "plat", "difficile", 25, 35, 4, ["recevoir"],
        [
            ("queue de lotte en médaillons", 800, "g", 800, "26018"),
            ("échalotes", 3, "pièce", 90, "20097"),
            ("gousses d'ail", 2, "pièce", 10, "11000"),
            ("tomates", 4, "pièce", 500, "20047"),
            ("concentré de tomate", 1, "càs", 20, "20068"),
            ("vin blanc sec", 20, "cl", 200, "5215"),
            ("cognac", 4, "cl", 40, "1023"),
            ("beurre", 40, "g", 40, "16400"),
            ("huile d'olive", 2, "càs", 20, "17270"),
            ("piment de Cayenne", 1, "pincée", 1, "11088"),
            ("persil plat", 0.5, "bouquet", 10, "11014"),
        ],
        [
            ("Sèche les médaillons de lotte, sale-les et fais-les dorer dans l'huile et la moitié du beurre, puis réserve-les.", 5),
            ("Verse le cognac dans la cocotte chaude et gratte les sucs.", 1),
            ("Ajoute les échalotes et l'ail hachés, fais-les fondre, puis les tomates pelées en dés, le concentré, le vin blanc et le piment.", 5),
            ("Laisse réduire la sauce à découvert jusqu'à ce qu'elle nappe la cuillère.", 15),
            ("Remets la lotte dans la sauce et laisse-la cuire à couvert à feu doux.", 8),
            ("Incorpore le reste du beurre en morceaux et parsème de persil avant de servir.", None),
        ],
    ),
    (
        "saint-jacques-poelees", "Noix de Saint-Jacques poêlées",
        "Des noix de Saint-Jacques dorées au beurre sur une fondue de poireaux à la crème.",
        "🐚", "france", "entree", "moyen", 15, 20, 4, ["recevoir", "hiver"],
        [
            ("noix de Saint-Jacques", 12, "pièce", 360, "10045"),
            ("poireaux", 3, "pièce", 450, "20039"),
            ("crème fraîche épaisse", 15, "cl", 150, "19410"),
            ("beurre", 40, "g", 40, "16400"),
            ("citron", 0.5, "pièce", 50, "13009"),
            ("poivre", 1, "pincée", 1, "11015"),
        ],
        [
            ("Émince finement le blanc et le vert tendre des poireaux, puis rince-les.", None),
            ("Fais-les fondre à couvert dans la moitié du beurre avec une pincée de sel.", 12),
            ("Ajoute la crème et laisse épaissir doucement.", 4),
            ("Sèche bien les noix de Saint-Jacques, puis saisis-les dans le reste du beurre très chaud, sans les bouger.", 2),
            ("Retourne-les, poursuis une minute, puis sers-les sur la fondue avec un trait de citron et du poivre.", 1),
        ],
    ),
    (
        "gravlax-saumon", "Gravlax de saumon",
        "Du saumon mariné au sel, au sucre et à l'aneth à la mode scandinave, servi avec une sauce moutarde au miel.",
        "🐟", "autre", "entree", "facile", 20, 0, 8, ["sans-cuisson", "recevoir"],
        [
            ("filet de saumon avec peau, très frais", 800, "g", 800, "26036"),
            ("gros sel", 80, "g", 80, None),
            ("sucre", 80, "g", 80, "31016"),
            ("aneth frais", 1, "bouquet", 30, "11093"),
            ("poivre concassé", 1, "càc", 3, "11015"),
            ("moutarde", 3, "càs", 45, "11013"),
            ("miel", 2, "càs", 40, "31008"),
            ("huile de colza", 3, "càs", 30, "17130"),
        ],
        [
            ("Retire les arêtes du saumon avec une pince.", None),
            ("Mélange le sel, le sucre, le poivre et la moitié de l'aneth haché.", None),
            ("Couvre la chair du saumon de ce mélange, filme-le serré et laisse-le au frais 48 heures en le retournant deux fois.", None),
            ("Rince le saumon, sèche-le et roule-le dans le reste de l'aneth.", None),
            ("Fouette la moutarde, le miel et l'huile, puis sers le saumon en tranches fines avec cette sauce.", None),
        ],
    ),
    (
        "gratin-de-poisson", "Gratin de poisson",
        "Du poisson blanc et des épinards sous une béchamel dorée à l'emmental, un plat familial tout simple.",
        "🧀", "france", "plat", "facile", 20, 30, 4, ["four", "famille"],
        [
            ("filets de cabillaud", 600, "g", 600, "26043"),
            ("jeunes pousses d'épinard", 300, "g", 300, "20270"),
            ("beurre", 40, "g", 40, "16400"),
            ("farine", 40, "g", 40, "9435"),
            ("lait", 50, "cl", 500, "19041"),
            ("emmental râpé", 80, "g", 80, "12118"),
            ("noix de muscade", 1, "pincée", 1, None),
            ("poivre", 1, "pincée", 1, "11015"),
        ],
        [
            ("Préchauffe le four à 200 °C et fais tomber les épinards quelques minutes dans une poêle sèche.", 3),
            ("Fais fondre le beurre, ajoute la farine, puis verse le lait en fouettant jusqu'à ce que la béchamel épaississe.", 8),
            ("Assaisonne de sel, poivre et muscade.", None),
            ("Étale les épinards dans un plat, pose le poisson en morceaux, nappe de béchamel et parsème d'emmental.", None),
            ("Enfourne jusqu'à ce que le dessus soit bien doré.", 20),
        ],
    ),
    (
        "spaghetti-palourdes", "Spaghetti aux palourdes",
        "Les spaghetti alle vongole napolitains : palourdes, ail, vin blanc et persil, rien de plus.",
        "🍝", "italie", "plat", "facile", 20, 15, 4, ["bord-de-mer"],
        [
            ("spaghetti", 400, "g", 400, "9810"),
            ("palourdes", 1, "kg", 1000, "10017"),
            ("gousses d'ail", 3, "pièce", 15, "11000"),
            ("vin blanc sec", 10, "cl", 100, "5215"),
            ("huile d'olive", 5, "càs", 60, "17270"),
            ("piment de Cayenne", 1, "pincée", 1, "11088"),
            ("persil plat", 1, "bouquet", 20, "11014"),
        ],
        [
            ("Fais tremper les palourdes dans de l'eau salée pour qu'elles rejettent leur sable, puis rince-les.", None),
            ("Mets les spaghetti à cuire dans une grande casserole d'eau salée.", 10),
            ("Pendant ce temps, fais dorer doucement l'ail émincé et le piment dans l'huile.", 2),
            ("Ajoute les palourdes et le vin blanc, couvre et secoue la poêle jusqu'à ce qu'elles s'ouvrent.", 4),
            ("Égoutte les pâtes un peu fermes, termine leur cuisson dans la poêle avec les palourdes et leur jus, puis parsème de persil.", 2),
        ],
    ),
]
