# Starter recipes, theme "sauces": 20 sauces and condiments from many
# cuisines. Original texts; ingredients pinned to Ciqual foods by external_id.

# (slug, title, description, icon, cuisine, category, difficulty, prep, cook,
#  servings, tags, ingredients[(label, qty, unit, grams, ciqual)],
#  steps[(text, minutes|None)])
R = [
    (
        "pesto-alla-genovese", "Pesto alla genovese",
        "Le pesto de Gênes : basilic frais, pignons, parmesan et huile d'olive, pilés minute.",
        "🌿", "italie", "sauce", "facile", 15, 3, 4, ["sans-cuisson", "ete"],
        [
            ("basilic frais", 60, "g", 60, "11033"),
            ("pignons de pin", 30, "g", 30, "15025"),
            ("parmesan râpé", 50, "g", 50, "12120"),
            ("gousse d'ail", 1, "pièce", 5, "11000"),
            ("huile d'olive", 10, "cl", 90, "17270"),
            ("gros sel", 1, "pincée", 1, None),
        ],
        [
            ("Fais dorer les pignons à sec dans une poêle, en remuant, puis laisse-les refroidir.", 3),
            ("Effeuille le basilic, rince les feuilles et sèche-les bien dans un torchon.", None),
            ("Pile l'ail avec le gros sel au mortier, ajoute les pignons et écrase-les.", None),
            ("Ajoute le basilic par petites poignées en tournant le pilon plutôt qu'en frappant.", None),
            ("Incorpore le parmesan, puis verse l'huile en filet jusqu'à obtenir une sauce souple.", None),
        ],
    ),
    (
        "sauce-vinaigrette-moutarde", "Vinaigrette à la moutarde",
        "La vinaigrette française bien émulsionnée, qui nappe la salade sans la noyer.",
        "🥗", "france", "sauce", "facile", 5, 0, 6, ["express", "sans-cuisson", "vegan"],
        [
            ("moutarde de Dijon", 1, "càs", 15, "11013"),
            ("vinaigre de vin rouge", 2, "càs", 30, "11220"),
            ("huile de tournesol", 4, "càs", 48, "17440"),
            ("huile d'olive", 2, "càs", 24, "17270"),
            ("échalote", 1, "pièce", 30, "20097"),
            ("sel", 1, "pincée", 1, None),
            ("poivre", 1, "pincée", 1, "11015"),
        ],
        [
            ("Cisèle l'échalote très finement.", None),
            ("Dans un bol, dissous le sel dans le vinaigre, puis ajoute la moutarde.", None),
            ("Verse les huiles en filet en fouettant pour que la sauce épaississe.", None),
            ("Ajoute l'échalote et le poivre, goûte et rectifie avant de servir.", None),
        ],
    ),
    (
        "sauce-mayonnaise-maison", "Mayonnaise maison",
        "Une mayonnaise ferme et brillante, montée au fouet avec un seul jaune d'œuf.",
        "🥚", "france", "sauce", "moyen", 10, 0, 6, ["sans-cuisson", "classique"],
        [
            ("jaune d'œuf", 1, "pièce", 20, "22002"),
            ("moutarde", 1, "càc", 5, "11013"),
            ("huile de tournesol", 25, "cl", 230, "17440"),
            ("vinaigre", 1, "càc", 5, "11018"),
            ("sel", 1, "pincée", 1, None),
            ("poivre", 1, "pincée", 1, "11015"),
        ],
        [
            ("Sors l'œuf et la moutarde à l'avance : tout doit être à la même température.", None),
            ("Fouette le jaune avec la moutarde, le sel et le poivre dans un bol calé sur un torchon.", None),
            ("Verse l'huile goutte à goutte en fouettant sans arrêt, jusqu'à ce que la sauce prenne.", 5),
            ("Continue en mince filet jusqu'à la texture voulue.", 3),
            ("Termine avec le vinaigre et garde au frais, bien couverte, deux jours au plus.", None),
        ],
    ),
    (
        "sauce-bechamel", "Sauce béchamel",
        "La sauce blanche de base, douce et nappante, parfumée à la muscade.",
        "🥛", "france", "sauce", "facile", 5, 12, 6, ["classique", "gratin"],
        [
            ("beurre", 50, "g", 50, "16400"),
            ("farine de blé", 50, "g", 50, "9435"),
            ("lait", 75, "cl", 770, "19041"),
            ("noix de muscade", 1, "pincée", 1, "11048"),
            ("sel", 1, "pincée", 1, None),
            ("poivre", 1, "pincée", 1, "11015"),
        ],
        [
            ("Fais fondre le beurre dans une casserole à feu moyen.", 2),
            ("Ajoute la farine d'un coup et remue sans laisser colorer.", 2),
            ("Hors du feu, verse le lait froid petit à petit en fouettant.", None),
            ("Remets sur le feu et fouette jusqu'à ce que la sauce épaississe et nappe la cuillère.", 8),
            ("Assaisonne de sel, poivre et muscade.", None),
        ],
    ),
    (
        "sauce-tomate-maison", "Sauce tomate maison",
        "Une sauce tomate à l'italienne, mijotée doucement avec ail et basilic.",
        "🍅", "italie", "sauce", "facile", 10, 30, 6, ["batch-cooking", "vegan"],
        [
            ("pulpe de tomates", 800, "g", 800, "20169"),
            ("oignon", 1, "pièce", 120, "20239"),
            ("gousses d'ail", 2, "pièce", 10, "11000"),
            ("huile d'olive", 3, "càs", 36, "17270"),
            ("sucre", 1, "pincée", 2, "31016"),
            ("basilic frais", 1, "bouquet", 15, "11033"),
            ("sel", 1, "pincée", 1, None),
        ],
        [
            ("Émince l'oignon et fais-le fondre dans l'huile sans le colorer.", 6),
            ("Ajoute l'ail écrasé et remue une minute.", 1),
            ("Verse la pulpe de tomates, le sucre et le sel.", None),
            ("Laisse mijoter à couvert entrouvert en remuant de temps en temps.", 25),
            ("Ajoute le basilic ciselé hors du feu ; mixe si tu la veux lisse.", None),
        ],
    ),
    (
        "sauce-tzatziki", "Tzatziki",
        "La sauce grecque au yaourt, concombre, ail et aneth, fraîche comme tout.",
        "🥒", "grece", "sauce", "facile", 15, 0, 6, ["sans-cuisson", "ete", "apero"],
        [
            ("yaourt à la grecque", 400, "g", 400, "19550"),
            ("concombre", 1, "pièce", 300, "20019"),
            ("gousse d'ail", 1, "pièce", 5, "11000"),
            ("aneth frais", 1, "bouquet", 10, "11093"),
            ("huile d'olive", 1, "càs", 12, "17270"),
            ("jus de citron", 1, "càs", 15, "13009"),
            ("sel", 1, "pincée", 1, None),
        ],
        [
            ("Râpe le concombre, sale-le et laisse-le dégorger dans une passoire.", 10),
            ("Presse-le fort entre tes mains pour en retirer le maximum d'eau.", None),
            ("Mélange le yaourt avec l'ail râpé, le citron et l'aneth ciselé.", None),
            ("Incorpore le concombre, arrose d'huile d'olive et garde au frais avant de servir.", None),
        ],
    ),
    (
        "sauce-raita-concombre", "Raïta au concombre",
        "La sauce indienne au yaourt, concombre et cumin grillé, pour adoucir les plats épicés.",
        "🥣", "inde", "sauce", "facile", 10, 2, 4, ["sans-cuisson", "express"],
        [
            ("yaourt nature", 300, "g", 300, "19593"),
            ("concombre", 0.5, "pièce", 150, "20019"),
            ("graines de cumin", 1, "càc", 3, "11042"),
            ("menthe fraîche", 10, "feuilles", 5, "11027"),
            ("coriandre fraîche (facultatif)", 1, "poignée", 5, "11094"),
            ("sel", 1, "pincée", 1, None),
        ],
        [
            ("Fais griller le cumin à sec jusqu'à ce qu'il embaume, puis écrase-le.", 2),
            ("Râpe le concombre et presse-le pour enlever l'eau.", None),
            ("Fouette le yaourt avec le sel pour le rendre lisse.", None),
            ("Ajoute le concombre, la menthe ciselée et la moitié du cumin.", None),
            ("Saupoudre du reste de cumin et de coriandre au moment de servir.", None),
        ],
    ),
    (
        "sauce-satay-arachide", "Sauce satay à l'arachide",
        "Une sauce onctueuse à la cacahuète et au lait de coco, venue d'Indonésie, pour brochettes et légumes.",
        "🥜", "autre", "sauce", "facile", 10, 8, 6, ["vegan", "express"],
        [
            ("beurre de cacahuète", 120, "g", 120, "15202"),
            ("lait de coco", 20, "cl", 200, "18041"),
            ("sauce soja", 2, "càs", 30, "11104"),
            ("sucre roux", 1, "càs", 12, "31017"),
            ("citron vert", 1, "pièce", 30, "13067"),
            ("gousse d'ail", 1, "pièce", 5, "11000"),
            ("gingembre frais", 10, "g", 10, "11074"),
            ("cacahuètes concassées (facultatif)", 20, "g", 20, "15001"),
        ],
        [
            ("Râpe l'ail et le gingembre.", None),
            ("Dans une petite casserole, chauffe doucement le lait de coco avec l'ail et le gingembre.", 3),
            ("Ajoute le beurre de cacahuète, la sauce soja et le sucre, fouette jusqu'à ce que ce soit lisse.", 5),
            ("Hors du feu, ajoute le jus du citron vert ; détends avec un peu d'eau si besoin.", None),
            ("Sers tiède, parsemée de cacahuètes concassées.", None),
        ],
    ),
    (
        "sauce-chimichurri", "Chimichurri",
        "La sauce argentine au persil, origan et vinaigre, faite pour les grillades.",
        "🌱", "amerique_sud", "sauce", "facile", 15, 0, 6, ["sans-cuisson", "barbecue", "vegan"],
        [
            ("persil plat", 1, "bouquet", 50, "11014"),
            ("origan séché", 1, "càs", 3, "11035"),
            ("gousses d'ail", 3, "pièce", 15, "11000"),
            ("piment rouge frais", 1, "pièce", 10, "20151"),
            ("vinaigre de vin rouge", 4, "càs", 60, "11220"),
            ("huile d'olive", 10, "cl", 90, "17270"),
            ("sel", 1, "pincée", 1, None),
        ],
        [
            ("Hache finement le persil, l'ail et le piment au couteau.", None),
            ("Mets-les dans un bocal avec l'origan et le sel.", None),
            ("Verse le vinaigre, puis l'huile, et mélange.", None),
            ("Laisse reposer au moins 30 minutes pour que les saveurs se marient.", 30),
        ],
    ),
    (
        "sauce-salsa-verde", "Salsa verde à l'italienne",
        "Une sauce verte aux herbes, câpres et anchois, vive et salée, pour viandes et poissons.",
        "🍃", "italie", "sauce", "facile", 15, 0, 6, ["sans-cuisson"],
        [
            ("persil plat", 1, "bouquet", 40, "11014"),
            ("basilic frais", 0.5, "bouquet", 15, "11033"),
            ("câpres", 1, "càs", 10, None),
            ("filets d'anchois à l'huile", 3, "pièce", 12, "26000"),
            ("cornichons", 2, "pièce", 20, "11004"),
            ("moutarde de Dijon", 1, "càc", 5, "11013"),
            ("vinaigre de vin rouge", 1, "càs", 15, "11220"),
            ("huile d'olive", 8, "cl", 72, "17270"),
        ],
        [
            ("Hache ensemble le persil, le basilic, les câpres, les anchois et les cornichons.", None),
            ("Dans un bol, mélange la moutarde et le vinaigre.", None),
            ("Ajoute le hachis puis l'huile d'olive en remuant.", None),
            ("Goûte avant de saler : les anchois et les câpres le sont déjà.", None),
        ],
    ),
    (
        "sauce-romesco", "Sauce romesco",
        "La sauce catalane aux poivrons grillés, amandes et noisettes, épaisse et fumée.",
        "🫑", "espagne", "sauce", "moyen", 15, 25, 6, ["four", "vegan"],
        [
            ("poivrons rouges", 2, "pièce", 300, "20087"),
            ("tomates", 2, "pièce", 250, "20047"),
            ("gousses d'ail", 3, "pièce", 15, "11000"),
            ("amandes", 40, "g", 40, "15000"),
            ("noisettes grillées", 30, "g", 30, "15033"),
            ("tranche de pain", 1, "pièce", 30, "7001"),
            ("paprika fumé", 1, "càc", 3, "11049"),
            ("vinaigre de vin rouge", 2, "càs", 30, "11220"),
            ("huile d'olive", 8, "cl", 72, "17270"),
        ],
        [
            ("Préchauffe le four à 220 °C et fais rôtir les poivrons, les tomates et l'ail en chemise.", 25),
            ("Pendant ce temps, fais dorer les amandes et le pain dans un peu d'huile.", 4),
            ("Pèle les poivrons, les tomates et l'ail, retire les graines des poivrons.", None),
            ("Mixe les légumes avec les amandes, les noisettes, le pain et le paprika.", None),
            ("Ajoute le vinaigre puis l'huile en mixant, sale et garde une texture un peu granuleuse.", None),
        ],
    ),
    (
        "sauce-teriyaki", "Sauce teriyaki",
        "La sauce japonaise sucrée-salée au saké et au soja, laquée et brillante.",
        "🍶", "japon", "sauce", "facile", 5, 8, 6, ["express", "laque"],
        [
            ("sauce soja", 10, "cl", 110, "11104"),
            ("saké", 6, "cl", 60, "1026"),
            ("mirin", 6, "cl", 65, None),
            ("sucre roux", 2, "càs", 25, "31017"),
            ("gingembre frais", 10, "g", 10, "11074"),
            ("fécule de maïs", 1, "càc", 4, "9510"),
        ],
        [
            ("Verse la sauce soja, le saké, le mirin et le sucre dans une petite casserole.", None),
            ("Ajoute le gingembre râpé et porte à frémissement.", 3),
            ("Délaye la fécule dans une cuillère d'eau froide et verse-la en fouettant.", None),
            ("Laisse épaissir à feu doux jusqu'à ce que la sauce nappe la cuillère.", 4),
            ("Utilise-la pour laquer en fin de cuisson ou en sauce à part.", None),
        ],
    ),
    (
        "sauce-nuoc-cham", "Nuoc cham",
        "La sauce vietnamienne au nuoc-mâm, citron vert et piment, pour nems et bols de vermicelles.",
        "🌶️", "vietnam", "sauce", "facile", 10, 0, 6, ["sans-cuisson", "express"],
        [
            ("sauce nuoc-mâm", 4, "càs", 60, "11194"),
            ("sucre", 3, "càs", 36, "31016"),
            ("citron vert", 2, "pièce", 60, "13067"),
            ("eau tiède", 12, "cl", 120, "18066"),
            ("gousse d'ail", 1, "pièce", 5, "11000"),
            ("piment rouge frais", 1, "pièce", 10, "20151"),
            ("carotte râpée (facultatif)", 20, "g", 20, "20009"),
        ],
        [
            ("Dissous le sucre dans l'eau tiède.", None),
            ("Ajoute le nuoc-mâm et le jus des citrons verts.", None),
            ("Hache finement l'ail et le piment, ajoute-les à la sauce.", None),
            ("Goûte : l'équilibre doit être à la fois salé, sucré et acide ; ajoute la carotte si tu veux.", None),
        ],
    ),
    (
        "sauce-chermoula", "Chermoula",
        "La marinade-sauce marocaine aux herbes, citron et épices, idéale avec le poisson.",
        "🐟", "maroc", "sauce", "facile", 15, 0, 6, ["sans-cuisson", "marinade", "vegan"],
        [
            ("coriandre fraîche", 1, "bouquet", 40, "11094"),
            ("persil plat", 1, "bouquet", 40, "11014"),
            ("gousses d'ail", 3, "pièce", 15, "11000"),
            ("cumin moulu", 2, "càc", 6, "11042"),
            ("paprika", 2, "càc", 6, "11049"),
            ("piment de Cayenne", 1, "pincée", 1, "11088"),
            ("citron", 1, "pièce", 60, "13009"),
            ("huile d'olive", 8, "cl", 72, "17270"),
            ("sel", 1, "pincée", 1, None),
        ],
        [
            ("Hache finement la coriandre, le persil et l'ail.", None),
            ("Ajoute le cumin, le paprika, le piment et le sel.", None),
            ("Verse le jus du citron et l'huile, mélange bien.", None),
            ("Utilise-la en marinade une heure avant la cuisson, ou en sauce à table.", None),
        ],
    ),
    (
        "sauce-tahin-citron", "Sauce au tahin et citron",
        "La sauce libanaise au sésame, citron et ail, qui accompagne falafels et légumes rôtis.",
        "🍋", "liban", "sauce", "facile", 10, 0, 6, ["sans-cuisson", "vegan", "express"],
        [
            ("tahin (purée de sésame)", 120, "g", 120, "15203"),
            ("citron", 1, "pièce", 60, "13009"),
            ("gousse d'ail", 1, "pièce", 5, "11000"),
            ("eau froide", 10, "cl", 100, "18066"),
            ("sel", 1, "pincée", 1, None),
            ("persil plat (facultatif)", 1, "càs", 5, "11014"),
        ],
        [
            ("Mélange le tahin avec l'ail râpé et le jus de citron : la pâte va d'abord épaissir.", None),
            ("Ajoute l'eau froide petit à petit en fouettant jusqu'à une sauce lisse et crémeuse.", None),
            ("Sale et ajuste l'acidité à ton goût.", None),
            ("Parsème de persil haché au moment de servir.", None),
        ],
    ),
    (
        "sauce-beurre-blanc", "Beurre blanc",
        "La sauce nantaise au vin blanc et aux échalotes, montée au beurre froid, pour le poisson.",
        "🧈", "france", "sauce", "moyen", 10, 15, 4, ["classique", "poisson"],
        [
            ("échalotes", 2, "pièce", 60, "20097"),
            ("vin blanc sec", 10, "cl", 100, "5215"),
            ("vinaigre", 3, "càs", 45, "11018"),
            ("beurre demi-sel très froid", 200, "g", 200, "16400"),
            ("poivre", 1, "pincée", 1, "11015"),
        ],
        [
            ("Cisèle les échalotes très finement.", None),
            ("Fais-les réduire avec le vin blanc et le vinaigre jusqu'à ce qu'il ne reste presque plus de liquide.", 10),
            ("Coupe le beurre en petits dés et garde-le au froid.", None),
            ("À feu très doux, incorpore le beurre dés par dés en fouettant, sans jamais faire bouillir.", 5),
            ("Poivre, filtre si tu la veux lisse et sers aussitôt.", None),
        ],
    ),
    (
        "sauce-bearnaise", "Sauce béarnaise",
        "La grande sauce au beurre et à l'estragon, faite pour une pièce de bœuf grillée.",
        "🥩", "france", "sauce", "difficile", 15, 20, 4, ["classique", "bain-marie"],
        [
            ("échalotes", 2, "pièce", 60, "20097"),
            ("estragon frais", 1, "bouquet", 15, "11092"),
            ("vin blanc sec", 5, "cl", 50, "5215"),
            ("vinaigre", 5, "cl", 50, "11018"),
            ("jaunes d'œufs", 3, "pièce", 60, "22002"),
            ("beurre", 180, "g", 180, "16400"),
            ("poivre", 1, "pincée", 1, "11015"),
            ("sel", 1, "pincée", 1, None),
        ],
        [
            ("Fais réduire les échalotes ciselées, la moitié de l'estragon, le vin et le vinaigre jusqu'aux deux tiers.", 8),
            ("Fais fondre le beurre doucement et laisse-le tiédir.", 3),
            ("Hors du feu, ajoute les jaunes et une cuillère d'eau à la réduction refroidie.", None),
            ("Fouette au bain-marie à feu doux jusqu'à obtenir une mousse épaisse.", 6),
            ("Verse le beurre tiède en filet en fouettant, puis filtre.", 3),
            ("Ajoute le reste d'estragon haché, sale, poivre et garde au chaud sans bouillir.", None),
        ],
    ),
    (
        "sauce-barbecue-maison", "Sauce barbecue maison",
        "Une sauce barbecue à l'américaine, sucrée, fumée et acidulée, pour ribs et burgers.",
        "🔥", "etats_unis", "sauce", "facile", 10, 20, 8, ["barbecue", "batch-cooking"],
        [
            ("ketchup", 250, "g", 250, "11008"),
            ("concentré de tomate", 2, "càs", 30, "20068"),
            ("vinaigre de cidre", 5, "cl", 50, "11018"),
            ("miel", 3, "càs", 60, "31008"),
            ("sucre roux", 2, "càs", 25, "31017"),
            ("moutarde", 1, "càs", 15, "11013"),
            ("oignon", 1, "pièce", 100, "20239"),
            ("paprika fumé", 2, "càc", 6, "11049"),
            ("gousse d'ail", 1, "pièce", 5, "11000"),
        ],
        [
            ("Râpe l'oignon et l'ail.", None),
            ("Mets tous les ingrédients dans une casserole et mélange.", None),
            ("Porte à frémissement puis laisse réduire à feu doux en remuant souvent.", 20),
            ("Mixe si tu veux une sauce lisse et laisse refroidir.", None),
            ("Conserve-la en bocal au frais jusqu'à deux semaines.", None),
        ],
    ),
    (
        "harissa-maison", "Harissa maison",
        "La pâte de piments tunisienne au carvi et à la coriandre, à doser selon ton goût.",
        "🌶️", "tunisie", "sauce", "moyen", 20, 0, 12, ["vegan", "epice", "bocal"],
        [
            ("piments rouges séchés", 60, "g", 60, None),
            ("gousses d'ail", 4, "pièce", 20, "11000"),
            ("graines de carvi", 1, "càc", 3, "11064"),
            ("graines de coriandre", 1, "càc", 3, "11026"),
            ("cumin moulu", 1, "càc", 3, "11042"),
            ("huile d'olive", 6, "cl", 54, "17270"),
            ("sel", 1, "càc", 5, None),
        ],
        [
            ("Retire les queues et une partie des graines des piments, puis fais-les tremper dans l'eau chaude.", 20),
            ("Pile ou moud le carvi et la coriandre.", None),
            ("Égoutte les piments et mixe-les avec l'ail, les épices et le sel en une pâte épaisse.", None),
            ("Ajoute la moitié de l'huile et mixe encore.", None),
            ("Mets en bocal et recouvre d'une couche d'huile ; elle se garde plusieurs semaines au frais.", None),
        ],
    ),
    (
        "guacamole-maison", "Guacamole",
        "L'écrasé d'avocat mexicain au citron vert, coriandre et piment, à préparer minute.",
        "🥑", "mexique", "sauce", "facile", 15, 0, 4, ["sans-cuisson", "apero", "vegan"],
        [
            ("avocats mûrs", 2, "pièce", 300, "13004"),
            ("citron vert", 1, "pièce", 30, "13067"),
            ("oignon rouge", 0.5, "pièce", 40, "20238"),
            ("tomate", 1, "pièce", 120, "20047"),
            ("coriandre fraîche", 0.5, "bouquet", 15, "11094"),
            ("piment vert frais", 1, "pièce", 10, "20151"),
            ("sel", 1, "pincée", 1, None),
        ],
        [
            ("Hache finement l'oignon, le piment et la coriandre.", None),
            ("Coupe la tomate en petits dés en retirant les graines.", None),
            ("Écrase la chair des avocats à la fourchette avec le jus du citron vert et le sel.", None),
            ("Incorpore le reste des ingrédients en gardant un peu de texture, et sers aussitôt.", None),
        ],
    ),
]
