# Starter recipes, theme "soupes_entrees": soups, starters and salads.
# Same tuple shape as scripts/seed-world-recipes.py:
# (slug, title, description, icon, cuisine, category, difficulty, prep, cook,
#  servings, tags, ingredients[(label, qty, unit, grams, ciqual)],
#  steps[(text, minutes|None)])
R = [
    (
        "soupe-giraumon-coco", "Soupe de giraumon au lait de coco",
        "Une soupe antillaise veloutée de potiron, relevée de gingembre et adoucie au lait de coco.",
        "🎃", "antilles", "soupe", "facile", 15, 30, 4, ["vegan", "hiver"],
        [
            ("potiron", 1, "kg", 1000, "20044"),
            ("oignon", 1, "pièce", 150, "20239"),
            ("gousses d'ail", 2, "pièce", 10, "11000"),
            ("gingembre frais", 1, "morceau", 15, "11074"),
            ("lait de coco", 20, "cl", 200, "18041"),
            ("bouillon de légumes", 60, "cl", 600, "25948"),
            ("huile d'olive", 2, "càs", 24, "17270"),
            ("thym frais", 2, "brins", 2, "11070"),
            ("piment (facultatif)", 1, "pièce", 5, "20151"),
        ],
        [
            ("Épluche le potiron, retire les graines et coupe la chair en cubes.", None),
            ("Fais fondre l'oignon émincé dans l'huile avec l'ail et le gingembre râpé.", 5),
            ("Ajoute le potiron, le thym et le bouillon, puis laisse cuire à couvert.", 25),
            ("Retire le thym, verse le lait de coco et mixe jusqu'à obtenir une texture lisse.", None),
            ("Rectifie l'assaisonnement et ajoute un peu de piment si tu aimes le relevé.", None),
        ],
    ),
    (
        "soupe-oignon-gratinee", "Soupe à l'oignon gratinée",
        "La soupe parisienne aux oignons longuement caramélisés, couverte de pain et de fromage gratiné.",
        "🧅", "france", "soupe", "moyen", 20, 60, 4, ["hiver", "four", "classique"],
        [
            ("oignons", 6, "pièce", 900, "20239"),
            ("beurre", 40, "g", 40, "16400"),
            ("farine", 1, "càs", 10, "9435"),
            ("vin blanc sec", 15, "cl", 150, "5215"),
            ("bouillon de bœuf", 1, "l", 1000, "25930"),
            ("baguette", 8, "tranches", 120, "7001"),
            ("gruyère râpé", 120, "g", 120, "12114"),
            ("thym frais", 2, "brins", 2, "11070"),
            ("poivre", 1, "pincée", 1, "11015"),
        ],
        [
            ("Émince finement les oignons.", None),
            ("Fais-les fondre dans le beurre à feu doux en remuant souvent, jusqu'à ce qu'ils soient bien dorés.", 30),
            ("Saupoudre de farine, mélange, puis déglace au vin blanc.", 2),
            ("Verse le bouillon, ajoute le thym et laisse mijoter.", 20),
            ("Répartis la soupe dans des bols allant au four, pose le pain grillé et couvre de gruyère.", None),
            ("Passe sous le gril jusqu'à ce que le fromage soit gratiné.", 5),
        ],
    ),
    (
        "minestrone-legumes", "Minestrone",
        "La grande soupe italienne de légumes, haricots blancs et petites pâtes.",
        "🥣", "italie", "soupe", "facile", 20, 40, 6, ["batch-cooking", "hiver"],
        [
            ("oignon", 1, "pièce", 150, "20239"),
            ("carottes", 2, "pièce", 200, "20009"),
            ("céleri branche", 2, "branches", 100, "20023"),
            ("courgette", 1, "pièce", 200, "20020"),
            ("pommes de terre", 2, "pièce", 250, "4008"),
            ("tomates pelées", 400, "g", 400, "20048"),
            ("haricots blancs cuits", 250, "g", 250, "20502"),
            ("petites pâtes", 100, "g", 100, "9810"),
            ("bouillon de légumes", 1.5, "l", 1500, "25948"),
            ("huile d'olive", 3, "càs", 36, "17270"),
            ("basilic frais", 1, "bouquet", 15, "11033"),
            ("parmesan râpé (facultatif)", 40, "g", 40, "12120"),
        ],
        [
            ("Coupe l'oignon, les carottes, le céleri, la courgette et les pommes de terre en petits dés.", None),
            ("Fais revenir l'oignon, les carottes et le céleri dans l'huile.", 8),
            ("Ajoute les pommes de terre, la courgette, les tomates et le bouillon, puis laisse mijoter.", 20),
            ("Verse les pâtes et les haricots, et poursuis la cuisson jusqu'à ce que les pâtes soient tendres.", 10),
            ("Sers avec le basilic ciselé et, si tu veux, un peu de parmesan.", None),
        ],
    ),
    (
        "pho-bo", "Soupe pho au bœuf",
        "Le bouillon vietnamien parfumé à l'anis étoilé, servi avec nouilles de riz et fines tranches de bœuf.",
        "🍜", "vietnam", "soupe", "moyen", 25, 45, 4, ["reconfort"],
        [
            ("bouillon de bœuf", 1.5, "l", 1500, "25930"),
            ("oignon", 1, "pièce", 150, "20239"),
            ("gingembre frais", 1, "morceau", 30, "11074"),
            ("anis étoilé", 3, "pièce", 3, None),
            ("bâton de cannelle", 1, "pièce", 3, "11025"),
            ("sauce nuoc-mâm", 3, "càs", 45, "11194"),
            ("vermicelles de riz", 250, "g", 250, "9900"),
            ("rumsteck de bœuf", 300, "g", 300, "6206"),
            ("oignons nouveaux", 3, "pièce", 45, "20323"),
            ("coriandre fraîche", 1, "bouquet", 15, "11094"),
            ("citron vert", 1, "pièce", 60, "13067"),
            ("piment (facultatif)", 1, "pièce", 5, "20151"),
        ],
        [
            ("Fais noircir l'oignon coupé en deux et le gingembre dans une poêle à sec.", 8),
            ("Mets-les dans le bouillon avec l'anis, la cannelle et le nuoc-mâm, puis laisse frémir.", 30),
            ("Pendant ce temps, place le bœuf au congélateur, puis tranche-le très finement.", None),
            ("Fais tremper ou cuire les vermicelles selon le paquet et répartis-les dans les bols.", 5),
            ("Dispose le bœuf cru sur les nouilles et verse le bouillon filtré bouillant par-dessus : il cuit instantanément.", None),
            ("Garnis d'oignons nouveaux, de coriandre, de citron vert et de piment.", None),
        ],
    ),
    (
        "tom-yum-crevettes", "Tom yum aux crevettes",
        "La soupe thaïlandaise acidulée et pimentée, parfumée à la citronnelle et au citron vert.",
        "🦐", "thailande", "soupe", "facile", 15, 15, 4, ["express", "epice"],
        [
            ("crevettes crues décortiquées", 400, "g", 400, "10021"),
            ("bouillon de volaille", 1, "l", 1000, "25947"),
            ("tiges de citronnelle", 2, "pièce", 40, None),
            ("gingembre frais", 1, "morceau", 20, "11074"),
            ("champignons", 200, "g", 200, "20010"),
            ("tomates cerises", 150, "g", 150, "20172"),
            ("sauce nuoc-mâm", 3, "càs", 45, "11194"),
            ("citrons verts", 2, "pièce", 120, "13067"),
            ("piment", 2, "pièce", 10, "20151"),
            ("coriandre fraîche", 1, "bouquet", 15, "11094"),
        ],
        [
            ("Écrase la citronnelle et coupe-la en tronçons, tranche le gingembre et le piment.", None),
            ("Fais frémir le bouillon avec la citronnelle, le gingembre et le piment.", 8),
            ("Ajoute les champignons émincés et les tomates cerises coupées en deux.", 3),
            ("Plonge les crevettes et laisse cuire jusqu'à ce qu'elles deviennent roses.", 3),
            ("Hors du feu, ajoute le nuoc-mâm et le jus des citrons verts, goûte et ajuste.", None),
            ("Parsème de coriandre et sers aussitôt.", None),
        ],
    ),
    (
        "mercimek-corbasi", "Soupe de lentilles corail à la turque",
        "La soupe turque de lentilles corail, veloutée et relevée d'un beurre au paprika.",
        "🥣", "turquie", "soupe", "facile", 10, 30, 4, ["express", "hiver"],
        [
            ("lentilles corail", 250, "g", 250, "20535"),
            ("oignon", 1, "pièce", 150, "20239"),
            ("carotte", 1, "pièce", 100, "20009"),
            ("pomme de terre", 1, "pièce", 150, "4008"),
            ("concentré de tomate", 1, "càs", 20, "20068"),
            ("cumin", 1, "càc", 3, "11042"),
            ("bouillon de légumes", 1.2, "l", 1200, "25948"),
            ("beurre", 30, "g", 30, "16400"),
            ("paprika", 1, "càc", 3, "11049"),
            ("citron", 1, "pièce", 100, "13009"),
            ("menthe séchée (facultatif)", 1, "càc", 1, "11029"),
        ],
        [
            ("Rince les lentilles jusqu'à ce que l'eau soit claire.", None),
            ("Fais revenir l'oignon, la carotte et la pomme de terre en dés dans la moitié du beurre.", 5),
            ("Ajoute le concentré de tomate, le cumin, les lentilles et le bouillon, puis laisse cuire.", 25),
            ("Mixe finement et rectifie l'assaisonnement.", None),
            ("Fais mousser le reste du beurre avec le paprika et verse-le en filet sur chaque bol.", 1),
            ("Sers avec un quartier de citron et un peu de menthe séchée.", None),
        ],
    ),
    (
        "caesar-salad-poulet", "Caesar salad au poulet",
        "La salade de romaine croquante, poulet doré, croûtons et sauce crémeuse au parmesan.",
        "🥗", "etats_unis", "salade", "moyen", 20, 15, 4, ["classique"],
        [
            ("laitue romaine", 2, "pièce", 500, "20171"),
            ("filets de poulet", 2, "pièce", 300, "36017"),
            ("pain de campagne", 3, "tranches", 120, "7261"),
            ("parmesan râpé", 50, "g", 50, "12120"),
            ("jaune d'œuf", 1, "pièce", 20, "22000"),
            ("filets d'anchois à l'huile", 4, "pièce", 16, "26000"),
            ("gousse d'ail", 1, "pièce", 5, "11000"),
            ("moutarde", 1, "càc", 5, "11013"),
            ("jus de citron", 2, "càs", 30, "13009"),
            ("huile d'olive", 8, "càs", 96, "17270"),
            ("poivre", 1, "pincée", 1, "11015"),
        ],
        [
            ("Coupe le pain en cubes, arrose-les d'un filet d'huile et fais-les dorer au four à 200 °C.", 8),
            ("Fais cuire les filets de poulet à la poêle avec un peu d'huile, puis tranche-les.", 10),
            ("Mixe le jaune d'œuf, les anchois, l'ail, la moutarde et le citron, puis monte avec l'huile restante et la moitié du parmesan.", None),
            ("Lave et coupe la romaine, mélange-la avec la sauce.", None),
            ("Ajoute le poulet, les croûtons et le reste du parmesan, poivre et sers.", None),
        ],
    ),
    (
        "salade-nicoise", "Salade niçoise",
        "La salade de Nice aux tomates, thon, œufs durs, olives et anchois, sans rien de cuit à part les œufs.",
        "🥗", "france", "salade", "facile", 20, 10, 4, ["ete", "classique"],
        [
            ("tomates", 4, "pièce", 500, "20047"),
            ("œufs", 4, "pièce", 220, "22000"),
            ("thon au naturel", 200, "g", 200, "26039"),
            ("poivron vert", 1, "pièce", 150, "20085"),
            ("concombre", 0.5, "pièce", 150, "20019"),
            ("oignon nouveau", 2, "pièce", 30, "20323"),
            ("olives noires", 60, "g", 60, "13131"),
            ("filets d'anchois à l'huile", 8, "pièce", 32, "26000"),
            ("huile d'olive", 4, "càs", 48, "17270"),
            ("basilic frais", 6, "feuilles", 3, "11033"),
        ],
        [
            ("Fais durcir les œufs, refroidis-les dans l'eau froide et écale-les.", 10),
            ("Coupe les tomates en quartiers, sale-les légèrement et laisse-les rendre un peu d'eau.", None),
            ("Émince le poivron, le concombre et l'oignon nouveau.", None),
            ("Dispose tous les légumes, le thon émietté, les œufs en quartiers, les olives et les anchois.", None),
            ("Arrose d'huile d'olive, parsème de basilic déchiré et sers bien frais.", None),
        ],
    ),
    (
        "carpaccio-betterave-chevre", "Carpaccio de betterave au chèvre",
        "De fines tranches de betterave, du chèvre frais, des noix et un filet de balsamique.",
        "🧀", "autre", "entree", "facile", 15, 0, 4, ["sans-cuisson", "express"],
        [
            ("betteraves cuites", 3, "pièce", 450, "20003"),
            ("fromage de chèvre frais", 120, "g", 120, "12812"),
            ("cerneaux de noix", 40, "g", 40, "15005"),
            ("huile d'olive", 3, "càs", 36, "17270"),
            ("vinaigre balsamique", 1, "càs", 15, "11091"),
            ("roquette ou mâche", 40, "g", 40, "20099"),
            ("ciboulette", 0.5, "bouquet", 5, "11003"),
            ("poivre", 1, "pincée", 1, "11015"),
        ],
        [
            ("Tranche les betteraves le plus finement possible, à la mandoline ou au couteau.", None),
            ("Étale-les en rosace sur les assiettes.", None),
            ("Émiette le chèvre par-dessus et ajoute les noix concassées.", None),
            ("Fouette l'huile et le balsamique, arrose les assiettes.", None),
            ("Termine avec quelques feuilles de salade, la ciboulette et un tour de poivre.", None),
        ],
    ),
    (
        "rouleaux-printemps-crevettes", "Rouleaux de printemps aux crevettes",
        "Des rouleaux vietnamiens frais aux crevettes, herbes et vermicelles, avec une sauce aux cacahuètes.",
        "🥢", "vietnam", "entree", "moyen", 35, 5, 4, ["sans-cuisson", "ete"],
        [
            ("galettes de riz", 12, "pièce", 100, None),
            ("crevettes cuites décortiquées", 250, "g", 250, "10007"),
            ("vermicelles de riz", 80, "g", 80, "9900"),
            ("salade sucrine", 1, "pièce", 150, "20288"),
            ("carotte", 1, "pièce", 100, "20009"),
            ("menthe fraîche", 1, "bouquet", 15, "11027"),
            ("coriandre fraîche", 1, "bouquet", 15, "11094"),
            ("beurre de cacahuète", 3, "càs", 45, "15202"),
            ("sauce soja", 2, "càs", 30, "11104"),
            ("citron vert", 1, "pièce", 60, "13067"),
        ],
        [
            ("Fais cuire les vermicelles selon le paquet, rince-les à l'eau froide et égoutte-les.", 5),
            ("Coupe les crevettes en deux dans l'épaisseur et râpe la carotte.", None),
            ("Trempe une galette quelques secondes dans l'eau tiède et pose-la sur un torchon humide.", None),
            ("Garnis de salade, vermicelles, carotte, herbes et crevettes, puis roule serré en rabattant les côtés.", None),
            ("Mélange le beurre de cacahuète, la sauce soja, le jus de citron vert et un peu d'eau pour la sauce.", None),
        ],
    ),
    (
        "oeufs-mimosa", "Œufs mimosa",
        "Des œufs durs garnis d'une farce crémeuse à la mayonnaise, saupoudrés de jaune émietté.",
        "🥚", "france", "entree", "facile", 20, 10, 4, ["classique", "apero"],
        [
            ("œufs", 6, "pièce", 330, "22000"),
            ("mayonnaise", 3, "càs", 45, "11054"),
            ("moutarde", 1, "càc", 5, "11013"),
            ("ciboulette", 0.5, "bouquet", 5, "11003"),
            ("paprika (facultatif)", 1, "pincée", 1, "11049"),
            ("poivre", 1, "pincée", 1, "11015"),
        ],
        [
            ("Plonge les œufs dans l'eau bouillante et compte dix minutes.", 10),
            ("Refroidis-les dans l'eau glacée, écale-les et coupe-les en deux dans la longueur.", None),
            ("Retire les jaunes et garde-en deux de côté.", None),
            ("Écrase les autres jaunes avec la mayonnaise, la moutarde, la ciboulette ciselée et le poivre.", None),
            ("Garnis les blancs de cette farce et émiette les jaunes réservés par-dessus à travers une passoire.", None),
        ],
    ),
    (
        "fattoush", "Fattoush",
        "La salade libanaise de crudités et d'herbes, avec des morceaux de pain pita grillé et une pointe de sumac.",
        "🥗", "liban", "salade", "facile", 20, 8, 4, ["vegan", "ete"],
        [
            ("pain pita", 2, "pièce", 120, "7180"),
            ("tomates", 3, "pièce", 360, "20047"),
            ("concombre", 1, "pièce", 300, "20019"),
            ("radis", 8, "pièce", 80, "20045"),
            ("salade sucrine", 1, "pièce", 150, "20288"),
            ("oignons nouveaux", 3, "pièce", 45, "20323"),
            ("persil plat", 1, "bouquet", 30, "11014"),
            ("menthe fraîche", 0.5, "bouquet", 10, "11027"),
            ("jus de citron", 3, "càs", 45, "13009"),
            ("huile d'olive", 5, "càs", 60, "17270"),
            ("sumac", 2, "càc", 5, None),
        ],
        [
            ("Coupe les pitas en carrés, arrose-les d'un peu d'huile et fais-les griller au four à 200 °C.", 8),
            ("Coupe les tomates, le concombre et les radis en morceaux, émince la salade et les oignons nouveaux.", None),
            ("Hache grossièrement le persil et la menthe.", None),
            ("Fouette le citron, le reste d'huile, le sumac et une pincée de sel.", None),
            ("Mélange tout et ajoute les pitas grillées au dernier moment pour qu'elles restent croustillantes.", None),
        ],
    ),
    (
        "salade-pates-italienne", "Salade de pâtes à l'italienne",
        "Des pâtes froides avec tomates cerises, mozzarella, jambon cru et basilic.",
        "🍝", "italie", "salade", "facile", 15, 10, 4, ["ete", "pique-nique"],
        [
            ("pâtes courtes", 300, "g", 300, "9810"),
            ("tomates cerises", 250, "g", 250, "20172"),
            ("mozzarella", 1, "boule", 125, "19590"),
            ("jambon cru", 4, "tranches", 80, "28800"),
            ("olives noires", 50, "g", 50, "13131"),
            ("roquette", 50, "g", 50, None),
            ("basilic frais", 1, "bouquet", 15, "11033"),
            ("huile d'olive", 4, "càs", 48, "17270"),
            ("vinaigre balsamique", 1, "càs", 15, "11091"),
        ],
        [
            ("Fais cuire les pâtes al dente dans une grande casserole d'eau salée.", 10),
            ("Égoutte-les, rince-les à l'eau froide et mélange-les avec un peu d'huile.", None),
            ("Coupe les tomates cerises en deux, la mozzarella en dés et le jambon en lanières.", None),
            ("Mélange les pâtes avec la garniture, les olives et la roquette.", None),
            ("Assaisonne avec le reste d'huile, le balsamique et le basilic ciselé ; sers frais.", None),
        ],
    ),
    (
        "veloute-petits-pois-menthe", "Velouté de petits pois à la menthe",
        "Un velouté vert vif, doux et frais, relevé de menthe et d'une touche de crème.",
        "🫛", "france", "soupe", "facile", 10, 15, 4, ["express", "printemps"],
        [
            ("petits pois surgelés", 600, "g", 600, "20084"),
            ("oignon", 1, "pièce", 150, "20239"),
            ("beurre", 20, "g", 20, "16400"),
            ("bouillon de légumes", 80, "cl", 800, "25948"),
            ("crème fraîche", 10, "cl", 100, "19410"),
            ("menthe fraîche", 0.5, "bouquet", 10, "11027"),
            ("poivre", 1, "pincée", 1, "11015"),
        ],
        [
            ("Fais fondre l'oignon émincé dans le beurre sans le colorer.", 4),
            ("Ajoute les petits pois et le bouillon, puis laisse cuire à petits frémissements.", 10),
            ("Ajoute les feuilles de menthe, en gardant quelques-unes pour le service.", None),
            ("Mixe longuement avec la crème pour garder une belle couleur.", None),
            ("Poivre, sers chaud ou froid avec la menthe réservée.", None),
        ],
    ),
    (
        "tarator-concombre", "Tarator, soupe froide au concombre",
        "La soupe froide bulgare au yaourt, concombre, aneth et noix, parfaite par temps chaud.",
        "🥒", "europe_est", "soupe", "facile", 15, 0, 4, ["sans-cuisson", "ete"],
        [
            ("concombres", 2, "pièce", 600, "20019"),
            ("yaourt nature", 500, "g", 500, "19593"),
            ("eau froide", 20, "cl", 200, None),
            ("gousses d'ail", 2, "pièce", 10, "11000"),
            ("cerneaux de noix", 50, "g", 50, "15005"),
            ("aneth frais", 0.5, "bouquet", 10, "11093"),
            ("huile d'olive", 2, "càs", 24, "17270"),
        ],
        [
            ("Pèle les concombres en laissant quelques bandes de peau et coupe-les en tout petits dés.", None),
            ("Écrase l'ail avec une pincée de sel.", None),
            ("Fouette le yaourt avec l'eau froide jusqu'à une texture de soupe.", None),
            ("Ajoute le concombre, l'ail, l'aneth ciselé et la moitié des noix concassées.", None),
            ("Réserve au frais au moins une heure, puis sers avec le reste des noix et un filet d'huile.", None),
        ],
    ),
    (
        "salade-thai-boeuf", "Salade thaï au bœuf",
        "Du bœuf saisi tranché sur une salade croquante d'herbes, citron vert et cacahuètes.",
        "🥩", "thailande", "salade", "moyen", 20, 8, 4, ["epice", "ete"],
        [
            ("rumsteck de bœuf", 400, "g", 400, "6206"),
            ("concombre", 1, "pièce", 300, "20019"),
            ("oignon rouge", 1, "pièce", 100, "20238"),
            ("salade sucrine", 1, "pièce", 150, "20288"),
            ("menthe fraîche", 1, "bouquet", 15, "11027"),
            ("coriandre fraîche", 1, "bouquet", 15, "11094"),
            ("cacahuètes grillées", 40, "g", 40, "15053"),
            ("sauce nuoc-mâm", 3, "càs", 45, "11194"),
            ("citrons verts", 2, "pièce", 120, "13067"),
            ("sucre", 1, "càc", 5, "31016"),
            ("piment", 1, "pièce", 5, "20151"),
            ("huile de tournesol", 1, "càs", 12, "17440"),
        ],
        [
            ("Saisis le bœuf dans l'huile très chaude, deux à trois minutes par face, puis laisse-le reposer.", 6),
            ("Mélange le nuoc-mâm, le jus des citrons verts, le sucre et le piment émincé.", None),
            ("Émince le concombre, l'oignon rouge et la salade, effeuille les herbes.", None),
            ("Tranche finement le bœuf et mélange-le avec les légumes et la sauce.", None),
            ("Parsème de cacahuètes concassées au moment de servir.", None),
        ],
    ),
    (
        "tartare-saumon-avocat", "Tartare de saumon à l'avocat",
        "Du saumon cru taillé au couteau, avocat fondant, citron vert et sésame.",
        "🐟", "autre", "entree", "facile", 20, 0, 4, ["sans-cuisson", "express"],
        [
            ("saumon très frais sans peau", 400, "g", 400, "26036"),
            ("avocats mûrs", 2, "pièce", 280, "13004"),
            ("échalote", 1, "pièce", 30, "20097"),
            ("citron vert", 1, "pièce", 60, "13067"),
            ("sauce soja", 1, "càs", 15, "11104"),
            ("huile d'olive", 2, "càs", 24, "17270"),
            ("ciboulette", 0.5, "bouquet", 5, "11003"),
            ("graines de sésame (facultatif)", 1, "càs", 8, "15038"),
        ],
        [
            ("Taille le saumon en petits dés réguliers avec un couteau bien aiguisé.", None),
            ("Mélange-le avec l'échalote hachée, la sauce soja, l'huile et la ciboulette ciselée.", None),
            ("Coupe les avocats en dés et arrose-les du jus du citron vert.", None),
            ("Dresse dans un cercle : une couche d'avocat, puis le saumon.", None),
            ("Parsème de sésame et sers aussitôt, bien frais.", None),
        ],
    ),
    (
        "caldo-verde", "Caldo verde",
        "La soupe portugaise aux pommes de terre et au chou finement émincé, avec des rondelles de chorizo.",
        "🥬", "portugal", "soupe", "facile", 15, 30, 4, ["hiver", "reconfort"],
        [
            ("pommes de terre", 6, "pièce", 800, "4008"),
            ("oignon", 1, "pièce", 150, "20239"),
            ("gousses d'ail", 2, "pièce", 10, "11000"),
            ("chou frisé", 250, "g", 250, "20218"),
            ("chorizo", 120, "g", 120, "30315"),
            ("huile d'olive", 4, "càs", 48, "17270"),
            ("eau", 1.2, "l", 1200, None),
            ("poivre", 1, "pincée", 1, "11015"),
        ],
        [
            ("Fais fondre l'oignon et l'ail dans la moitié de l'huile.", 4),
            ("Ajoute les pommes de terre en morceaux et l'eau salée, puis laisse cuire.", 20),
            ("Mixe finement la soupe.", None),
            ("Roule les feuilles de chou et coupe-les en très fines lanières, ajoute-les à la soupe.", 5),
            ("Fais dorer le chorizo en rondelles à la poêle et répartis-le dans les bols avec un filet d'huile.", 3),
        ],
    ),
    (
        "salade-lentilles-vertes", "Salade de lentilles vertes",
        "Des lentilles tièdes à la vinaigrette moutardée, avec carotte, échalote et persil.",
        "🥗", "france", "salade", "facile", 15, 25, 4, ["vegan", "batch-cooking"],
        [
            ("lentilles vertes", 250, "g", 250, "20585"),
            ("carotte", 1, "pièce", 100, "20009"),
            ("échalotes", 2, "pièce", 60, "20097"),
            ("laurier", 1, "feuille", 1, None),
            ("moutarde", 1, "càs", 15, "11013"),
            ("vinaigre de vin", 2, "càs", 30, "11220"),
            ("huile de colza", 4, "càs", 48, "17130"),
            ("persil plat", 0.5, "bouquet", 15, "11014"),
        ],
        [
            ("Rince les lentilles et mets-les dans une casserole d'eau froide avec la carotte en dés et le laurier.", None),
            ("Porte à frémissement et laisse cuire sans saler, jusqu'à ce qu'elles soient tendres mais entières.", 25),
            ("Fouette la moutarde, le vinaigre, l'huile, le sel et le poivre.", None),
            ("Égoutte les lentilles et mélange-les encore tièdes avec la vinaigrette et les échalotes hachées.", None),
            ("Ajoute le persil ciselé et sers tiède ou froid.", None),
        ],
    ),
    (
        "sunomono-concombre-wakame", "Sunomono, salade de concombre au wakame",
        "Une petite salade japonaise de concombre et d'algue wakame à la vinaigrette de riz.",
        "🥒", "japon", "salade", "facile", 15, 0, 4, ["vegan", "sans-cuisson", "express"],
        [
            ("concombres", 2, "pièce", 500, "20019"),
            ("algue wakame séchée", 8, "g", 8, "20984"),
            ("vinaigre de riz", 4, "càs", 60, "11018"),
            ("sucre", 1, "càs", 12, "31016"),
            ("sauce soja", 1, "càs", 15, "11104"),
            ("graines de sésame", 1, "càs", 8, "15038"),
            ("gingembre frais (facultatif)", 1, "petit morceau", 5, "11074"),
        ],
        [
            ("Fais tremper le wakame dans l'eau froide, puis presse-le.", 10),
            ("Tranche les concombres très finement, sale-les et laisse-les dégorger.", 10),
            ("Mélange le vinaigre de riz, le sucre et la sauce soja jusqu'à ce que le sucre fonde.", None),
            ("Presse le concombre pour retirer l'eau, puis mélange-le avec le wakame et la sauce.", None),
            ("Parsème de sésame et d'un peu de gingembre râpé, sers bien frais.", None),
        ],
    ),
]
