# Vegetarian and vegan main dishes (a few sides) for the starter catalogue.
# Same tuple shape as scripts/seed-world-recipes.py. Original texts.

# (slug, title, description, icon, cuisine, category, difficulty, prep, cook,
#  servings, tags, ingredients[(label, qty, unit, grams, ciqual)],
#  steps[(text, minutes|None)])
R = [
    (
        "lasagnes-aux-legumes", "Lasagnes aux légumes",
        "Des couches de pâtes, de légumes d'été fondants et de béchamel, gratinées à la mozzarella.",
        "🍝", "italie", "plat", "moyen", 30, 45, 6, ["four", "batch-cooking"],
        [
            ("feuilles de lasagnes sèches", 250, "g", 250, "9810"),
            ("courgettes", 2, "pièce", 400, "20020"),
            ("aubergine", 1, "pièce", 300, "20300"),
            ("poivron rouge", 1, "pièce", 150, "20087"),
            ("tomates pelées", 800, "g", 800, "20048"),
            ("oignon", 1, "pièce", 150, "20239"),
            ("gousses d'ail", 2, "pièce", 10, "11000"),
            ("huile d'olive", 3, "càs", 36, "17270"),
            ("beurre", 50, "g", 50, "16400"),
            ("farine", 50, "g", 50, "9435"),
            ("lait", 60, "cl", 600, "19041"),
            ("mozzarella", 1, "boule", 125, "19590"),
            ("parmesan râpé", 50, "g", 50, "12120"),
            ("basilic frais (facultatif)", 1, "bouquet", 10, "11033"),
        ],
        [
            ("Coupe les courgettes, l'aubergine et le poivron en petits dés, émince l'oignon et l'ail.", None),
            ("Fais revenir l'oignon et l'ail dans l'huile, ajoute les légumes et laisse-les dorer.", 10),
            ("Verse les tomates pelées, sale, poivre et laisse compoter à feu moyen.", 15),
            ("Pour la béchamel, fais fondre le beurre, ajoute la farine, puis le lait petit à petit en fouettant jusqu'à ce que ça nappe.", 8),
            ("Préchauffe le four à 190 °C. Alterne dans un plat : sauce aux légumes, feuilles de lasagnes, béchamel, sur trois couches.", None),
            ("Termine par la mozzarella en morceaux et le parmesan, puis enfourne jusqu'à ce que ce soit bien doré.", 35),
            ("Laisse reposer quelques minutes et parsème de basilic avant de servir.", None),
        ],
    ),
    (
        "gratin-dauphinois", "Gratin dauphinois",
        "Des pommes de terre fines cuites lentement dans la crème et le lait parfumés à l'ail, spécialité du Dauphiné.",
        "🥔", "france", "accompagnement", "facile", 20, 75, 6, ["four", "hiver"],
        [
            ("pommes de terre à chair ferme", 1.2, "kg", 1200, "4008"),
            ("lait entier", 50, "cl", 500, "19023"),
            ("crème fraîche liquide", 30, "cl", 300, "19415"),
            ("gousse d'ail", 1, "pièce", 5, "11000"),
            ("beurre", 15, "g", 15, "16400"),
            ("noix de muscade", 1, "pincée", 1, "11048"),
            ("poivre", 1, "pincée", 1, "11015"),
        ],
        [
            ("Préchauffe le four à 160 °C. Frotte un plat avec la gousse d'ail coupée, puis beurre-le.", None),
            ("Épluche les pommes de terre et tranche-les en rondelles fines, sans les rincer.", None),
            ("Porte le lait et la crème à frémissement avec la muscade, du sel et du poivre, ajoute les pommes de terre et laisse cuire doucement en remuant.", 10),
            ("Verse le tout dans le plat en lissant la surface.", None),
            ("Enfourne jusqu'à ce que le dessus soit doré et que la pointe d'un couteau s'enfonce sans résistance.", 65),
        ],
    ),
    (
        "falafels-maison", "Falafels maison",
        "Des boulettes de pois chiches aux herbes, croustillantes dehors et vertes dedans, comme au Proche-Orient.",
        "🧆", "liban", "plat", "moyen", 25, 15, 4, ["vegan", "friture"],
        [
            ("pois chiches secs", 250, "g", 250, "20516"),
            ("oignon", 1, "pièce", 120, "20239"),
            ("gousses d'ail", 3, "pièce", 15, "11000"),
            ("persil plat", 1, "bouquet", 30, "11014"),
            ("coriandre fraîche", 1, "bouquet", 30, "11094"),
            ("cumin", 2, "càc", 4, "11042"),
            ("graines de coriandre", 1, "càc", 2, "11026"),
            ("levure chimique", 1, "càc", 4, "11046"),
            ("huile de friture", 50, "cl", 60, "17440"),
            ("pains pita", 4, "pièce", 240, "7180"),
            ("tahin (facultatif)", 3, "càs", 45, "15203"),
        ],
        [
            ("La veille, fais tremper les pois chiches dans un grand volume d'eau froide ; ils ne doivent pas être cuits.", None),
            ("Égoutte-les bien et mixe-les avec l'oignon, l'ail, les herbes et les épices, jusqu'à obtenir une semoule humide.", None),
            ("Ajoute la levure et du sel, puis laisse reposer la pâte au frais.", 30),
            ("Façonne des petites boulettes un peu aplaties en tassant bien.", None),
            ("Fais-les frire par petites quantités dans l'huile chaude jusqu'à ce qu'elles soient bien brunes.", 12),
            ("Égoutte sur du papier absorbant et sers dans les pitas avec un filet de tahin.", None),
        ],
    ),
    (
        "shakshuka-verte", "Shakshuka verte",
        "Des œufs pochés dans une poêlée d'épinards, de poireau et d'herbes, avec une touche de feta.",
        "🍳", "israel", "plat", "facile", 10, 20, 2, ["express", "une-poele"],
        [
            ("épinards frais", 300, "g", 300, "20270"),
            ("poireau", 1, "pièce", 150, "20039"),
            ("courgette", 1, "pièce", 200, "20020"),
            ("gousses d'ail", 2, "pièce", 10, "11000"),
            ("huile d'olive", 2, "càs", 24, "17270"),
            ("cumin", 1, "càc", 2, "11042"),
            ("œufs", 4, "pièce", 220, "22000"),
            ("feta", 60, "g", 60, "12066"),
            ("aneth frais (facultatif)", 1, "bouquet", 10, "11093"),
        ],
        [
            ("Émince finement le poireau, râpe la courgette et hache l'ail.", None),
            ("Fais fondre le poireau dans l'huile, puis ajoute la courgette, l'ail et le cumin.", 6),
            ("Ajoute les épinards par poignées, laisse-les tomber, sale et poivre.", 4),
            ("Creuse quatre puits, casse un œuf dans chacun et couvre.", None),
            ("Laisse cuire à feu doux jusqu'à ce que les blancs soient pris et les jaunes encore coulants.", 7),
            ("Émiette la feta, parsème d'aneth et sers dans la poêle avec du pain.", None),
        ],
    ),
    (
        "pad-thai-tofu", "Pad thaï au tofu",
        "Les nouilles de riz sautées de Thaïlande, avec tofu doré, œuf, pousses de soja et cacahuètes.",
        "🍜", "thailande", "plat", "moyen", 20, 12, 2, ["wok", "express"],
        [
            ("nouilles de riz plates", 200, "g", 200, "9900"),
            ("tofu ferme", 200, "g", 200, "20904"),
            ("œufs", 2, "pièce", 110, "22000"),
            ("pousses de soja", 100, "g", 100, "20183"),
            ("oignons nouveaux", 3, "pièce", 45, "20323"),
            ("gousses d'ail", 2, "pièce", 10, "11000"),
            ("sauce soja", 3, "càs", 45, "11104"),
            ("sucre roux", 1, "càs", 15, "31017"),
            ("citron vert", 1, "pièce", 60, "13067"),
            ("huile d'arachide", 3, "càs", 36, "17040"),
            ("cacahuètes grillées non salées", 40, "g", 40, "15053"),
            ("piment (facultatif)", 1, "pièce", 5, "20151"),
        ],
        [
            ("Fais tremper les nouilles dans de l'eau tiède jusqu'à ce qu'elles soient souples, puis égoutte-les.", 15),
            ("Mélange la sauce soja, le sucre et le jus du citron vert. Coupe le tofu en dés, concasse les cacahuètes.", None),
            ("Fais dorer le tofu dans l'huile chaude au wok, puis réserve-le.", 5),
            ("Fais revenir l'ail, pousse-le sur le côté et brouille les œufs rapidement.", 2),
            ("Ajoute les nouilles et la sauce, remue à feu vif, puis remets le tofu, les pousses et les oignons nouveaux.", 4),
            ("Sers aussitôt avec les cacahuètes, un quartier de citron vert et le piment.", None),
        ],
    ),
    (
        "buddha-bowl-patate-douce", "Buddha bowl à la patate douce",
        "Un grand bol de quinoa, patate douce rôtie, pois chiches épicés et avocat, nappé de sauce au tahin.",
        "🥗", "autre", "plat", "facile", 20, 30, 2, ["vegan", "meal-prep"],
        [
            ("quinoa", 150, "g", 150, "9340"),
            ("patate douce", 1, "pièce", 400, "4101"),
            ("pois chiches cuits", 200, "g", 200, "20507"),
            ("avocat", 1, "pièce", 150, "13004"),
            ("chou rouge", 150, "g", 150, "20014"),
            ("jeunes pousses d'épinards", 60, "g", 60, "20270"),
            ("huile d'olive", 3, "càs", 36, "17270"),
            ("paprika", 1, "càc", 2, "11049"),
            ("tahin", 3, "càs", 45, "15203"),
            ("jus de citron", 2, "càs", 30, "13009"),
            ("graines de sésame (facultatif)", 1, "càs", 8, "15038"),
        ],
        [
            ("Préchauffe le four à 200 °C. Coupe la patate douce en cubes, mélange-la avec la moitié de l'huile et du sel.", None),
            ("Enrobe les pois chiches égouttés du reste d'huile et du paprika, étale-les à côté de la patate douce et enfourne.", 30),
            ("Pendant ce temps, rince le quinoa et fais-le cuire dans deux fois son volume d'eau salée.", 12),
            ("Fouette le tahin avec le jus de citron, du sel et un peu d'eau pour une sauce nappante.", None),
            ("Émince finement le chou rouge et tranche l'avocat.", None),
            ("Garnis les bols : quinoa, pousses, légumes rôtis, chou, avocat, puis sauce et sésame.", None),
        ],
    ),
    (
        "gnocchis-sauce-tomate", "Gnocchis sauce tomate",
        "Des gnocchis dorés à la poêle dans une sauce tomate au basilic, avec des perles de mozzarella.",
        "🍅", "italie", "plat", "facile", 10, 20, 4, ["express", "une-poele"],
        [
            ("gnocchis à la pomme de terre", 800, "g", 800, "26264"),
            ("tomates pelées", 400, "g", 400, "20048"),
            ("concentré de tomate", 1, "càs", 15, "20068"),
            ("gousses d'ail", 2, "pièce", 10, "11000"),
            ("huile d'olive", 3, "càs", 36, "17270"),
            ("mozzarella", 1, "boule", 125, "19590"),
            ("basilic frais", 1, "bouquet", 15, "11033"),
            ("parmesan râpé (facultatif)", 30, "g", 30, "12120"),
        ],
        [
            ("Fais revenir l'ail émincé dans la moitié de l'huile sans le colorer.", 2),
            ("Ajoute les tomates écrasées et le concentré, sale, poivre et laisse mijoter.", 12),
            ("Dans une autre poêle, fais dorer les gnocchis dans le reste d'huile en les retournant.", 8),
            ("Verse les gnocchis dans la sauce, ajoute la mozzarella en morceaux et laisse-la fondre à peine.", 2),
            ("Parsème de basilic déchiré et de parmesan, sers bien chaud.", None),
        ],
    ),
    (
        "galettes-sarrasin-completes", "Galettes de sarrasin complètes",
        "Les galettes bretonnes au sarrasin, garnies d'œuf, de fromage fondu et de champignons.",
        "🥞", "france", "plat", "moyen", 15, 25, 4, ["sans-gluten", "creperie"],
        [
            ("farine de sarrasin", 250, "g", 250, "9540"),
            ("eau froide", 60, "cl", 600, None),
            ("sel", 1, "pincée", 2, None),
            ("beurre", 40, "g", 40, "16400"),
            ("œufs", 4, "pièce", 220, "22000"),
            ("emmental râpé", 150, "g", 150, "12118"),
            ("champignons de Paris", 250, "g", 250, "20010"),
            ("poivre", 1, "pincée", 1, "11015"),
        ],
        [
            ("Fouette la farine de sarrasin avec le sel et l'eau jusqu'à une pâte lisse et fluide, puis laisse reposer.", 60),
            ("Émince les champignons et fais-les sauter avec un peu de beurre, sale et poivre.", 6),
            ("Beurre une grande poêle chaude, verse une louche de pâte et étale-la finement.", None),
            ("Quand le bord se détache, casse un œuf au centre, étale le blanc, ajoute fromage et champignons.", 3),
            ("Replie les bords en carré en laissant le jaune visible, laisse le blanc prendre et sers aussitôt.", 2),
        ],
    ),
    (
        "tarte-aux-poireaux", "Tarte aux poireaux",
        "Une tarte fondante de poireaux étuvés au beurre, liés à la crème et aux œufs.",
        "🥧", "france", "plat", "facile", 20, 45, 6, ["four", "hiver"],
        [
            ("pâte brisée", 1, "pièce", 230, "23410"),
            ("poireaux", 4, "pièce", 600, "20039"),
            ("beurre", 30, "g", 30, "16400"),
            ("œufs", 3, "pièce", 165, "22000"),
            ("crème fraîche épaisse", 20, "cl", 200, "19410"),
            ("comté râpé", 60, "g", 60, "12110"),
            ("noix de muscade", 1, "pincée", 1, "11048"),
            ("poivre", 1, "pincée", 1, "11015"),
        ],
        [
            ("Fends les poireaux, rince-les bien et émince-les finement, vert tendre compris.", None),
            ("Fais-les fondre dans le beurre à couvert, à feu doux, sans coloration.", 15),
            ("Préchauffe le four à 190 °C et étale la pâte dans un moule.", None),
            ("Fouette les œufs avec la crème, la muscade, du sel et du poivre, puis ajoute les poireaux.", None),
            ("Verse sur la pâte, parsème de comté et enfourne jusqu'à ce que la tarte soit dorée et prise.", 30),
        ],
    ),
    (
        "mac-and-cheese", "Mac and cheese",
        "Le gratin de macaronis américain, noyé dans une sauce au cheddar et croustillant sur le dessus.",
        "🧀", "etats_unis", "plat", "facile", 15, 30, 4, ["four", "reconfort"],
        [
            ("macaronis", 300, "g", 300, "9810"),
            ("beurre", 40, "g", 40, "16400"),
            ("farine", 40, "g", 40, "9435"),
            ("lait entier", 60, "cl", 600, "19023"),
            ("cheddar râpé", 200, "g", 200, "12726"),
            ("moutarde", 1, "càc", 5, "11013"),
            ("paprika", 1, "pincée", 1, "11049"),
            ("chapelure", 30, "g", 30, "7500"),
        ],
        [
            ("Fais cuire les macaronis deux minutes de moins qu'indiqué, puis égoutte-les.", 8),
            ("Fais fondre le beurre, ajoute la farine, puis le lait petit à petit en fouettant jusqu'à épaississement.", 6),
            ("Hors du feu, incorpore les trois quarts du cheddar, la moutarde et le paprika, sale et poivre.", None),
            ("Préchauffe le four à 200 °C, mélange les pâtes à la sauce et verse dans un plat.", None),
            ("Couvre du reste de cheddar et de chapelure, puis gratine jusqu'à ce que ça bouillonne.", 15),
        ],
    ),
    (
        "enchiladas-aux-haricots", "Enchiladas aux haricots",
        "Des tortillas roulées autour de haricots rouges et de maïs, nappées de sauce tomate épicée et gratinées.",
        "🌯", "mexique", "plat", "facile", 20, 25, 4, ["four", "epice"],
        [
            ("tortillas de maïs", 8, "pièce", 320, "7813"),
            ("haricots rouges cuits", 400, "g", 400, "20503"),
            ("maïs doux", 150, "g", 150, "20066"),
            ("oignon", 1, "pièce", 120, "20239"),
            ("poivron vert", 1, "pièce", 150, "20085"),
            ("tomates pelées", 400, "g", 400, "20048"),
            ("cumin", 1, "càc", 2, "11042"),
            ("piment de Cayenne", 1, "pincée", 1, "11088"),
            ("huile d'olive", 2, "càs", 24, "17270"),
            ("cheddar râpé", 120, "g", 120, "12726"),
            ("coriandre fraîche (facultatif)", 1, "bouquet", 10, "11094"),
        ],
        [
            ("Mixe les tomates pelées avec la moitié du cumin, le piment et du sel pour la sauce.", None),
            ("Fais revenir l'oignon et le poivron émincés dans l'huile, ajoute les haricots, le maïs et le reste de cumin, puis écrase grossièrement.", 8),
            ("Préchauffe le four à 190 °C et verse un peu de sauce au fond d'un plat.", None),
            ("Garnis chaque tortilla de farce, roule-la et range-la dans le plat, jointure en dessous.", None),
            ("Nappe du reste de sauce, couvre de cheddar et enfourne jusqu'à ce que ça gratine.", 20),
            ("Parsème de coriandre avant de servir.", None),
        ],
    ),
    (
        "chana-masala", "Chana masala",
        "Un mijoté de pois chiches du nord de l'Inde, dans une sauce tomate aux épices et au gingembre.",
        "🍛", "inde", "plat", "facile", 15, 30, 4, ["vegan", "batch-cooking"],
        [
            ("pois chiches cuits", 500, "g", 500, "20507"),
            ("oignons", 2, "pièce", 250, "20239"),
            ("tomates", 3, "pièce", 360, "20047"),
            ("gingembre frais", 20, "g", 20, "11074"),
            ("gousses d'ail", 3, "pièce", 15, "11000"),
            ("huile d'arachide", 3, "càs", 36, "17040"),
            ("cumin", 1, "càc", 2, "11042"),
            ("curcuma", 1, "càc", 3, "11089"),
            ("garam masala", 2, "càc", 4, None),
            ("coriandre fraîche", 1, "bouquet", 15, "11094"),
            ("riz blanc", 300, "g", 300, "9100"),
        ],
        [
            ("Hache finement les oignons, l'ail et le gingembre, coupe les tomates en petits dés.", None),
            ("Fais griller le cumin dans l'huile chaude, puis ajoute les oignons et laisse-les bien dorer.", 10),
            ("Ajoute l'ail, le gingembre, le curcuma et le garam masala, remue une minute.", 1),
            ("Verse les tomates et laisse compoter jusqu'à ce que l'huile remonte.", 8),
            ("Ajoute les pois chiches et un verre d'eau, sale et laisse mijoter en écrasant quelques pois chiches pour épaissir.", 12),
            ("Pendant ce temps, fais cuire le riz. Sers le chana masala parsemé de coriandre.", None),
        ],
    ),
    (
        "palak-paneer", "Palak paneer",
        "Des cubes de paneer dorés dans une sauce onctueuse aux épinards et aux épices, spécialité indienne.",
        "🥬", "inde", "plat", "moyen", 20, 25, 4, ["sans-gluten", "epice"],
        [
            ("paneer", 250, "g", 250, None),
            ("épinards frais", 500, "g", 500, "20270"),
            ("oignon", 1, "pièce", 150, "20239"),
            ("tomate", 1, "pièce", 120, "20047"),
            ("gingembre frais", 15, "g", 15, "11074"),
            ("gousses d'ail", 3, "pièce", 15, "11000"),
            ("beurre", 30, "g", 30, "16400"),
            ("cumin", 1, "càc", 2, "11042"),
            ("garam masala", 1, "càc", 2, None),
            ("crème fraîche liquide", 5, "cl", 50, "19415"),
            ("piment (facultatif)", 1, "pièce", 5, "20151"),
        ],
        [
            ("Plonge les épinards deux minutes dans l'eau bouillante, rafraîchis-les puis mixe-les en purée.", 2),
            ("Coupe le paneer en cubes et fais-les dorer dans la moitié du beurre, puis réserve.", 5),
            ("Dans le reste du beurre, fais revenir le cumin, puis l'oignon haché, l'ail et le gingembre.", 8),
            ("Ajoute la tomate en dés et le garam masala, laisse compoter.", 5),
            ("Incorpore la purée d'épinards, sale, ajoute un peu d'eau si besoin et laisse frémir.", 5),
            ("Ajoute le paneer et la crème, réchauffe doucement et sers avec du riz ou des naans.", None),
        ],
    ),
    (
        "mapo-tofu-vegetal", "Mapo tofu végétal",
        "La version végétale du plat sichuanais : tofu soyeux et champignons dans une sauce pimentée et parfumée.",
        "🌶️", "chine", "plat", "moyen", 15, 15, 3, ["vegan", "epice"],
        [
            ("tofu soyeux", 400, "g", 400, "20906"),
            ("champignons", 200, "g", 200, "20010"),
            ("pâte de piment fermentée (doubanjiang)", 2, "càs", 30, None),
            ("sauce soja", 2, "càs", 30, "11104"),
            ("gousses d'ail", 3, "pièce", 15, "11000"),
            ("gingembre frais", 15, "g", 15, "11074"),
            ("huile de sésame", 1, "càs", 12, "17400"),
            ("huile d'arachide", 2, "càs", 24, "17040"),
            ("fécule de maïs", 1, "càs", 10, "9510"),
            ("oignons nouveaux", 2, "pièce", 30, "20323"),
            ("poivre du Sichuan", 1, "càc", 2, None),
            ("riz blanc", 250, "g", 250, "9100"),
        ],
        [
            ("Coupe le tofu en cubes et laisse-le tiédir dans de l'eau chaude salée pour le raffermir. Hache finement les champignons.", 5),
            ("Fais dorer les champignons dans l'huile d'arachide jusqu'à ce qu'ils soient bien secs et colorés.", 6),
            ("Ajoute l'ail, le gingembre et la pâte de piment, remue jusqu'à ce que l'huile rougisse.", 1),
            ("Verse la sauce soja et un verre d'eau, puis glisse délicatement le tofu égoutté.", 3),
            ("Lie avec la fécule délayée dans un peu d'eau froide, en remuant doucement.", 1),
            ("Termine avec l'huile de sésame, le poivre du Sichuan moulu et les oignons nouveaux, sers avec le riz.", None),
        ],
    ),
    (
        "risotto-de-courge", "Risotto de courge",
        "Un risotto crémeux à la courge fondante, déglacé au vin blanc et lié au parmesan.",
        "🎃", "italie", "plat", "moyen", 15, 30, 4, ["automne"],
        [
            ("riz rond pour risotto", 320, "g", 320, "9100"),
            ("courge butternut", 600, "g", 600, "20292"),
            ("oignon", 1, "pièce", 120, "20239"),
            ("vin blanc sec", 10, "cl", 100, "5215"),
            ("bouillon de légumes chaud", 1.2, "l", 1200, "25948"),
            ("beurre", 40, "g", 40, "16400"),
            ("huile d'olive", 2, "càs", 24, "17270"),
            ("parmesan râpé", 60, "g", 60, "12120"),
            ("thym frais (facultatif)", 3, "brins", 3, "11070"),
        ],
        [
            ("Épluche la courge et coupe-la en petits dés, émince l'oignon.", None),
            ("Fais revenir l'oignon dans l'huile, ajoute la courge et laisse-la colorer légèrement.", 6),
            ("Ajoute le riz et remue jusqu'à ce qu'il devienne translucide, puis déglace au vin blanc.", 2),
            ("Verse le bouillon chaud louche par louche, en attendant qu'il soit absorbé avant d'en rajouter.", 18),
            ("Hors du feu, incorpore le beurre et le parmesan, couvre et laisse reposer deux minutes.", 2),
            ("Sers aussitôt avec quelques feuilles de thym.", None),
        ],
    ),
    (
        "legumes-rotis-au-four", "Légumes rôtis au four",
        "Une grande plaque de légumes de saison caramélisés au four, au thym et à l'ail en chemise.",
        "🥕", "autre", "accompagnement", "facile", 15, 40, 4, ["vegan", "four"],
        [
            ("carottes", 3, "pièce", 300, "20009"),
            ("panais", 2, "pièce", 250, "20181"),
            ("oignons rouges", 2, "pièce", 200, "20238"),
            ("courgette", 1, "pièce", 200, "20020"),
            ("poivron jaune", 1, "pièce", 150, "20168"),
            ("gousses d'ail", 6, "pièce", 30, "11000"),
            ("huile d'olive", 4, "càs", 48, "17270"),
            ("thym frais", 4, "brins", 4, "11070"),
            ("vinaigre balsamique (facultatif)", 1, "càs", 15, "11091"),
        ],
        [
            ("Préchauffe le four à 210 °C.", None),
            ("Coupe les carottes et les panais en bâtonnets, les oignons en quartiers, la courgette et le poivron en gros morceaux.", None),
            ("Étale les légumes sur une plaque sans les serrer, ajoute l'ail entier, le thym, l'huile, du sel et du poivre, et mélange avec les mains.", None),
            ("Enfourne en retournant les légumes à mi-cuisson, jusqu'à ce qu'ils soient tendres et bien dorés.", 40),
            ("Arrose d'un filet de vinaigre balsamique à la sortie du four et presse l'ail confit sur les légumes.", None),
        ],
    ),
    (
        "burger-vegetarien-haricots", "Burger végétarien aux haricots",
        "Un steak de haricots rouges aux épices douces, grillé à la poêle et servi dans un bun moelleux.",
        "🍔", "etats_unis", "plat", "moyen", 25, 15, 4, ["street-food"],
        [
            ("haricots rouges cuits", 400, "g", 400, "20503"),
            ("chapelure", 60, "g", 60, "7500"),
            ("œuf", 1, "pièce", 55, "22000"),
            ("oignon rouge", 1, "pièce", 100, "20238"),
            ("gousse d'ail", 1, "pièce", 5, "11000"),
            ("paprika", 1, "càc", 2, "11049"),
            ("cumin", 1, "càc", 2, "11042"),
            ("huile d'olive", 2, "càs", 24, "17270"),
            ("pains à burger", 4, "pièce", 240, "7259"),
            ("cheddar en tranches", 4, "tranches", 80, "12726"),
            ("tomate", 1, "pièce", 120, "20047"),
            ("salade sucrine", 1, "pièce", 80, "20288"),
            ("ketchup (facultatif)", 4, "càs", 60, "11008"),
        ],
        [
            ("Égoutte bien les haricots et sèche-les dans un torchon, puis écrase-les grossièrement à la fourchette.", None),
            ("Ajoute l'oignon haché très fin, l'ail, les épices, l'œuf, la chapelure et du sel ; la pâte doit se tenir.", None),
            ("Forme quatre steaks épais et laisse-les raffermir au frais.", 15),
            ("Fais-les dorer dans l'huile à feu moyen, en les retournant délicatement ; pose le cheddar en fin de cuisson.", 10),
            ("Toaste les pains, puis monte les burgers avec la salade, la tomate en rondelles et le ketchup.", 2),
        ],
    ),
    (
        "couscous-sept-legumes", "Couscous aux sept légumes",
        "Le couscous marocain végétal : semoule fine et bouillon parfumé où mijotent sept légumes et des pois chiches.",
        "🥘", "maroc", "plat", "moyen", 30, 60, 6, ["vegan", "grande-tablee"],
        [
            ("semoule de blé moyenne", 500, "g", 500, "9610"),
            ("carottes", 3, "pièce", 300, "20009"),
            ("navets", 2, "pièce", 250, "20064"),
            ("courgettes", 2, "pièce", 400, "20020"),
            ("courge", 400, "g", 400, "20292"),
            ("chou blanc", 0.25, "pièce", 300, "20116"),
            ("tomates", 3, "pièce", 360, "20047"),
            ("oignons", 2, "pièce", 250, "20239"),
            ("pois chiches cuits", 250, "g", 250, "20507"),
            ("huile d'olive", 5, "càs", 60, "17270"),
            ("curcuma", 1, "càc", 3, "11089"),
            ("gingembre en poudre", 1, "càc", 2, None),
            ("cannelle", 1, "pincée", 1, "11025"),
            ("coriandre fraîche", 1, "bouquet", 20, "11094"),
        ],
        [
            ("Dans une grande marmite, fais revenir les oignons émincés dans la moitié de l'huile avec les épices et les tomates râpées.", 8),
            ("Ajoute les carottes et les navets coupés en gros tronçons, couvre d'eau, sale et laisse cuire.", 20),
            ("Ajoute le chou en quartiers, puis la courge et les courgettes en gros morceaux, les pois chiches et la coriandre.", 25),
            ("Pendant ce temps, arrose la semoule du même volume d'eau bouillante salée et du reste d'huile, couvre et laisse gonfler.", 10),
            ("Égraine la semoule à la fourchette, puis passe-la quelques minutes à la vapeur au-dessus du bouillon pour qu'elle soit bien aérée.", 5),
            ("Dresse la semoule en dôme, dispose les légumes autour et sers le bouillon à part.", None),
        ],
    ),
    (
        "moussaka-vegetarienne", "Moussaka végétarienne",
        "La moussaka grecque où les lentilles remplacent la viande, entre aubergines rôties et béchamel dorée.",
        "🍆", "grece", "plat", "moyen", 30, 60, 6, ["four", "batch-cooking"],
        [
            ("aubergines", 3, "pièce", 900, "20300"),
            ("lentilles vertes cuites", 400, "g", 400, "20587"),
            ("oignon", 1, "pièce", 150, "20239"),
            ("gousses d'ail", 2, "pièce", 10, "11000"),
            ("tomates pelées", 400, "g", 400, "20048"),
            ("cannelle", 1, "pincée", 1, "11025"),
            ("huile d'olive", 5, "càs", 60, "17270"),
            ("beurre", 50, "g", 50, "16400"),
            ("farine", 50, "g", 50, "9435"),
            ("lait", 50, "cl", 500, "19041"),
            ("œuf", 1, "pièce", 55, "22000"),
            ("feta", 80, "g", 80, "12066"),
        ],
        [
            ("Préchauffe le four à 200 °C. Tranche les aubergines, badigeonne-les d'huile et rôtis-les sur une plaque.", 20),
            ("Fais revenir l'oignon et l'ail, ajoute les tomates, les lentilles et la cannelle, sale et laisse épaissir.", 15),
            ("Prépare une béchamel avec le beurre, la farine et le lait, puis hors du feu ajoute l'œuf battu.", 8),
            ("Dans un plat, alterne aubergines et sauce aux lentilles, en finissant par des aubergines.", None),
            ("Nappe de béchamel, émiette la feta dessus et enfourne à 180 °C jusqu'à ce que ce soit bien doré.", 40),
            ("Laisse reposer au moins quinze minutes avant de couper, pour de belles parts.", None),
        ],
    ),
    (
        "okonomiyaki", "Okonomiyaki",
        "La galette japonaise au chou et à l'œuf, cuite à la poêle et nappée de sauce et de mayonnaise.",
        "🥬", "japon", "plat", "facile", 15, 15, 2, ["une-poele", "express"],
        [
            ("chou blanc", 300, "g", 300, "20116"),
            ("farine", 100, "g", 100, "9435"),
            ("œufs", 2, "pièce", 110, "22000"),
            ("eau", 10, "cl", 100, None),
            ("oignons nouveaux", 3, "pièce", 45, "20323"),
            ("gingembre frais", 10, "g", 10, "11074"),
            ("huile d'arachide", 2, "càs", 24, "17040"),
            ("sauce soja", 1, "càs", 15, "11104"),
            ("ketchup", 2, "càs", 30, "11008"),
            ("mayonnaise", 2, "càs", 30, "11054"),
            ("algue nori (facultatif)", 1, "feuille", 3, "20987"),
        ],
        [
            ("Émince le chou très finement, hache les oignons nouveaux et râpe le gingembre.", None),
            ("Fouette la farine, les œufs et l'eau, puis ajoute le chou, les oignons et le gingembre ; la pâte doit juste enrober le chou.", None),
            ("Verse la moitié de la pâte dans une poêle huilée bien chaude, en formant une galette épaisse.", None),
            ("Laisse dorer à feu moyen, retourne à l'aide d'une assiette et poursuis la cuisson.", 7),
            ("Mélange la sauce soja et le ketchup, nappe la galette, trace des traits de mayonnaise et parsème de nori émietté.", None),
        ],
    ),
]
