# Starter recipes, theme "viandes": meat and poultry main dishes from many
# cuisines. Same tuple shape as scripts/seed-world-recipes.py.

R = [
    (
        "boeuf-bourguignon", "Bœuf bourguignon",
        "Le grand mijoté de Bourgogne : bœuf fondant au vin rouge, lardons, champignons et carottes.",
        "🍷", "france", "plat", "moyen", 30, 180, 6, ["mijote", "hiver", "batch-cooking"],
        [
            ("paleron de bœuf", 1.2, "kg", 1200, "6270"),
            ("vin rouge", 75, "cl", 750, "5214"),
            ("lardons fumés", 150, "g", 150, "28720"),
            ("champignons de Paris", 250, "g", 250, "20056"),
            ("carottes", 3, "pièce", 300, "20009"),
            ("oignons", 2, "pièce", 200, "20239"),
            ("gousses d'ail", 2, "pièce", 10, "11000"),
            ("farine de blé", 2, "càs", 20, "9435"),
            ("beurre", 30, "g", 30, "16400"),
            ("thym frais", 3, "brins", 3, "11070"),
            ("feuilles de laurier", 2, "pièce", 1, "11053"),
            ("poivre", 1, "pincée", 1, "11015"),
        ],
        [
            ("Coupe le bœuf en gros cubes de 5 cm et sèche-les bien avec du papier absorbant.", None),
            ("Fais dorer les lardons dans une cocotte, retire-les, puis saisis la viande par petites quantités dans leur gras.", 15),
            ("Ajoute les oignons émincés et les carottes en rondelles, saupoudre de farine et remue une minute.", 5),
            ("Verse le vin rouge, ajoute l'ail, le thym, le laurier et les lardons, poivre et porte à frémissement.", None),
            ("Couvre et laisse mijoter à feu très doux jusqu'à ce que la viande se coupe à la cuillère.", 150),
            ("Fais sauter les champignons au beurre et ajoute-les en fin de cuisson ; rectifie l'assaisonnement.", 10),
        ],
    ),
    (
        "coq-au-vin", "Coq au vin",
        "Des morceaux de poulet mijotés au vin rouge avec lardons, champignons et petits oignons.",
        "🐓", "france", "plat", "moyen", 25, 90, 6, ["mijote", "hiver"],
        [
            ("cuisses de poulet", 6, "pièce", 1500, "36002"),
            ("vin rouge", 75, "cl", 750, "5214"),
            ("lardons fumés", 150, "g", 150, "28720"),
            ("champignons de Paris", 250, "g", 250, "20056"),
            ("petits oignons", 12, "pièce", 250, "20239"),
            ("gousses d'ail", 2, "pièce", 10, "11000"),
            ("farine de blé", 2, "càs", 20, "9435"),
            ("beurre", 30, "g", 30, "16400"),
            ("thym frais", 3, "brins", 3, "11070"),
            ("persil plat (facultatif)", 1, "bouquet", 15, "11014"),
        ],
        [
            ("Coupe les cuisses en deux au niveau de l'articulation, sale et poivre.", None),
            ("Fais dorer les lardons et les petits oignons dans le beurre, puis réserve-les.", 8),
            ("Dans la même cocotte, colore les morceaux de poulet sur toutes les faces, saupoudre de farine.", 10),
            ("Mouille avec le vin rouge, ajoute l'ail, le thym, les lardons et les oignons, couvre.", None),
            ("Laisse mijoter à feu doux ; ajoute les champignons émincés pour les 20 dernières minutes.", 70),
            ("Parsème de persil haché et sers avec des pommes de terre vapeur ou des pâtes fraîches.", None),
        ],
    ),
    (
        "poulet-roti-herbes", "Poulet rôti aux herbes",
        "Un poulet entier doré au four, parfumé au beurre d'herbes, à l'ail et au citron.",
        "🍗", "france", "plat", "facile", 15, 80, 5, ["four", "classique"],
        [
            ("poulet entier", 1, "pièce", 1600, "36016"),
            ("beurre mou", 50, "g", 50, "16400"),
            ("thym frais", 4, "brins", 4, "11070"),
            ("romarin frais", 2, "brins", 3, "11068"),
            ("gousses d'ail", 6, "pièce", 30, "11000"),
            ("citron", 1, "pièce", 100, "13009"),
            ("huile d'olive", 1, "càs", 12, "17270"),
            ("poivre", 1, "pincée", 1, "11015"),
        ],
        [
            ("Sors le poulet du réfrigérateur 30 minutes avant et préchauffe le four à 210 °C.", None),
            ("Mélange le beurre mou avec les feuilles de thym et le romarin hachés, sale et poivre.", None),
            ("Glisse une partie du beurre sous la peau des filets et étale le reste sur tout le poulet.", None),
            ("Place le citron coupé en deux dans la cavité et les gousses d'ail en chemise autour, arrose d'huile.", None),
            ("Enfourne en arrosant avec le jus toutes les 20 minutes, jusqu'à ce que le jus de la cuisse soit clair.", 80),
            ("Laisse reposer 10 minutes sous une feuille de papier aluminium avant de découper.", 10),
        ],
    ),
    (
        "poulet-basquaise", "Poulet basquaise",
        "Le poulet du Pays basque mijoté avec poivrons, tomates, jambon cru et une pointe de piment.",
        "🫑", "france", "plat", "facile", 20, 60, 4, ["mijote", "ete"],
        [
            ("cuisses de poulet", 4, "pièce", 1000, "36002"),
            ("poivrons rouges", 2, "pièce", 300, "20087"),
            ("poivrons verts", 2, "pièce", 300, "20085"),
            ("tomates", 5, "pièce", 600, "20047"),
            ("oignons", 2, "pièce", 200, "20239"),
            ("jambon cru", 2, "tranche", 60, "28800"),
            ("gousses d'ail", 3, "pièce", 15, "11000"),
            ("vin blanc sec", 10, "cl", 100, "5215"),
            ("huile d'olive", 3, "càs", 36, "17270"),
            ("piment d'Espelette", 1, "càc", 2, None),
        ],
        [
            ("Émince les oignons et les poivrons en lanières, coupe les tomates en dés et le jambon en morceaux.", None),
            ("Fais dorer les morceaux de poulet dans l'huile d'olive, puis réserve-les.", 10),
            ("Dans la même cocotte, fais fondre les oignons et les poivrons avec le jambon.", 10),
            ("Ajoute les tomates, l'ail écrasé, le vin blanc et le piment, puis remets le poulet.", None),
            ("Couvre et laisse mijoter jusqu'à ce que la viande soit tendre et la sauce bien réduite.", 40),
        ],
    ),
    (
        "roti-porc-miel-moutarde", "Rôti de porc miel-moutarde",
        "Un rôti de porc laqué au miel et à la moutarde à l'ancienne, entouré de pommes de terre fondantes.",
        "🍯", "france", "plat", "facile", 15, 70, 6, ["four", "dimanche"],
        [
            ("rôti de porc", 1.2, "kg", 1200, "28300"),
            ("miel", 3, "càs", 60, "31008"),
            ("moutarde à l'ancienne", 3, "càs", 45, "11021"),
            ("pommes de terre", 1, "kg", 1000, "4008"),
            ("oignons", 2, "pièce", 200, "20239"),
            ("gousses d'ail", 4, "pièce", 20, "11000"),
            ("thym frais", 4, "brins", 4, "11070"),
            ("huile d'olive", 2, "càs", 24, "17270"),
            ("poivre", 1, "pincée", 1, "11015"),
        ],
        [
            ("Préchauffe le four à 190 °C et mélange le miel avec la moutarde, sel et poivre.", None),
            ("Badigeonne généreusement le rôti de ce mélange et pose-le au centre d'un plat.", None),
            ("Entoure-le des pommes de terre en quartiers, des oignons en quartiers et de l'ail, arrose d'huile et parsème de thym.", None),
            ("Enfourne en arrosant le rôti de son jus toutes les 20 minutes.", 70),
            ("Laisse reposer la viande 10 minutes avant de la trancher finement.", 10),
        ],
    ),
    (
        "navarin-agneau", "Navarin d'agneau",
        "Un ragoût d'agneau printanier aux carottes, navets, pommes de terre nouvelles et petits pois.",
        "🥕", "france", "plat", "moyen", 30, 105, 6, ["mijote", "printemps"],
        [
            ("épaule d'agneau en morceaux", 1.2, "kg", 1200, "21504"),
            ("carottes", 4, "pièce", 400, "20009"),
            ("navets", 4, "pièce", 400, "20321"),
            ("pommes de terre nouvelles", 500, "g", 500, "4023"),
            ("petits pois", 200, "g", 200, "20326"),
            ("oignons", 2, "pièce", 200, "20239"),
            ("concentré de tomate", 2, "càs", 30, "20068"),
            ("farine de blé", 1, "càs", 10, "9435"),
            ("gousses d'ail", 2, "pièce", 10, "11000"),
            ("bouillon de volaille", 60, "cl", 600, "25947"),
            ("huile d'olive", 2, "càs", 24, "17270"),
            ("thym frais", 3, "brins", 3, "11070"),
        ],
        [
            ("Fais dorer les morceaux d'agneau dans l'huile, en plusieurs fois, dans une cocotte.", 12),
            ("Ajoute les oignons émincés, saupoudre de farine, puis incorpore le concentré de tomate.", 3),
            ("Verse le bouillon, ajoute l'ail et le thym, sale, poivre, couvre et laisse mijoter.", 60),
            ("Ajoute les carottes et les navets en tronçons et les pommes de terre entières.", 30),
            ("Termine avec les petits pois et poursuis la cuisson à couvert jusqu'à ce qu'ils soient tendres.", 15),
        ],
    ),
    (
        "spaghetti-bolognaise", "Spaghetti bolognaise",
        "Des spaghetti nappés d'une sauce tomate à la viande hachée longuement mijotée.",
        "🍝", "italie", "plat", "facile", 20, 75, 4, ["reconfort", "batch-cooking"],
        [
            ("spaghetti", 400, "g", 400, "9810"),
            ("bœuf haché", 400, "g", 400, "6252"),
            ("tomates pelées en boîte", 800, "g", 800, "20169"),
            ("concentré de tomate", 1, "càs", 15, "20068"),
            ("carotte", 1, "pièce", 100, "20009"),
            ("branche de céleri", 1, "pièce", 60, "20023"),
            ("oignon", 1, "pièce", 100, "20239"),
            ("vin rouge", 10, "cl", 100, "5214"),
            ("huile d'olive", 3, "càs", 36, "17270"),
            ("parmesan râpé (facultatif)", 40, "g", 40, "12120"),
        ],
        [
            ("Hache finement l'oignon, la carotte et le céleri, puis fais-les revenir dans l'huile.", 8),
            ("Ajoute la viande et fais-la dorer en l'émiettant à la cuillère.", 8),
            ("Verse le vin rouge et laisse-le s'évaporer, puis ajoute les tomates et le concentré.", 3),
            ("Sale, poivre, couvre à moitié et laisse mijoter à feu doux en remuant de temps en temps.", 60),
            ("Fais cuire les spaghetti al dente, égoutte-les et mélange-les à la sauce ; sers avec du parmesan.", 10),
        ],
    ),
    (
        "spaghetti-carbonara", "Spaghetti carbonara",
        "La recette romaine : guanciale croustillant, jaunes d'œufs, fromage et beaucoup de poivre, sans crème.",
        "🥓", "italie", "plat", "moyen", 10, 15, 4, ["express"],
        [
            ("spaghetti", 400, "g", 400, "9810"),
            ("guanciale ou lardons fumés", 150, "g", 150, "28720"),
            ("jaunes d'œufs", 4, "pièce", 72, "22000"),
            ("œuf entier", 1, "pièce", 55, "22000"),
            ("pecorino ou parmesan râpé", 60, "g", 60, "12120"),
            ("poivre noir", 1, "càc", 3, "11015"),
        ],
        [
            ("Mets à bouillir une grande casserole d'eau salée et fais cuire les spaghetti.", 10),
            ("Pendant ce temps, fais revenir le guanciale coupé en bâtonnets à sec jusqu'à ce qu'il soit croustillant.", 6),
            ("Fouette les jaunes, l'œuf entier, le fromage et le poivre dans un grand saladier.", None),
            ("Égoutte les pâtes en gardant une louche d'eau de cuisson et verse-les dans la poêle hors du feu.", None),
            ("Ajoute le mélange aux œufs et un peu d'eau de cuisson, remue vivement pour obtenir une sauce crémeuse ; sers aussitôt.", 1),
        ],
    ),
    (
        "chili-con-carne", "Chili con carne",
        "Le mijoté texan-mexicain de bœuf haché, haricots rouges, tomates et épices douces.",
        "🌶️", "mexique", "plat", "facile", 15, 60, 6, ["batch-cooking", "hiver"],
        [
            ("bœuf haché", 600, "g", 600, "6252"),
            ("haricots rouges cuits", 500, "g", 500, "20503"),
            ("tomates concassées en boîte", 800, "g", 800, "20169"),
            ("poivron rouge", 1, "pièce", 150, "20087"),
            ("oignons", 2, "pièce", 200, "20239"),
            ("gousses d'ail", 3, "pièce", 15, "11000"),
            ("cumin moulu", 2, "càc", 4, "11042"),
            ("paprika", 2, "càc", 4, "11049"),
            ("piment de Cayenne", 1, "pincée", 1, "11088"),
            ("huile de tournesol", 2, "càs", 24, "17440"),
            ("riz blanc", 400, "g", 400, "9100"),
        ],
        [
            ("Fais revenir les oignons et le poivron en dés dans l'huile jusqu'à ce qu'ils soient tendres.", 8),
            ("Ajoute l'ail, le cumin, le paprika et le piment, remue une minute pour torréfier les épices.", 1),
            ("Incorpore la viande et fais-la dorer en l'émiettant.", 8),
            ("Verse les tomates, sale et laisse mijoter à couvert en remuant de temps en temps.", 35),
            ("Ajoute les haricots rouges égouttés et poursuis la cuisson à découvert.", 10),
            ("Fais cuire le riz et sers le chili dessus, avec de la coriandre ou de la crème si tu aimes.", None),
        ],
    ),
    (
        "burger-maison", "Burger maison",
        "Un burger généreux au steak haché, cheddar fondant, crudités et sauce maison.",
        "🍔", "etats_unis", "plat", "facile", 20, 10, 4, ["express", "partage"],
        [
            ("pains à burger", 4, "pièce", 320, "7259"),
            ("bœuf haché", 600, "g", 600, "6256"),
            ("cheddar", 4, "tranche", 80, "12726"),
            ("tomate", 1, "pièce", 120, "20047"),
            ("oignon rouge", 1, "pièce", 100, "20238"),
            ("feuilles de salade", 4, "pièce", 40, "20288"),
            ("cornichons", 4, "pièce", 40, "11004"),
            ("ketchup", 3, "càs", 45, "11008"),
            ("moutarde", 1, "càs", 15, "11013"),
            ("poivre", 1, "pincée", 1, "11015"),
        ],
        [
            ("Façonne 4 steaks un peu plus larges que les pains, sans trop tasser la viande, et creuse légèrement le centre.", None),
            ("Mélange le ketchup et la moutarde, émince l'oignon, la tomate et les cornichons.", None),
            ("Saisis les steaks dans une poêle très chaude, sale et poivre, puis retourne-les.", 4),
            ("Pose le cheddar sur les steaks et couvre une minute pour le faire fondre ; toaste les pains côté mie.", 2),
            ("Monte les burgers : sauce, salade, steak, tomate, oignon, cornichons, puis le chapeau.", None),
        ],
    ),
    (
        "poulet-teriyaki", "Poulet teriyaki",
        "Des hauts de cuisse laqués dans une sauce sucrée-salée à la japonaise, servis sur du riz.",
        "🍚", "japon", "plat", "facile", 10, 20, 4, ["express"],
        [
            ("hauts de cuisse de poulet désossés", 700, "g", 700, "36019"),
            ("sauce soja", 6, "càs", 90, "11104"),
            ("mirin", 4, "càs", 60, None),
            ("miel", 2, "càs", 40, "31008"),
            ("gingembre frais", 1, "morceau", 15, "11074"),
            ("gousse d'ail", 1, "pièce", 5, "11000"),
            ("huile de tournesol", 1, "càs", 12, "17440"),
            ("graines de sésame (facultatif)", 1, "càs", 8, "15038"),
            ("riz blanc", 320, "g", 320, "9100"),
        ],
        [
            ("Fais cuire le riz selon les indications du paquet.", 15),
            ("Mélange la sauce soja, le mirin, le miel, le gingembre râpé et l'ail écrasé.", None),
            ("Fais dorer le poulet côté peau dans l'huile, puis retourne-le et poursuis la cuisson.", 12),
            ("Verse la sauce et laisse-la réduire en arrosant le poulet jusqu'à ce qu'il soit bien laqué.", 5),
            ("Tranche le poulet, parsème de sésame et sers sur le riz avec le reste de sauce.", None),
        ],
    ),
    (
        "boeuf-lok-lak", "Bœuf lok lak",
        "Le sauté de bœuf cambodgien au poivre, servi avec une sauce citron vert-poivre et des crudités.",
        "🥩", "autre", "plat", "facile", 20, 10, 4, ["express", "wok"],
        [
            ("rumsteck de bœuf", 600, "g", 600, "6206"),
            ("sauce soja", 3, "càs", 45, "11104"),
            ("sauce de poisson", 1, "càs", 15, "11194"),
            ("sucre", 1, "càs", 12, "31016"),
            ("gousses d'ail", 3, "pièce", 15, "11000"),
            ("poivre noir moulu", 2, "càc", 5, "11015"),
            ("citrons verts", 2, "pièce", 120, "13067"),
            ("tomates", 2, "pièce", 240, "20047"),
            ("oignon rouge", 1, "pièce", 100, "20238"),
            ("feuilles de salade", 8, "pièce", 80, "20288"),
            ("huile de tournesol", 2, "càs", 24, "17440"),
            ("riz thaï", 320, "g", 320, "9119"),
        ],
        [
            ("Coupe le bœuf en cubes de 2 cm et fais-le mariner avec la sauce soja, la sauce de poisson, le sucre et l'ail écrasé.", 15),
            ("Fais cuire le riz et dispose la salade, les tomates en rondelles et l'oignon émincé sur les assiettes.", 15),
            ("Mélange le jus des citrons verts avec le poivre et une pincée de sel pour la sauce.", None),
            ("Saisis le bœuf à feu très vif dans l'huile, en le gardant rosé à cœur.", 4),
            ("Dépose la viande sur les crudités et sers avec le riz et la sauce au poivre à part.", None),
        ],
    ),
    (
        "poulet-curry-vert", "Poulet au curry vert",
        "Un curry thaï au lait de coco, parfumé au basilic, avec du poulet tendre et des légumes croquants.",
        "🥥", "thailande", "plat", "facile", 15, 20, 4, ["express", "sans-gluten"],
        [
            ("filets de poulet", 600, "g", 600, "36017"),
            ("pâte de curry vert", 2, "càs", 30, None),
            ("lait de coco", 40, "cl", 400, "18041"),
            ("courgette", 1, "pièce", 200, "20020"),
            ("poivron rouge", 1, "pièce", 150, "20087"),
            ("sauce de poisson", 1, "càs", 15, "11194"),
            ("sucre", 1, "càc", 5, "31016"),
            ("basilic frais", 1, "bouquet", 15, "11033"),
            ("huile de tournesol", 1, "càs", 12, "17440"),
            ("riz thaï", 320, "g", 320, "9119"),
        ],
        [
            ("Fais cuire le riz et coupe le poulet en lamelles, la courgette et le poivron en morceaux.", 15),
            ("Fais revenir la pâte de curry dans l'huile avec quelques cuillères de lait de coco jusqu'à ce qu'elle embaume.", 2),
            ("Ajoute le poulet et enrobe-le bien de pâte.", 4),
            ("Verse le reste du lait de coco, la sauce de poisson et le sucre, puis les légumes.", None),
            ("Laisse frémir jusqu'à ce que le poulet soit cuit, ajoute le basilic et sers avec le riz.", 10),
        ],
    ),
    (
        "porc-ananas-aigre-doux", "Porc à l'ananas aigre-doux",
        "Des lamelles de porc sautées avec ananas et poivrons dans une sauce aigre-douce brillante.",
        "🍍", "chine", "plat", "facile", 20, 15, 4, ["wok", "express"],
        [
            ("filet mignon ou longe de porc", 500, "g", 500, "28003"),
            ("ananas frais", 300, "g", 300, "13002"),
            ("poivron vert", 1, "pièce", 150, "20085"),
            ("poivron rouge", 1, "pièce", 150, "20087"),
            ("oignon", 1, "pièce", 100, "20239"),
            ("sauce soja", 3, "càs", 45, "11104"),
            ("ketchup", 3, "càs", 45, "11008"),
            ("vinaigre", 2, "càs", 30, "11018"),
            ("sucre", 2, "càs", 24, "31016"),
            ("fécule de maïs", 2, "càs", 20, "9510"),
            ("huile de tournesol", 3, "càs", 36, "17440"),
            ("riz blanc", 320, "g", 320, "9100"),
        ],
        [
            ("Coupe le porc en lamelles et enrobe-le d'une cuillère de sauce soja et d'une cuillère de fécule.", 10),
            ("Mélange le ketchup, le vinaigre, le sucre, le reste de sauce soja et de fécule avec 10 cl d'eau.", None),
            ("Saisis le porc dans l'huile bien chaude au wok, puis réserve-le.", 5),
            ("Fais sauter l'oignon et les poivrons en morceaux, puis ajoute l'ananas en cubes.", 4),
            ("Remets le porc, verse la sauce et remue jusqu'à ce qu'elle nappe ; sers avec le riz.", 2),
        ],
    ),
    (
        "jerk-chicken", "Jerk chicken",
        "Le poulet jamaïcain mariné au piment, au thym et aux épices, grillé jusqu'à être bien caramélisé.",
        "🔥", "antilles", "plat", "moyen", 20, 40, 4, ["barbecue", "ete", "marinade"],
        [
            ("pilons et hauts de cuisse de poulet", 1.2, "kg", 1200, "36022"),
            ("oignons nouveaux", 4, "pièce", 80, "20323"),
            ("piment antillais", 1, "pièce", 10, "20151"),
            ("gousses d'ail", 3, "pièce", 15, "11000"),
            ("gingembre frais", 1, "morceau", 15, "11074"),
            ("citron vert", 1, "pièce", 60, "13067"),
            ("sauce soja", 3, "càs", 45, "11104"),
            ("sucre roux", 1, "càs", 12, "31017"),
            ("quatre-épices", 1, "càc", 2, "11056"),
            ("thym frais", 4, "brins", 4, "11070"),
            ("huile de tournesol", 2, "càs", 24, "17440"),
        ],
        [
            ("Mixe les oignons nouveaux, le piment épépiné, l'ail, le gingembre, le jus du citron vert, la sauce soja, le sucre, les épices, le thym et l'huile.", None),
            ("Entaille la viande, enrobe-la de marinade et laisse reposer au frais, idéalement une nuit.", 240),
            ("Préchauffe le four à 200 °C ou allume le barbecue.", None),
            ("Fais cuire le poulet en le retournant à mi-cuisson, jusqu'à ce qu'il soit bien doré et cuit à cœur.", 40),
            ("Sers avec du riz aux haricots rouges ou des bananes plantain poêlées.", None),
        ],
    ),
    (
        "tajine-agneau-abricots", "Tajine d'agneau aux abricots",
        "Un tajine marocain d'agneau fondant, sucré-salé aux abricots secs, miel et amandes grillées.",
        "🫕", "maroc", "plat", "moyen", 20, 120, 6, ["mijote", "sucre-sale"],
        [
            ("épaule d'agneau en morceaux", 1.2, "kg", 1200, "21504"),
            ("abricots secs", 200, "g", 200, "13001"),
            ("oignons", 3, "pièce", 300, "20239"),
            ("gousses d'ail", 2, "pièce", 10, "11000"),
            ("gingembre en poudre", 1, "càc", 2, "11006"),
            ("cannelle en poudre", 1, "càc", 3, "11025"),
            ("miel", 2, "càs", 40, "31008"),
            ("amandes émondées", 60, "g", 60, "15041"),
            ("huile d'olive", 3, "càs", 36, "17270"),
            ("coriandre fraîche (facultatif)", 1, "bouquet", 15, "11094"),
        ],
        [
            ("Fais dorer l'agneau dans l'huile avec les oignons émincés, l'ail, le gingembre et la cannelle.", 10),
            ("Couvre à hauteur d'eau, sale, poivre et laisse mijoter à couvert à feu doux.", 90),
            ("Ajoute les abricots et le miel, puis poursuis la cuisson à découvert pour réduire la sauce.", 25),
            ("Fais griller les amandes à sec dans une poêle.", 4),
            ("Sers parsemé d'amandes et de coriandre, avec de la semoule ou du pain.", None),
        ],
    ),
    (
        "kefta-grillees", "Kefta grillées",
        "Des brochettes de viande hachée aux herbes et aux épices, grillées et servies avec une sauce au yaourt.",
        "🍢", "liban", "plat", "facile", 25, 10, 4, ["barbecue", "ete"],
        [
            ("bœuf ou agneau haché", 600, "g", 600, "6256"),
            ("oignon", 1, "pièce", 100, "20239"),
            ("persil plat", 1, "bouquet", 30, "11014"),
            ("menthe fraîche", 0.5, "bouquet", 10, "11027"),
            ("cumin moulu", 1, "càc", 2, "11042"),
            ("paprika", 1, "càc", 2, "11049"),
            ("cannelle en poudre", 1, "pincée", 1, "11025"),
            ("yaourt nature", 250, "g", 250, "19593"),
            ("gousse d'ail", 1, "pièce", 5, "11000"),
            ("pains pita", 4, "pièce", 280, "7180"),
        ],
        [
            ("Râpe l'oignon et presse-le pour retirer son jus, hache finement le persil et la menthe.", None),
            ("Mélange la viande avec l'oignon, les herbes, les épices, du sel et du poivre ; pétris une minute.", None),
            ("Façonne des boudins allongés autour de brochettes et laisse-les raffermir au frais.", 15),
            ("Mélange le yaourt avec l'ail écrasé, une pincée de sel et un peu de menthe.", None),
            ("Grille les kefta en les retournant jusqu'à ce qu'elles soient dorées, et sers avec les pitas et la sauce.", 10),
        ],
    ),
    (
        "gyros-poulet", "Gyros de poulet",
        "Le sandwich grec de poulet mariné aux épices, roulé dans une pita avec tzatziki et crudités.",
        "🥙", "grece", "plat", "facile", 25, 15, 4, ["street-food", "ete"],
        [
            ("hauts de cuisse de poulet désossés", 600, "g", 600, "36019"),
            ("yaourt à la grecque", 300, "g", 300, "19550"),
            ("citron", 1, "pièce", 100, "13009"),
            ("gousses d'ail", 3, "pièce", 15, "11000"),
            ("origan séché", 2, "càc", 2, "11035"),
            ("paprika", 1, "càc", 2, "11049"),
            ("huile d'olive", 3, "càs", 36, "17270"),
            ("concombre", 0.5, "pièce", 150, "20019"),
            ("tomates", 2, "pièce", 240, "20047"),
            ("oignon rouge", 1, "pièce", 100, "20238"),
            ("pains pita", 4, "pièce", 280, "7180"),
        ],
        [
            ("Mélange 100 g de yaourt avec le jus de citron, 2 gousses d'ail, l'origan, le paprika et l'huile, puis enrobe le poulet.", 30),
            ("Pour le tzatziki, râpe le concombre, presse-le et mélange-le au reste du yaourt avec l'ail restant.", None),
            ("Fais griller le poulet dans une poêle bien chaude jusqu'à ce qu'il soit doré, puis émince-le.", 12),
            ("Réchauffe les pitas quelques secondes à la poêle.", 2),
            ("Garnis chaque pita de poulet, de tomates, d'oignon rouge et de tzatziki, puis roule-la.", None),
        ],
    ),
    (
        "butter-chicken", "Butter chicken",
        "Le poulet au beurre du nord de l'Inde, mariné au yaourt et mijoté dans une sauce tomate crémeuse.",
        "🍛", "inde", "plat", "moyen", 20, 35, 4, ["reconfort", "sans-gluten"],
        [
            ("hauts de cuisse de poulet désossés", 700, "g", 700, "36019"),
            ("yaourt nature", 150, "g", 150, "19593"),
            ("purée de tomates", 400, "g", 400, "20170"),
            ("beurre", 50, "g", 50, "16400"),
            ("crème liquide", 15, "cl", 150, "19415"),
            ("oignon", 1, "pièce", 100, "20239"),
            ("gousses d'ail", 3, "pièce", 15, "11000"),
            ("gingembre frais", 1, "morceau", 15, "11074"),
            ("garam masala", 2, "càc", 4, None),
            ("paprika", 1, "càc", 2, "11049"),
            ("riz basmati", 320, "g", 320, "9119"),
        ],
        [
            ("Fais mariner le poulet en morceaux avec le yaourt, la moitié du garam masala, le paprika et du sel.", 30),
            ("Fais dorer le poulet dans la moitié du beurre dans une sauteuse, puis réserve-le.", 8),
            ("Fais fondre l'oignon avec le reste du beurre, ajoute l'ail et le gingembre râpés.", 6),
            ("Verse la purée de tomates et le reste du garam masala, laisse réduire à feu doux.", 10),
            ("Ajoute la crème et le poulet, laisse mijoter pour finir la cuisson ; sers avec le riz basmati.", 10),
        ],
    ),
    (
        "chou-farci-golabki", "Chou farci à la polonaise",
        "Des feuilles de chou roulées autour d'une farce de porc et de riz, mijotées en sauce tomate, comme en Pologne.",
        "🥬", "europe_est", "plat", "moyen", 40, 60, 6, ["four", "hiver", "batch-cooking"],
        [
            ("chou blanc", 1, "pièce", 1200, "20116"),
            ("porc haché", 500, "g", 500, "28001"),
            ("riz blanc", 120, "g", 120, "9100"),
            ("oignons", 2, "pièce", 200, "20239"),
            ("beurre", 20, "g", 20, "16400"),
            ("coulis de tomate", 500, "g", 500, "20170"),
            ("crème fraîche épaisse (facultatif)", 10, "cl", 100, "19410"),
            ("aneth frais (facultatif)", 1, "bouquet", 10, "11093"),
            ("poivre", 1, "pincée", 1, "11015"),
        ],
        [
            ("Blanchis le chou entier dans l'eau bouillante et détache une douzaine de feuilles au fur et à mesure qu'elles s'assouplissent.", 10),
            ("Fais cuire le riz 10 minutes à l'eau, égoutte-le ; fais fondre les oignons hachés dans le beurre.", 10),
            ("Mélange le porc, le riz, les oignons, du sel et du poivre.", None),
            ("Retire la grosse côte des feuilles, garnis-les de farce et roule-les en repliant les bords.", None),
            ("Range-les serrés dans un plat, nappe de coulis allongé de 20 cl d'eau, couvre et enfourne à 180 °C.", 50),
            ("Sers avec une cuillère de crème et un peu d'aneth.", None),
        ],
    ),
]
