# Generates supabase/migrations/202609291230_more_starter_recipes.sql from the
# themed recipe lists in scripts/recipes/*.py (same tuple shape as
# scripts/seed-world-recipes.py): sauces, soups and starters, vegetarian
# mains, meat, fish, desserts, brunch and apéro. Validates every value first.
import glob
import os
import re
import runpy

OUT = "supabase/migrations/202609291230_more_starter_recipes.sql"

CUISINES = set("""france italie espagne portugal grece europe_est turquie liban
israel maroc algerie tunisie afrique_ouest etats_unis mexique antilles
amerique_sud inde chine japon coree vietnam thailande autre""".split())
CATEGORIES = set("""kemia petit_dej entree soupe salade plat accompagnement
dessert pain boisson sauce""".split())
DIFFICULTIES = {"facile", "moyen", "difficile"}
# Tone guard (CLAUDE.md): no diet culture, no religious or festive references.
FORBIDDEN = re.compile(
    r"\b(calories?|kcal|minceur|l[ée]g[èe]re?s?\b|healthy|culpabilit|ramadan|"
    r"chabbat|shabbat|no[ëe]l|p[âa]ques|a[ïi]d\b|hanouk|diwali|halal|casher)",
    re.I,
)


def esc(s):
    return s.replace("'", "''")


def arr(values):
    if not values:
        return "'{}'"
    return "array[" + ",".join(f"'{esc(v)}'" for v in values) + "]"


def num(value):
    return str(value).rstrip("0").rstrip(".") if isinstance(value, float) else str(value)


def load():
    recipes = []
    for path in sorted(glob.glob("scripts/recipes/*.py")):
        for recipe in runpy.run_path(path)["R"]:
            recipes.append((os.path.basename(path), recipe))
    return recipes


def validate(recipes, existing):
    errors = []
    seen = set(existing)
    for source, r in recipes:
        (slug, title, desc, icon, cuisine, cat, diff, prep, cook, servings,
         tags, ingredients, steps) = r
        where = f"{source}:{slug}"
        if not re.fullmatch(r"[a-z0-9]+(-[a-z0-9]+)*", slug):
            errors.append(f"{where}: bad slug")
        if slug in seen:
            errors.append(f"{where}: duplicate slug")
        seen.add(slug)
        if cuisine not in CUISINES:
            errors.append(f"{where}: cuisine {cuisine}")
        if cat not in CATEGORIES:
            errors.append(f"{where}: category {cat}")
        if diff not in DIFFICULTIES:
            errors.append(f"{where}: difficulty {diff}")
        if not (0 <= prep <= 600 and 0 <= cook <= 1440 and 1 <= servings <= 24):
            errors.append(f"{where}: time or servings out of range")
        if not (1 <= len(ingredients) <= 30 and 1 <= len(steps) <= 25):
            errors.append(f"{where}: ingredient or step count")
        texts = [title, desc] + [s[0] for s in steps]
        for text in texts:
            if FORBIDDEN.search(text):
                errors.append(f"{where}: tone « {FORBIDDEN.search(text).group(0)} »")
        for label, qty, unit, grams, code in ingredients:
            if not (0 < grams <= 20000):
                errors.append(f"{where}: grams {label}")
            if len(label) > 120:
                errors.append(f"{where}: long label")
        for text, minutes in steps:
            if not (3 <= len(text) <= 600):
                errors.append(f"{where}: step length")
            if minutes is not None and not (1 <= minutes <= 720):
                errors.append(f"{where}: step minutes")
    return errors


def emit(recipes):
    lines = [
        "-- Session 20 catalogue: about 140 more starter recipes (sauces, soups",
        "-- and starters, vegetarian mains, meat, fish, desserts, brunch and",
        "-- apéro), generated by scripts/seed-more-recipes.py from",
        "-- scripts/recipes/*.py. Original texts; ingredients pinned to Ciqual.",
        "-- Idempotent on slug. Apply after 202609291200 (cuisines, « sauce »).",
    ]
    slugs = []
    for _, (slug, title, desc, icon, cuisine, cat, diff, prep, cook, servings,
            tags, ingredients, steps) in recipes:
        slugs.append(slug)
        ing_rows = []
        for pos, (label, qty, unit, grams, code) in enumerate(ingredients):
            food = (
                f"(select id from public.foods where source = 'ciqual' and external_id = '{code}')"
                if code else "null"
            )
            ing_rows.append(
                f"((select id from r), {pos}, {food}, {num(qty)}, '{esc(unit)}', {num(grams)}, '{esc(label)}')"
            )
        step_rows = [
            f"((select id from r), {pos}, '{esc(text)}', {minutes * 60 if minutes else 'null::int'})"
            for pos, (text, minutes) in enumerate(steps)
        ]
        ing_sql = ",\n    ".join(ing_rows)
        step_sql = ",\n  ".join(step_rows)
        lines.append(f"""
with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, '{esc(title)}', '{slug}', '{esc(desc)}', '{icon}', '{cuisine}', '{cat}', '{diff}',
     {prep}, {cook}, {servings}, {arr(tags)}, 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    {ing_sql}
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  {step_sql}
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);""")
    slug_list = ", ".join(f"'{s}'" for s in sorted(slugs))
    # Nutrition only when foods with an energy value cover >= 90 % of grams.
    lines.append(f"""
update public.recipes r
set nutrition_per_serving = case
  when (
    select coalesce(sum(i.grams) filter (where f.per_100g ? 'kcal'), 0)
      >= 0.9 * nullif(sum(i.grams), 0)
    from public.recipe_ingredients i
    left join public.foods f on f.id = i.food_id
    where i.recipe_id = r.id
  ) then coalesce(public.compute_recipe_nutrition(r.id), '{{}}'::jsonb)
  else '{{}}'::jsonb
end
where r.author_id is null and r.slug in ({slug_list});""")
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    existing = []
    for seed in ("src/db/seed/recipes/recipes.sql",
                 "supabase/migrations/202609291220_world_starter_recipes.sql"):
        existing += re.findall(r"\(null, '(?:[^']|'')*', '([a-z0-9-]+)'", open(seed).read())
    assert len(existing) == 61, len(existing)
    recipes = load()
    problems = validate(recipes, existing)
    if problems:
        print("\n".join(problems))
        raise SystemExit(1)
    emit(recipes)
    print(f"{len(recipes)} recipes written to {OUT}")
