-- Session 19 (ADR-032): a diverse starter catalogue, generated by
-- scripts/seed-world-recipes.py. Adds recipes from every continent and
-- for every table next to the 35 original ones, which stay untouched.
-- Original texts; ingredients pinned to Ciqual foods for the nutrition.
-- Idempotent on slug. Apply after 202609291200 (world cuisines).

with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, 'Quiche lorraine', 'quiche-lorraine', 'La tarte salée de Lorraine : lardons fumés, crème et œufs sur une pâte brisée.', '🥧', 'france', 'plat', 'facile',
     15, 35, 6, array['four','classique'], 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '23410'), 1, 'pièce', 230, 'pâte brisée'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '28720'), 200, 'g', 200, 'lardons fumés'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '22000'), 3, 'pièce', 165, 'œufs'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '19410'), 20, 'cl', 200, 'crème fraîche épaisse'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '19041'), 10, 'cl', 100, 'lait'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '12118'), 60, 'g', 60, 'emmental râpé'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '11015'), 1, 'pincée', 1, 'poivre')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  ((select id from r), 0, 'Préchauffe le four à 200 °C et étale la pâte dans un moule, en gardant le papier de cuisson.', null::int),
  ((select id from r), 1, 'Fais dorer les lardons à sec dans une poêle, puis égoutte-les sur du papier absorbant.', 300),
  ((select id from r), 2, 'Fouette les œufs avec la crème, le lait et le poivre ; le sel est inutile avec les lardons.', null::int),
  ((select id from r), 3, 'Répartis les lardons et l''emmental sur la pâte, verse l''appareil.', null::int),
  ((select id from r), 4, 'Enfourne jusqu''à ce que la quiche soit dorée et juste prise au centre.', 1800)
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, 'Ratatouille', 'ratatouille', 'Le mijoté provençal de légumes d''été, fondant et parfumé au thym.', '🍆', 'france', 'accompagnement', 'facile',
     25, 50, 6, array['meal-prep','ete'], 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '20300'), 2, 'pièce', 500, 'aubergines'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '20020'), 2, 'pièce', 400, 'courgettes'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20087'), 2, 'pièce', 300, 'poivrons rouges'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '20047'), 5, 'pièce', 600, 'tomates'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '20239'), 2, 'pièce', 200, 'oignons'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '11000'), 3, 'pièce', 15, 'gousses d''ail'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 5, 'càs', 60, 'huile d''olive'),
    ((select id from r), 7, (select id from public.foods where source = 'ciqual' and external_id = '11070'), 4, 'brins', 4, 'thym frais')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  ((select id from r), 0, 'Coupe les aubergines, les courgettes et les poivrons en dés, les tomates en quartiers et les oignons en lamelles.', null::int),
  ((select id from r), 1, 'Fais revenir les oignons dans l''huile, puis ajoute les poivrons.', 480),
  ((select id from r), 2, 'Ajoute les aubergines et les courgettes, laisse-les colorer en remuant.', 600),
  ((select id from r), 3, 'Verse les tomates, l''ail écrasé et le thym, sale et poivre.', null::int),
  ((select id from r), 4, 'Couvre et laisse mijoter à feu doux ; c''est encore meilleur le lendemain.', 1800)
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, 'Moules marinières', 'moules-marinieres', 'Des moules ouvertes au vin blanc, échalotes et persil, à saucer sans modération.', '🦪', 'france', 'plat', 'facile',
     20, 10, 4, array['express','bord-de-mer'], 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '10014'), 2, 'kg', 2000, 'moules de bouchot'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '5215'), 20, 'cl', 200, 'vin blanc sec'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20097'), 3, 'pièce', 90, 'échalotes'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '16400'), 30, 'g', 30, 'beurre'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '11014'), 1, 'bouquet', 20, 'persil plat'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '11015'), 1, 'pincée', 1, 'poivre')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  ((select id from r), 0, 'Gratte et rince les moules ; jette celles qui restent ouvertes quand tu les tapotes.', null::int),
  ((select id from r), 1, 'Fais fondre les échalotes émincées dans le beurre, dans une grande cocotte.', 180),
  ((select id from r), 2, 'Ajoute le vin blanc et les moules, poivre, couvre et monte le feu.', null::int),
  ((select id from r), 3, 'Secoue la cocotte jusqu''à ce que toutes les moules soient ouvertes.', 360),
  ((select id from r), 4, 'Parsème de persil haché et sers aussitôt avec le jus.', null::int)
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, 'Risotto aux champignons', 'risotto-champignons', 'Un risotto crémeux, parfumé aux champignons et au parmesan.', '🍄', 'italie', 'plat', 'moyen',
     15, 25, 4, array['reconfort'], 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '9100'), 320, 'g', 320, 'riz rond pour risotto'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '20010'), 400, 'g', 400, 'champignons'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20239'), 1, 'pièce', 100, 'oignon'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '25948'), 1.2, 'l', 1200, 'bouillon de légumes chaud'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '5215'), 10, 'cl', 100, 'vin blanc sec'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '12120'), 60, 'g', 60, 'parmesan râpé'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '16400'), 30, 'g', 30, 'beurre'),
    ((select id from r), 7, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 2, 'càs', 25, 'huile d''olive')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  ((select id from r), 0, 'Fais dorer les champignons émincés dans une poêle chaude avec un peu d''huile, réserve.', 360),
  ((select id from r), 1, 'Dans une sauteuse, fais fondre l''oignon haché dans le reste d''huile, ajoute le riz et nacre-le.', 180),
  ((select id from r), 2, 'Verse le vin blanc et laisse-le s''évaporer.', 120),
  ((select id from r), 3, 'Ajoute le bouillon louche par louche, en remuant, en attendant qu''il soit absorbé à chaque fois.', 1080),
  ((select id from r), 4, 'Hors du feu, incorpore les champignons, le beurre et le parmesan, couvre 2 minutes et sers.', 120)
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, 'Tiramisu', 'tiramisu', 'Le dessert italien au café : biscuits imbibés et crème au mascarpone.', '🍰', 'italie', 'dessert', 'moyen',
     25, 0, 6, array['sans-cuisson','a-l-avance'], 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '19584'), 250, 'g', 250, 'mascarpone'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '22000'), 3, 'pièce', 165, 'œufs'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '31016'), 80, 'g', 80, 'sucre'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '18073'), 30, 'cl', 300, 'café fort refroidi'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '24430'), 24, 'pièce', 200, 'biscuits à la cuillère'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '18100'), 2, 'càs', 15, 'cacao non sucré'),
    ((select id from r), 6, null, 3, 'càs', 45, 'marsala (facultatif)')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  ((select id from r), 0, 'Sépare les blancs des jaunes ; fouette les jaunes avec le sucre jusqu''à ce qu''ils blanchissent.', null::int),
  ((select id from r), 1, 'Incorpore le mascarpone, puis les blancs montés en neige ferme, délicatement.', null::int),
  ((select id from r), 2, 'Trempe rapidement les biscuits dans le café (et le marsala si tu l''utilises) et tapisse le plat.', null::int),
  ((select id from r), 3, 'Alterne couches de crème et de biscuits, en finissant par la crème.', null::int),
  ((select id from r), 4, 'Laisse reposer au frais au moins 6 heures, puis saupoudre de cacao au moment de servir.', null::int)
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, 'Gaspacho andalou', 'gaspacho', 'Une soupe froide de tomates, concombre et poivron, fraîche comme un été à Séville.', '🍅', 'espagne', 'soupe', 'facile',
     20, 0, 4, array['sans-cuisson','ete'], 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '20047'), 1, 'kg', 1000, 'tomates bien mûres'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '20019'), 0.5, 'pièce', 200, 'concombre'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20085'), 1, 'pièce', 150, 'poivron vert'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '11000'), 1, 'pièce', 5, 'gousse d''ail'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '7001'), 60, 'g', 60, 'pain rassis'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 6, 'càs', 70, 'huile d''olive'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '11220'), 2, 'càs', 30, 'vinaigre de vin')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  ((select id from r), 0, 'Fais tremper le pain dans un peu d''eau.', null::int),
  ((select id from r), 1, 'Coupe grossièrement les tomates, le concombre pelé, le poivron et l''ail.', null::int),
  ((select id from r), 2, 'Mixe tous les légumes avec le pain essoré, le vinaigre et du sel, puis l''huile en filet.', null::int),
  ((select id from r), 3, 'Passe au chinois pour une texture lisse et réserve au frais au moins 2 heures.', null::int),
  ((select id from r), 4, 'Sers très froid avec quelques dés de légumes.', null::int)
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, 'Tortilla de patatas', 'tortilla-de-patatas', 'L''omelette épaisse aux pommes de terre et aux oignons confits.', '🥔', 'espagne', 'plat', 'moyen',
     15, 35, 4, array['pique-nique'], 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '4008'), 600, 'g', 600, 'pommes de terre'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '20239'), 1, 'pièce', 150, 'oignon'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '22000'), 6, 'pièce', 330, 'œufs'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 10, 'cl', 90, 'huile d''olive')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  ((select id from r), 0, 'Coupe les pommes de terre en fines lamelles et l''oignon en rondelles.', null::int),
  ((select id from r), 1, 'Fais-les confire doucement dans l''huile, sans les colorer, jusqu''à ce qu''ils soient tendres.', 1200),
  ((select id from r), 2, 'Égoutte-les et mélange-les aux œufs battus salés ; laisse reposer 5 minutes.', 300),
  ((select id from r), 3, 'Verse dans une poêle huilée bien chaude, cuis à feu moyen.', 360),
  ((select id from r), 4, 'Retourne la tortilla à l''aide d''une assiette et laisse cuire l''autre face.', 240)
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, 'Salade grecque', 'salade-grecque', 'Tomates, concombre, oignon rouge, olives et feta, arrosés d''huile d''olive.', '🥗', 'grece', 'salade', 'facile',
     15, 0, 4, array['express','ete'], 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '20047'), 4, 'pièce', 500, 'tomates'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '20019'), 1, 'pièce', 300, 'concombre'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20238'), 1, 'pièce', 100, 'oignon rouge'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '12066'), 200, 'g', 200, 'feta'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '13131'), 80, 'g', 80, 'olives noires'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 4, 'càs', 50, 'huile d''olive'),
    ((select id from r), 6, null, 1, 'càc', 2, 'origan séché')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  ((select id from r), 0, 'Coupe les tomates en quartiers, le concombre en demi-rondelles et l''oignon en fines lamelles.', null::int),
  ((select id from r), 1, 'Dispose les légumes et les olives dans un plat.', null::int),
  ((select id from r), 2, 'Pose la feta en bloc ou en gros morceaux par-dessus.', null::int),
  ((select id from r), 3, 'Arrose d''huile d''olive, parsème d''origan et poivre.', null::int)
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, 'Taboulé libanais', 'taboule-libanais', 'Beaucoup de persil, un peu de boulgour, du citron : la version herbacée du Liban.', '🌿', 'liban', 'salade', 'facile',
     30, 0, 4, array['ete','vegan'], 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '11014'), 3, 'bouquets', 150, 'persil plat'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '11027'), 1, 'bouquet', 20, 'menthe fraîche'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '9690'), 60, 'g', 60, 'boulgour fin'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '20047'), 3, 'pièce', 350, 'tomates'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '20323'), 2, 'pièce', 40, 'oignon nouveau'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '13009'), 2, 'pièce', 80, 'jus de citron'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 5, 'càs', 60, 'huile d''olive')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  ((select id from r), 0, 'Rince le boulgour et laisse-le gonfler dans le jus de citron.', 900),
  ((select id from r), 1, 'Hache finement le persil et la menthe au couteau, sans les écraser.', null::int),
  ((select id from r), 2, 'Coupe les tomates en tout petits dés et émince les oignons.', null::int),
  ((select id from r), 3, 'Mélange le tout avec l''huile, sale, et sers bien frais.', null::int)
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, 'Houmous', 'houmous', 'La crème de pois chiches au tahin, citron et ail, à partager avec du pain pita.', '🫘', 'liban', 'kemia', 'facile',
     10, 0, 6, array['express','apero'], 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '20507'), 400, 'g', 400, 'pois chiches cuits'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '15203'), 80, 'g', 80, 'tahin'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '13009'), 1, 'pièce', 40, 'jus de citron'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '11000'), 1, 'pièce', 5, 'gousse d''ail'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '11042'), 1, 'càc', 2, 'cumin'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 3, 'càs', 35, 'huile d''olive')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  ((select id from r), 0, 'Garde un peu d''eau des pois chiches, égoutte le reste.', null::int),
  ((select id from r), 1, 'Mixe les pois chiches avec le tahin, le citron, l''ail, le cumin et du sel.', null::int),
  ((select id from r), 2, 'Ajoute l''eau réservée petit à petit jusqu''à une texture très lisse.', null::int),
  ((select id from r), 3, 'Sers dans une assiette creuse, avec un filet d''huile d''olive.', null::int)
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, 'Imam bayildi', 'imam-bayildi', 'Aubergines fondantes farcies aux oignons et tomates, servies tièdes.', '🍆', 'turquie', 'plat', 'moyen',
     25, 60, 4, array['four','vegan'], 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '20300'), 4, 'pièce', 1000, 'aubergines'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '20239'), 3, 'pièce', 300, 'oignons'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20047'), 4, 'pièce', 500, 'tomates'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '11000'), 4, 'pièce', 20, 'gousses d''ail'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '11014'), 1, 'bouquet', 30, 'persil'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 10, 'cl', 90, 'huile d''olive'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '31016'), 1, 'càc', 5, 'sucre')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  ((select id from r), 0, 'Pèle les aubergines en bandes, fends-les sur la longueur et fais-les dorer dans l''huile.', 600),
  ((select id from r), 1, 'Fais fondre les oignons émincés avec l''ail, puis ajoute les tomates en dés, le sucre et le persil.', 900),
  ((select id from r), 2, 'Ouvre les aubergines et remplis-les de cette farce.', null::int),
  ((select id from r), 3, 'Mouille d''un fond d''eau, couvre et cuis au four à 180 °C.', 2400),
  ((select id from r), 4, 'Laisse tiédir : elles se dégustent tièdes ou froides.', null::int)
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, 'Dal de lentilles corail au lait de coco', 'dal-lentilles-corail', 'Des lentilles fondantes aux épices douces, adoucies au lait de coco.', '🍛', 'inde', 'plat', 'facile',
     10, 25, 4, array['vegan','meal-prep'], 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '20535'), 250, 'g', 250, 'lentilles corail'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '18041'), 40, 'cl', 400, 'lait de coco'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20239'), 1, 'pièce', 100, 'oignon'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '20048'), 1, 'boîte', 400, 'tomates pelées'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '11074'), 1, 'morceau', 15, 'gingembre frais'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '11000'), 2, 'pièce', 10, 'gousses d''ail'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '11005'), 2, 'càc', 5, 'curry en poudre'),
    ((select id from r), 7, (select id from public.foods where source = 'ciqual' and external_id = '11089'), 1, 'càc', 3, 'curcuma'),
    ((select id from r), 8, (select id from public.foods where source = 'ciqual' and external_id = '17440'), 2, 'càs', 25, 'huile de tournesol')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  ((select id from r), 0, 'Fais revenir l''oignon, l''ail et le gingembre hachés dans l''huile.', 300),
  ((select id from r), 1, 'Ajoute le curry et le curcuma, remue 1 minute pour réveiller les épices.', 60),
  ((select id from r), 2, 'Verse les lentilles rincées, les tomates, le lait de coco et 40 cl d''eau.', null::int),
  ((select id from r), 3, 'Laisse mijoter en remuant de temps en temps, jusqu''à ce que les lentilles fondent.', 1200),
  ((select id from r), 4, 'Sale, ajuste la texture avec un peu d''eau et sers avec du riz.', null::int)
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, 'Poulet tikka masala', 'poulet-tikka-masala', 'Des morceaux de poulet marinés au yaourt et aux épices, dans une sauce tomate crémeuse.', '🍗', 'inde', 'plat', 'moyen',
     20, 35, 4, array['epice'], 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '36017'), 700, 'g', 700, 'filets de poulet'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '19593'), 150, 'g', 150, 'yaourt nature'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '19415'), 15, 'cl', 150, 'crème'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '20048'), 1, 'boîte', 400, 'tomates pelées'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '20239'), 1, 'pièce', 120, 'oignon'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '11074'), 1, 'morceau', 15, 'gingembre frais'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '11000'), 3, 'pièce', 15, 'gousses d''ail'),
    ((select id from r), 7, (select id from public.foods where source = 'ciqual' and external_id = '11005'), 1, 'càs', 8, 'curry en poudre'),
    ((select id from r), 8, (select id from public.foods where source = 'ciqual' and external_id = '11049'), 1, 'càc', 3, 'paprika'),
    ((select id from r), 9, (select id from public.foods where source = 'ciqual' and external_id = '17440'), 2, 'càs', 25, 'huile de tournesol')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  ((select id from r), 0, 'Coupe le poulet en morceaux et fais-le mariner avec le yaourt, la moitié des épices et du sel.', 1800),
  ((select id from r), 1, 'Saisis le poulet à la poêle bien chaude, réserve.', 360),
  ((select id from r), 2, 'Fais revenir l''oignon, l''ail et le gingembre, ajoute le reste des épices puis les tomates.', 600),
  ((select id from r), 3, 'Remets le poulet, ajoute la crème et laisse mijoter.', 900),
  ((select id from r), 4, 'Sers avec du riz basmati ou des naans.', null::int)
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, 'Poulet sauté aux noix de cajou', 'poulet-noix-de-cajou', 'Un sauté minute au wok : poulet, poivron, noix de cajou grillées et sauce soja.', '🥡', 'chine', 'plat', 'facile',
     15, 12, 4, array['express','wok'], 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '36017'), 500, 'g', 500, 'filets de poulet'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '15055'), 80, 'g', 80, 'noix de cajou'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20087'), 1, 'pièce', 150, 'poivron rouge'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '20323'), 3, 'pièce', 60, 'oignons nouveaux'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '11104'), 4, 'càs', 60, 'sauce soja'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '11074'), 1, 'morceau', 10, 'gingembre frais'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '17440'), 2, 'càs', 25, 'huile de tournesol'),
    ((select id from r), 7, (select id from public.foods where source = 'ciqual' and external_id = '31016'), 1, 'càc', 5, 'sucre')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  ((select id from r), 0, 'Fais griller les noix de cajou à sec dans le wok, réserve.', 180),
  ((select id from r), 1, 'Saisis le poulet en lamelles dans l''huile très chaude.', 300),
  ((select id from r), 2, 'Ajoute le poivron, le gingembre et les oignons, saute 2 minutes.', 120),
  ((select id from r), 3, 'Verse la sauce soja et le sucre, remue pour enrober.', 60),
  ((select id from r), 4, 'Ajoute les noix de cajou et sers avec du riz.', null::int)
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, 'Porc au caramel', 'porc-au-caramel', 'Le classique vietnamien : porc mijoté dans un caramel salé au nuoc-mâm.', '🍖', 'vietnam', 'plat', 'moyen',
     15, 45, 4, array['mijote'], 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '28302'), 800, 'g', 800, 'échine de porc'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '31016'), 60, 'g', 60, 'sucre'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '11194'), 4, 'càs', 60, 'sauce nuoc-mâm'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '20097'), 3, 'pièce', 90, 'échalotes'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '11000'), 3, 'pièce', 15, 'gousses d''ail'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '11015'), 1, 'càc', 2, 'poivre')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  ((select id from r), 0, 'Coupe le porc en cubes et fais-le mariner avec le nuoc-mâm, l''ail et le poivre.', 900),
  ((select id from r), 1, 'Fais un caramel ambré avec le sucre et 2 cuillerées d''eau dans une cocotte.', 300),
  ((select id from r), 2, 'Ajoute les échalotes puis la viande, et remue pour bien l''enrober.', 180),
  ((select id from r), 3, 'Couvre à hauteur d''eau et laisse mijoter jusqu''à ce que la sauce devienne sirupeuse.', 2400),
  ((select id from r), 4, 'Sers avec du riz blanc.', null::int)
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, 'Soupe miso au tofu', 'soupe-miso-tofu', 'Un bouillon dashi au miso, dés de tofu soyeux et oignon nouveau.', '🍜', 'japon', 'soupe', 'facile',
     10, 10, 4, array['express'], 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, null, 1, 'l', 1000, 'bouillon dashi'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '20916'), 60, 'g', 60, 'pâte miso'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20906'), 200, 'g', 200, 'tofu soyeux'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '20987'), 1, 'feuille', 3, 'algue nori'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '20323'), 1, 'pièce', 20, 'oignon nouveau')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  ((select id from r), 0, 'Porte le dashi à frémissement, sans le faire bouillir.', 300),
  ((select id from r), 1, 'Délaye le miso dans une louche de bouillon, puis verse-le dans la casserole.', null::int),
  ((select id from r), 2, 'Ajoute le tofu en petits dés et l''algue en lanières, chauffe 2 minutes.', 120),
  ((select id from r), 3, 'Sers aussitôt, parsemé d''oignon nouveau.', null::int)
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, 'Bibimbap', 'bibimbap', 'Le bol coréen : riz, légumes sautés, bœuf mariné et œuf au plat.', '🍚', 'coree', 'plat', 'moyen',
     30, 20, 4, array['bol'], 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '9100'), 300, 'g', 300, 'riz blanc'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '6252'), 300, 'g', 300, 'bœuf haché'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20009'), 2, 'pièce', 200, 'carottes'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '20270'), 200, 'g', 200, 'épinards frais'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '20020'), 1, 'pièce', 200, 'courgette'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '22000'), 4, 'pièce', 220, 'œufs'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '11104'), 3, 'càs', 45, 'sauce soja'),
    ((select id from r), 7, (select id from public.foods where source = 'ciqual' and external_id = '17400'), 2, 'càs', 25, 'huile de sésame'),
    ((select id from r), 8, (select id from public.foods where source = 'ciqual' and external_id = '15038'), 1, 'càs', 10, 'graines de sésame')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  ((select id from r), 0, 'Cuis le riz.', 900),
  ((select id from r), 1, 'Fais revenir le bœuf avec la moitié de la sauce soja et un peu d''huile de sésame.', 300),
  ((select id from r), 2, 'Saute séparément les carottes et la courgette en bâtonnets, puis fais tomber les épinards.', 480),
  ((select id from r), 3, 'Cuis les œufs au plat.', 240),
  ((select id from r), 4, 'Dresse le riz dans des bols, dispose les garnitures en couronne, l''œuf au centre, parsème de sésame.', null::int)
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, 'Curry vert de légumes', 'curry-vert-legumes', 'Des légumes croquants et du tofu dans un curry vert au lait de coco.', '🥥', 'thailande', 'plat', 'facile',
     15, 20, 4, array['epice'], 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '18041'), 40, 'cl', 400, 'lait de coco'),
    ((select id from r), 1, null, 2, 'càs', 30, 'pâte de curry vert'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20904'), 250, 'g', 250, 'tofu nature'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '20304'), 1, 'pièce', 300, 'brocoli'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '20070'), 150, 'g', 150, 'haricots verts'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '20168'), 1, 'pièce', 150, 'poivron jaune'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '11033'), 1, 'bouquet', 15, 'basilic frais'),
    ((select id from r), 7, (select id from public.foods where source = 'ciqual' and external_id = '17440'), 1, 'càs', 12, 'huile de tournesol')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  ((select id from r), 0, 'Fais revenir la pâte de curry dans l''huile pour libérer les arômes.', 60),
  ((select id from r), 1, 'Verse le lait de coco et porte à frémissement.', 180),
  ((select id from r), 2, 'Ajoute le brocoli en fleurettes, les haricots et le poivron, laisse cuire.', 480),
  ((select id from r), 3, 'Ajoute le tofu en cubes et réchauffe doucement.', 300),
  ((select id from r), 4, 'Parsème de basilic et sers avec du riz.', null::int)
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, 'Riz gluant à la mangue', 'mango-sticky-rice', 'Le dessert thaï : riz gluant au lait de coco sucré et tranches de mangue.', '🥭', 'thailande', 'dessert', 'moyen',
     15, 25, 4, array['vegan'], 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '9100'), 250, 'g', 250, 'riz gluant'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '18041'), 25, 'cl', 250, 'lait de coco'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '31016'), 60, 'g', 60, 'sucre'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '13025'), 2, 'pièce', 500, 'mangues mûres'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '15038'), 1, 'càs', 8, 'graines de sésame')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  ((select id from r), 0, 'Fais tremper le riz gluant dans l''eau froide au moins 4 heures.', null::int),
  ((select id from r), 1, 'Cuis-le à la vapeur jusqu''à ce qu''il soit translucide.', 1500),
  ((select id from r), 2, 'Chauffe le lait de coco avec le sucre et une pincée de sel, sans bouillir.', 180),
  ((select id from r), 3, 'Verse les deux tiers sur le riz chaud et laisse absorber.', 600),
  ((select id from r), 4, 'Sers avec la mangue en tranches, le reste de lait de coco et le sésame.', null::int)
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, 'Mafé de bœuf', 'mafe-boeuf', 'Le ragoût ouest-africain à la pâte d''arachide, riche et réconfortant.', '🥜', 'afrique_ouest', 'plat', 'moyen',
     20, 90, 6, array['mijote'], 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '6270'), 800, 'g', 800, 'paleron de bœuf'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '15202'), 150, 'g', 150, 'pâte d''arachide'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20068'), 70, 'g', 70, 'concentré de tomate'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '20239'), 2, 'pièce', 200, 'oignons'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '4101'), 2, 'pièce', 500, 'patates douces'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '20009'), 3, 'pièce', 300, 'carottes'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '20116'), 0.25, 'pièce', 300, 'chou blanc'),
    ((select id from r), 7, (select id from public.foods where source = 'ciqual' and external_id = '20151'), 1, 'pièce', 10, 'piment'),
    ((select id from r), 8, (select id from public.foods where source = 'ciqual' and external_id = '17040'), 3, 'càs', 35, 'huile d''arachide')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  ((select id from r), 0, 'Fais dorer la viande en cubes dans l''huile avec les oignons émincés.', 600),
  ((select id from r), 1, 'Ajoute le concentré de tomate, puis couvre d''eau et laisse cuire.', 2400),
  ((select id from r), 2, 'Délaye la pâte d''arachide dans une louche de bouillon et verse-la dans la cocotte.', null::int),
  ((select id from r), 3, 'Ajoute les légumes en gros morceaux et le piment entier, et laisse mijoter.', 2400),
  ((select id from r), 4, 'Sers avec du riz blanc.', null::int)
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, 'Poulet yassa', 'poulet-yassa', 'Le poulet mariné au citron et à la moutarde, confit dans une montagne d''oignons.', '🍋', 'afrique_ouest', 'plat', 'moyen',
     20, 60, 6, array['marinade'], 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '36002'), 6, 'pièce', 1200, 'cuisses de poulet'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '20239'), 6, 'pièce', 800, 'oignons'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '13009'), 3, 'pièce', 120, 'jus de citron'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '11013'), 3, 'càs', 45, 'moutarde'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '11000'), 3, 'pièce', 15, 'gousses d''ail'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '20151'), 1, 'pièce', 10, 'piment'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '17440'), 4, 'càs', 50, 'huile de tournesol')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  ((select id from r), 0, 'Fais mariner le poulet avec les oignons émincés, le citron, la moutarde, l''ail et du sel, idéalement une nuit.', null::int),
  ((select id from r), 1, 'Fais dorer les morceaux de poulet égouttés dans l''huile, réserve.', 600),
  ((select id from r), 2, 'Fais fondre longuement les oignons de la marinade dans la même cocotte.', 1200),
  ((select id from r), 3, 'Remets le poulet, ajoute le reste de marinade, le piment et un verre d''eau.', null::int),
  ((select id from r), 4, 'Laisse mijoter à couvert et sers avec du riz.', 1800)
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, 'Accras de morue', 'accras-de-morue', 'Les beignets antillais à la morue, relevés de piment et d''herbes.', '🐟', 'antilles', 'kemia', 'moyen',
     30, 15, 6, array['apero','friture'], 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '26098'), 250, 'g', 250, 'morue salée'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '9435'), 200, 'g', 200, 'farine'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '22000'), 1, 'pièce', 55, 'œuf'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '11046'), 1, 'sachet', 11, 'levure chimique'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '20323'), 2, 'pièce', 40, 'oignon nouveau'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '11014'), 1, 'bouquet', 20, 'persil'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '20151'), 1, 'pièce', 5, 'piment'),
    ((select id from r), 7, (select id from public.foods where source = 'ciqual' and external_id = '17440'), 50, 'cl', 60, 'huile de friture')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  ((select id from r), 0, 'Dessale la morue dans l''eau froide la veille, en changeant l''eau plusieurs fois.', null::int),
  ((select id from r), 1, 'Poche-la dans l''eau frémissante, égoutte et émiette-la.', 600),
  ((select id from r), 2, 'Mélange la farine, la levure, l''œuf et de l''eau jusqu''à une pâte épaisse.', null::int),
  ((select id from r), 3, 'Ajoute la morue, les herbes et le piment hachés, laisse reposer.', 1800),
  ((select id from r), 4, 'Fais frire des petites cuillerées de pâte dans l''huile chaude jusqu''à ce qu''elles soient dorées.', 300)
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, 'Chili sin carne', 'chili-sin-carne', 'Haricots rouges, maïs et poivrons mijotés aux épices, sans viande.', '🌶️', 'mexique', 'plat', 'facile',
     15, 35, 4, array['vegan','meal-prep'], 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '20503'), 500, 'g', 500, 'haricots rouges cuits'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '20066'), 150, 'g', 150, 'maïs doux'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20048'), 1, 'boîte', 400, 'tomates pelées'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '20087'), 1, 'pièce', 150, 'poivron rouge'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '20239'), 1, 'pièce', 120, 'oignon'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '11000'), 2, 'pièce', 10, 'gousses d''ail'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '11042'), 2, 'càc', 4, 'cumin'),
    ((select id from r), 7, (select id from public.foods where source = 'ciqual' and external_id = '11049'), 2, 'càc', 4, 'paprika'),
    ((select id from r), 8, (select id from public.foods where source = 'ciqual' and external_id = '17270'), 2, 'càs', 25, 'huile d''olive')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  ((select id from r), 0, 'Fais revenir l''oignon, l''ail et le poivron en dés dans l''huile.', 360),
  ((select id from r), 1, 'Ajoute les épices et remue une minute.', 60),
  ((select id from r), 2, 'Verse les tomates, les haricots et le maïs égouttés, sale.', null::int),
  ((select id from r), 3, 'Laisse mijoter à couvert en remuant de temps en temps.', 1500),
  ((select id from r), 4, 'Sers avec du riz, des tortillas ou de l''avocat.', null::int)
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, 'Ceviche de poisson', 'ceviche-poisson', 'Du poisson blanc très frais « cuit » au citron vert, oignon rouge et coriandre.', '🍋‍🟩', 'amerique_sud', 'entree', 'facile',
     20, 0, 4, array['sans-cuisson','ete'], 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '26075'), 500, 'g', 500, 'filets de bar très frais'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '13067'), 5, 'pièce', 200, 'citrons verts'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '20238'), 1, 'pièce', 100, 'oignon rouge'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '20151'), 1, 'pièce', 5, 'piment'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '11094'), 1, 'bouquet', 20, 'coriandre fraîche'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '20066'), 100, 'g', 100, 'maïs doux')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  ((select id from r), 0, 'Coupe le poisson en dés réguliers et l''oignon en très fines lamelles.', null::int),
  ((select id from r), 1, 'Mélange le poisson avec le jus des citrons verts, le piment émincé et du sel.', null::int),
  ((select id from r), 2, 'Laisse mariner au frais jusqu''à ce que le poisson devienne opaque.', 900),
  ((select id from r), 3, 'Ajoute l''oignon, la coriandre et le maïs, et sers aussitôt.', null::int)
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, 'Pancakes moelleux', 'pancakes', 'Des pancakes épais et moelleux, à arroser de sirop d''érable.', '🥞', 'etats_unis', 'petit_dej', 'facile',
     10, 15, 4, array['brunch'], 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '9435'), 250, 'g', 250, 'farine'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '19041'), 30, 'cl', 300, 'lait'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '22000'), 2, 'pièce', 110, 'œufs'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '16400'), 40, 'g', 40, 'beurre fondu'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '31016'), 30, 'g', 30, 'sucre'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '11046'), 1, 'sachet', 11, 'levure chimique'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '31034'), 8, 'càs', 120, 'sirop d''érable')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  ((select id from r), 0, 'Mélange la farine, le sucre, la levure et une pincée de sel.', null::int),
  ((select id from r), 1, 'Ajoute les œufs, le lait puis le beurre fondu, sans trop travailler la pâte.', null::int),
  ((select id from r), 2, 'Laisse reposer 10 minutes.', 600),
  ((select id from r), 3, 'Cuis des petites louches dans une poêle beurrée ; retourne quand des bulles apparaissent.', 720),
  ((select id from r), 4, 'Sers chaud avec le sirop d''érable.', null::int)
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);

with r as (
  insert into public.recipes
    (author_id, title, slug, description, icon, origin, category, difficulty,
     prep_min, cook_min, servings, tags, visibility, version_kind, status)
  values
    (null, 'Bortsch', 'bortsch', 'La soupe de betterave aux légumes, servie avec une cuillerée de crème.', '🥣', 'europe_est', 'soupe', 'moyen',
     25, 50, 6, array['hiver','meal-prep'], 'community', 'boutargue', 'published')
  on conflict (slug) do nothing
  returning id
),
ing as (
  insert into public.recipe_ingredients (recipe_id, position, food_id, qty, unit, grams, label_raw)
  select * from (values
    ((select id from r), 0, (select id from public.foods where source = 'ciqual' and external_id = '20003'), 3, 'pièce', 450, 'betteraves crues'),
    ((select id from r), 1, (select id from public.foods where source = 'ciqual' and external_id = '20116'), 0.25, 'pièce', 300, 'chou blanc'),
    ((select id from r), 2, (select id from public.foods where source = 'ciqual' and external_id = '4008'), 2, 'pièce', 300, 'pommes de terre'),
    ((select id from r), 3, (select id from public.foods where source = 'ciqual' and external_id = '20009'), 1, 'pièce', 120, 'carotte'),
    ((select id from r), 4, (select id from public.foods where source = 'ciqual' and external_id = '20239'), 1, 'pièce', 100, 'oignon'),
    ((select id from r), 5, (select id from public.foods where source = 'ciqual' and external_id = '20068'), 2, 'càs', 40, 'concentré de tomate'),
    ((select id from r), 6, (select id from public.foods where source = 'ciqual' and external_id = '25948'), 1.5, 'l', 1500, 'bouillon de légumes'),
    ((select id from r), 7, (select id from public.foods where source = 'ciqual' and external_id = '19410'), 6, 'càs', 90, 'crème fraîche'),
    ((select id from r), 8, (select id from public.foods where source = 'ciqual' and external_id = '11093'), 1, 'bouquet', 10, 'aneth frais')
  ) as v(recipe_id, position, food_id, qty, unit, grams, label_raw)
  where exists (select 1 from r)
)
insert into public.recipe_steps (recipe_id, position, text, duration_sec)
select * from (values
  ((select id from r), 0, 'Fais revenir l''oignon et la carotte râpée, puis ajoute la betterave râpée et le concentré de tomate.', 600),
  ((select id from r), 1, 'Verse le bouillon, ajoute les pommes de terre en dés et laisse cuire.', 1200),
  ((select id from r), 2, 'Ajoute le chou émincé et poursuis la cuisson.', 1200),
  ((select id from r), 3, 'Assaisonne avec du sel, du poivre et un filet de vinaigre si tu aimes.', null::int),
  ((select id from r), 4, 'Sers avec une cuillerée de crème et de l''aneth ciselé.', null::int)
) as v(recipe_id, position, text, duration_sec)
where exists (select 1 from r);

update public.recipes r
set nutrition_per_serving = case
  when (
    select coalesce(sum(i.grams) filter (where f.per_100g ? 'kcal'), 0)
      >= 0.9 * nullif(sum(i.grams), 0)
    from public.recipe_ingredients i
    left join public.foods f on f.id = i.food_id
    where i.recipe_id = r.id
  ) then coalesce(public.compute_recipe_nutrition(r.id), '{}'::jsonb)
  else '{}'::jsonb
end
where r.author_id is null and r.slug in ('accras-de-morue', 'bibimbap', 'bortsch', 'ceviche-poisson', 'chili-sin-carne', 'curry-vert-legumes', 'dal-lentilles-corail', 'gaspacho', 'houmous', 'imam-bayildi', 'mafe-boeuf', 'mango-sticky-rice', 'moules-marinieres', 'pancakes', 'porc-au-caramel', 'poulet-noix-de-cajou', 'poulet-tikka-masala', 'poulet-yassa', 'quiche-lorraine', 'ratatouille', 'risotto-champignons', 'salade-grecque', 'soupe-miso-tofu', 'taboule-libanais', 'tiramisu', 'tortilla-de-patatas');
